### ISSUE TITLE
[feature request] Allow the application to provide API-native shader code

### ISSUE THREAD

**Issue by swiftcoder** [gfx-rs/wgpu-rs#103]
Any thoughts on expanding the API to allow the application to pass in shaders in the native shader format of the underlying API, if it wants to?

Effectively I don't want to eat the cost of spirv_cross at runtime (mostly due to the binary size, but performance could also be an issue in the future). Since I always know the target graphics API at compile time, I could be front-loading the cross compilation to MSL/HLSL/etc where needed.

**Comment by grovesNL** [comment]
See https://github.com/gfx-rs/gfx/issues/3030 for why this isn't easily possible. TL;DR – we almost always have to do shader manipulation at runtime for each backend except Vulkan.

**Comment by kvark** [comment]
If there is a way, theoretically, to provide your own transpiled shaders (knowing the pipeline layout, specialization, etc), we'd have no way of ensuring that these shaders are safe to use. So that would be an unsafe API that is only available on local builds (i.e. not targeting the Web).

**Comment by kvark** [comment]
We are already not even compiling spirv-cross on Linux and macOS. Only HLSL remains.
I think the issue is largely solved by Naga.
