### ISSUE TITLE
"No adapters available" on OpenSUSE

### ISSUE THREAD

**Issue by JMCavanillas** [gfx-rs/wgpu-rs#105]
I tried to run examples on OpenSUSE Tumbleweed but it does not work. 
It works without problems on Fedora 30 and Windows 10 on the same PC.

**Hardware**
CPU: Intel Core i5-9300H @ 2.40GHz
GPU: NVIDIA GeForce GTX 1650 (Optimus)

**System**
OpenSUSE Tumbleweed 20191024

Kernel 5.3.7 
KDE Plasma 5.17 (x11)

Cargo 1.38.0
Rustc 1.38.0

**Steps to reproduce**
1.- Install a fresh copy of OpenSUSE Tumbleweed using NET Installer
2.- Install Rust using Rustup
```bash
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```
3.- Install cmake and C/C++ Tools
```bash
sudo zypper in -t pattern devel_C_C++
sudo zypper in cmake
```
4.- Clone this repo
```bash
git clone https://github.com/gfx-rs/wgpu-rs.git
```
5.- Run Cube example
```bash
cd wgpu-rs
cargo run --example cube
```

**Error**
```bash
thread 'main' panicked at 'No adapters are available!', /home/javier/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/78fbbba/wgpu-native/src/instance.rs:329:9
```

I dont know if its a bug, openSUSE's issue or I miss something :S

**Comment by kvark** [comment]
This is a perfectly normal reaction on a platform that doesn't expose any supported graphics APIs. Please make sure you can run Vulkan samples (e.g. `vkcube`) first. You may need to install the extra drivers for your card.

**Comment by JMCavanillas** [comment]
Thanks for the answer. My fault, I was missing Vulkan :D. After installing nvidia proprietary drivers and optimus support again and run the session under nvidia card, the adapter was recognized. For Intel, installing `libvulkan_intel` did the trick.
