### ISSUE TITLE
Panic when screen is turned off

### ISSUE THREAD

**Issue by antonok-edm** [gfx-rs/wgpu-rs#106]
I'm on Linux, and if the screen is turned off (e.g. with `xset dpms force off`), `wgpu` instantly panics with `GPU took too much time processing last frames :(`. This leaves me with no way to recover the UI.

Is there any reason in particular that `swap_chain_get_next_texture` explicitly panics rather than returning a `Result`?

**Comment by kvark** [comment]
@antonok-edm currently, the error handling is done via assertions like this one. This is temporary. We'll need gracefull error handling soon for WebGPU in Gecko, and it will affect wgpu-native and allow wgpu-rs to return a `Result`. If you want to start doing that today, the road is open.
