### ISSUE TITLE
Buffer should carry size information

### ISSUE THREAD

**Issue by m4b** [gfx-rs/wgpu-rs#12]
It would be nice if the wgpu-rs `Buffer` struct also carried the size it was constructed with.

I just hit another bug of drawing too many elements in a line list pipeline, which resulted in visual artifacts, instead of segfault (e.g. https://github.com/gfx-rs/wgpu/issues/184).

I think this would have been easier to avoid if the Buffer carried around the size itself, similar to really any other buffer like object in rust, e.g., vec, string, slices, arrays, etc.

**Comment by kvark** [comment]
As discussed on Gitter, the important distinction here is that neither of "visual artifacts" or "segfault" are supposed to be addressed *this* way. wgpu-native will be validating everything and guarantee no such behavior *regardless* of whether the user knows the buffer size or not.

At the end of the day, what this change will give you is just a tiny bit of convenience. This isn't about preventing any crashes or letting you do anything you can't already do. And it's hard to draw the line, where this convenience should stop:
  - do we allow querying texture dimensions?
  - what about the mipmaps, layers, and AA?
  - what about supported usages?

... etc. The easiest hard line to draw, and that's the one we are going with, is not exposing any info (that the user is already supposed to know) at all.

**Comment by m4b** [comment]
Yea thank you for summarizing the salient parts of discussion here. Would also like to add that heterogeneous buffers make this hard or infeasible from a technical point of view.

Feel free to close or keep open at your discretion :)

**Comment by kvark** [comment]
I'm going to close it, since the discussion has happened, and we decided to proceed with the current approach. That is to say, the issue can still be commented on :)
