### ISSUE TITLE
Why wgpu::TextureFormat::Bgra8UnormSrgb in examples when creating a swapchain?

### ISSUE THREAD

**Issue by sotrh** [gfx-rs/wgpu-rs#123]
Is there anything special about this texture format? Is it related to the monitor's format?

**Comment by kvark** [comment]
Yeah, it's the only texture format that is *guaranteed* to be natively supported by the swapchains of all the APIs/platforms. Is that a concern for your application?

**Comment by rukai** [comment]
I think what kvark said should be included in the documentation for `wgpu::TextureFormat::Bgra8UnormSrgb`

**Comment by kvark** [comment]
fwiw, upstream WebGPU API has an async method called [getSwapChainPreferredFormat](https://gpuweb.github.io/gpuweb/#dom-gpucanvascontext-getswapchainpreferredformat). The users would use that format in order to avoid a potential extra blit by the implementation. We just need to provide something like this in wgpu-native and wgpu-rs, which would be better than just documenting a particular format.

**Comment by sotrh** [comment]
It's no problem for me @kvark I just didn't know why it was being used. I'll update my tutorial to add that fact

**Comment by niklaskorz** [comment]
Ironically, Bgra8 does not seem to be supported by Vulkan on my Android device:

```
01-10 12:22:01.492 22964 23010 I RustStdoutStderr: thread '<unnamed>' panicked at 'requested format Bgra8Srgb is not in list of supported formats: [Rgba8Unorm, Rgba8Srgb, R5g6b5Unorm, A2b10g10r10Unorm, Rgba16Sfloat]', /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.2/src/backend/direct.rs:1355:35
```

**Comment by kvark** [comment]
Interesting! I suppose this is solved by #693 now?

**Comment by niklaskorz** [comment]
Yes, thankfully it is. 😄

**Comment by niklaskorz** [comment]
Hm actually, it looks like [`device_get_swap_chain_preferred_format`](https://github.com/gfx-rs/wgpu/blob/master/wgpu-core/src/device/mod.rs#L3888) still just returns `Bgra8UnormSrgb`? So I suppose in that case, it wouldn't work, as `Bgra8UnormSrgb` is [not supported as surface format by my device](http://vulkan.gpuinfo.org/displayreport.php?id=10183#surfaceformats).

**Comment by kvark** [comment]
We need `wgpu` checking for this and returning a correct value in the preferred format. Could you make an issue in `wgpu` about this, please?
