### ISSUE TITLE
`multithreaded_compute` test freezes the entire computer

### ISSUE THREAD

**Issue by Coder-256** [gfx-rs/wgpu-rs#129]
Another issue: Not quite sure why, but I have to remove this line in order for it to run:

https://github.com/gfx-rs/wgpu-rs/blob/a18b43bfa823644a73b92678a36d53fcdb232f57/tests/multithreaded_compute.rs#L2

Anyway, as the title says, running the test causes my entire computer to instantly freeze. I can move the mouse but everything else including the touch bar is completely unresponsive. The display stays on when closing the clamshell. I have to do a force restart. Because of that, I can't debug this.

MacBook Pro 2018, Intel Iris Plus Graphics 655, Mojave 10.14.6

**Comment by Coder-256** [comment]
[Log files](https://gist.github.com/Coder-256/eadb0910d3c68edf160f7052b15148a7)

**Comment by cwfitzgerald** [comment]
Closing as wgpu has changed substantially since this issue was filed. If it's still an issue on current master, feel free to re-open with new crash information
