### ISSUE TITLE
cube example fails on mac os

### ISSUE THREAD

**Issue by edap** [gfx-rs/wgpu-rs#131]
just pulled from master & cargo update.

I am trying to compile the cube example but it fails

```
error[E0658]: use of unstable library feature 'pin_into_inner'
  --> src/future.rs:28:31
   |
28 |         let arc = Arc::clone(&Pin::into_inner(self).inner);
   |                               ^^^^^^^^^^^^^^^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/60245
```

I am on Mac OS "El Capitan", MacBook Pro (Retina, 13-inch, Mid 2014).
GPU Intel Iris 1536 MB.

**Comment by Systemcluster** [comment]
`pin_into_inner` was stabilized in Rust 1.39.0, you need to update your toolchain if you want to run the current master on stable Rust.

**Comment by edap** [comment]
Updating to 1.39.0 fixes the previous error. Now I have another one:

```
   Compiling wgpu v0.4.0 (/Users/da1/Sources/rust/wgpu-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 6.35s
     Running `target/debug/examples/cube`
2019-11-25 14:56:16.620 cube[16426:135436] -[MTLIGAccelBuffer addDebugMarker:range:]: unrecognized selector sent to instance 0x7fdfe35a14c0
[2019-11-25T13:56:16Z ERROR relevant] Values of this type can't be dropped!
[1]    16426 segmentation fault  cargo run --example cube
```

The same is happening with the skybox example. Should I open a new issue?

**Comment by kvark** [comment]
Yes, please! Sounds like we are missing an OS version check before calling `addDebugMarker`.

**Comment by edap** [comment]
Done https://github.com/gfx-rs/wgpu-rs/issues/133

**Comment by kvark** [comment]
Thanks! Closing this one then.
