### ISSUE TITLE
Re-export DeviceType

### ISSUE THREAD

**Issue by cormac-obrien** [gfx-rs/wgpu-rs#137]
This is a blocker for gfx-rs/gfx#3027. It's currently not possible to access the `AdapterInfo.device_type` field from within `gfx` library code because the compiler tries to use the local version of `DeviceType` rather than the one used by `wgpu`, causing a version conflict:

```
error[E0308]: mismatched types
   --> src\backend\wgpu\src\lib.rs:999:23
    |
999 |                 info: a.get_info(),
    |                       ^^^^^^^^^^^^ expected struct `gfx_hal::adapter::AdapterInfo`, found a different struct `gfx_hal::adapter::AdapterInfo`
    |
    = note: expected type `gfx_hal::adapter::AdapterInfo` (struct `gfx_hal::adapter::AdapterInfo`)
               found type `gfx_hal::adapter::AdapterInfo` (struct `gfx_hal::adapter::AdapterInfo`)
note: Perhaps two different versions of crate `gfx_hal` are being used?
```

It would probably also be good just for consistency reasons, since we already re-export all the other `gfx` types used in `wgpu`'s public interfaces.

**Comment by kvark** [comment]
Strictly speaking, it's not a blocker: gfx-backend-wgpu shouldn't assume that wgpu uses the same gfx-hal version internally. It could be just copying the fields from one `AdapterInfo` into the other. In fact, this is the only way to go, since wgpu-rs will depend on the crates version of gfx-hal, while `master` code is generally not the same.

**Comment by cormac-obrien** [comment]
My mistake, the error message I copied doesn't demonstrate where I think the issue is. Re: copying the fields, it's not clear to me how this would work, unless there's a gap in my knowledge of the language (which is quite possible):

```rust
let a = wgpu::Adapter::request(&options);
let info = a.get_info();
let adapter = adapter::Adapter {
    info: adapter::AdapterInfo {
        name: info.name,
        vendor: info.vendor,
        device: info.device,
        device_type: // what to do here?
    },
    physical_device: /* ... */,
    queue_families: /* ... */,
};
```

It's not possible to copy the field directly (since it's a different version, as you mentioned), and as far as I know there's no way to match on it -- wgpu doesn't re-export the type or its version of gfx-hal, so there's no path to refer to the type. Am I missing something?

**Comment by kvark** [comment]
Ok, I see. We definitely need to reexport the sevice type then!

**Comment by GabrielMajeri** [comment]
Can this be closed now that [the corresponding PR](https://github.com/gfx-rs/wgpu/pull/401) is merged?
