### ISSUE TITLE
Loading textures from PNG

### ISSUE THREAD

**Issue by dmilford** [gfx-rs/wgpu-rs#14]
Thank you so much for the WGPU samples!  I'm hoping wgpu really takes off.

For your textured cube, I see that you're creating your fractal image via code.  Do you have any examples of loading a png instead?  I tried to cobble some example code from gfx-hal and your code to load some type of image as a test (I failed miserably by the way).  The best I could do is take some bytes from a bmp and modify the image byte vector you guys created in code.

I'm obviously just poking at things with a stick.  I do have experience with OpenGL ES, but it seems things have moved a bit and I need to go through a learning curve.

Any guidance would truly be appreciated.  I'd prefer an example with png, but I'll take any example if you have it.

Again, thank you so much for your efforts!!!

**Comment by dmilford** [comment]
UPDATE: Based on Dzmitry's recommendation, I was able to use a png for the cube.  I used Cargo.toml dependency png="0.14".  **I now have the png loading as the texture, but transparent sections are white.**  In OpenGL you just enable alpha blending and tell it what type of blending.  Perhaps there's something similar for wgpu?  Any advice would be welcomed.

In case it helps others, below is the textured cube with a png as the texture as well as the code used to load the image.  It's similar to the existing code with minor tweaks.
![Capture](https://user-images.githubusercontent.com/51060011/58389461-a7bb1100-7fdf-11e9-9a43-ffd5fd382e80.PNG)

       use std::fs::File;
       ------------------
       let decoder = png::Decoder::new(
            File::open(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/examples/dougs_cube/assets/logo.png"
            ))
            .unwrap(),
        );
        let (info, mut reader) = decoder.read_info().unwrap();
        let mut buf = vec![0; info.buffer_size()];
        reader.next_frame(&mut buf).unwrap();

        let texture_extent = wgpu::Extent3d {
            width: info.width,
            height: info.height,
            depth: 1,
        };
        let texture = device.create_texture(&wgpu::TextureDescriptor {
            size: texture_extent,
            array_layer_count: 1,
            mip_level_count: 1,
            sample_count: 1,
            dimension: wgpu::TextureDimension::D2,
            format: wgpu::TextureFormat::Rgba8Unorm,
            usage: wgpu::TextureUsage::SAMPLED | wgpu::TextureUsage::TRANSFER_DST,
        });

        let texture_view = texture.create_default_view();
        let temp_buf = device
            .create_buffer_mapped(buf.len(), wgpu::BufferUsage::TRANSFER_SRC)
            .fill_from_slice(&buf);
        init_encoder.copy_buffer_to_texture(
            wgpu::BufferCopyView {
                buffer: &temp_buf,
                offset: 0,
                **row_pitch: 4 * info.width,
                image_height: info.height,**
            },
            wgpu::TextureCopyView {
                texture: &texture,
                mip_level: 0,
                array_layer: 0,
                origin: wgpu::Origin3d {
                    x: 0.0,
                    y: 0.0,
                    z: 0.0,
                },
            },
            texture_extent,
        );

**Comment by kvark** [comment]
Glad to see you got it working!
Blending mode is a part of the render pipeline state. In this section from our cube example:
```rust
            color_states: &[wgpu::ColorStateDescriptor {
                format: sc_desc.format,
                color_blend: wgpu::BlendDescriptor::REPLACE,
                alpha_blend: wgpu::BlendDescriptor::REPLACE,
                write_mask: wgpu::ColorWrite::ALL,
            }],
```
You need to change it to the following for a simple alpha blending:
```rust
color_states: &[wgpu::ColorStateDescriptor {
                format: sc_desc.format,
                color_blend: wgpu::BlendDescriptor {
                    src_factor: BlendFactor::SrcAlpha,
                    dst_factor: BlendFactor::OneMinusSrcAlpha,
                    operation: BlendOperation::Add,                 
                },
                alpha_blend: wgpu::BlendDescriptor {
                    src_factor: BlendFactor::One,
                    dst_factor: BlendFactor::One,
                    operation: BlendOperation::Add,                 
                },
                write_mask: wgpu::ColorWrite::ALL,
            }],
```

**Comment by dmilford** [comment]
Sweet!!!  Yep, working now :)  You da man!
    On Sunday, May 26, 2019, 7:04:13 PM PDT, Dzmitry Malyshau <notifications@github.com> wrote:  
 
 
Glad to see you got it working!
Blending mode is a part of the render pipeline state. In this section from our cube example:
            color_states: &[wgpu::ColorStateDescriptor {
                format: sc_desc.format,
                color_blend: wgpu::BlendDescriptor::REPLACE,
                alpha_blend: wgpu::BlendDescriptor::REPLACE,
                write_mask: wgpu::ColorWrite::ALL,
            }],
You need to change it to the following for a simple alpha blending:
color_states: &[wgpu::ColorStateDescriptor {
                format: sc_desc.format,
                color_blend: wgpu::BlendDescriptor {
                    src_factor: BlendFactor::SrcAlpha,
                    dst_factor: BlendFactor::OneMinusSrcAlpha,
                    operation: BlendOperation::Add,                 
                },
                alpha_blend: wgpu::BlendDescriptor {
                    src_factor: BlendFactor::One,
                    dst_factor: BlendFactor::One,
                    operation: BlendOperation::Add,                 
                },
                write_mask: wgpu::ColorWrite::ALL,
            }],

**Comment by kvark** [comment]
Great, closing then.
