### ISSUE TITLE
Does not compile on arm/raspberry pi 4

### ISSUE THREAD

**Issue by MarkSwanson** [gfx-rs/wgpu-rs#142]
Just a tracking issue. I've created this here to help others that attempt to compile wgpu-rs on a raspberry pi.

The real issue seems to be with raw-window-handle:
https://github.com/rust-windowing/raw-window-handle/issues/45

**Comment by MarkSwanson** [comment]
I think the issue is in wgpu. It should be using usize. Will log a bug in wgpu.

**Comment by kvark** [comment]
We can (and do) move issues between repos, no need to close and re-create.
