### ISSUE TITLE
Alternative to ZeroCopy

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu-rs#146]
Unfortunately, ZeroCopy take a really long time to build. It's a part of Fuchsia code base, and communicating with developers or filing issues seems... problematic. Perhaps, we could make a simpler version of it for ourselves, or find an existing alternative.

**Comment by Lokathor** [comment]
I suspect [bytemuck](https://docs.rs/bytemuck) should already cover you, but if there are particular changes that you want that it doesn't support they can most probably be added.
