### ISSUE TITLE
Boids example panics due to assertion failure

### ISSUE THREAD

**Issue by TheSpydog** [gfx-rs/wgpu-rs#150]
When I try to run the new boids example, it immediately panics due to an [assertion failure.](https://github.com/gfx-rs/wgpu-rs/blob/master/examples/boids/main.rs#L45) Simply removing the assert makes the program run without issue. Running on Windows 10.

Am I just misunderstanding how this example is supposed to work? I'm brand new to Rust and wgpu, so maybe I'm missing some valuable information. :)

**Comment by Veykril** [comment]
I would assume the assert fails due to you checking out the repository on windows the files have `\r\n` as the newline characters, so the first line of the shader would be `#version 450\r\n` while the assert checks for `#version 450\n`.

**Comment by TheSpydog** [comment]
Just tested and that is indeed the issue. I wonder if that section could be rewritten to something like the following:
```
let mut boids_source_str = String::from(include_str!("boids.comp"));
assert!(boids_source_str.starts_with("#version 450"));
boids_source_str.insert_str(boids_source_str.find('\n').unwrap() + 1,
     &format!("#define NUM_PARTICLES {}\n#define PARTICLES_PER_GROUP {}\n", 
     NUM_PARTICLES, PARTICLES_PER_GROUP));
```
That way it dynamically determines the position of the newline character rather than having a hardcoded value. This works on my Windows machine. Haven't tested on Mac or Linux but it seems like it would work there too. But maybe there's a rustier way to accomplish this? :)

**Comment by Veykril** [comment]
I believe that should fix the problem and continue to work on the other systems.
