### ISSUE TITLE
Is there support for device camera?

### ISSUE THREAD

**Issue by stephanemagnenat** [gfx-rs/wgpu-rs#170]
Is there current, or future, support for device cameras (not scene cameras)? I imagine that most modern devices, especially mobile ones, have a SOC with some optimised data path between the camera processing part and the GPU that can bypass the CPU, and so I would guess ideally the GPU API should expose such a path. But maybe I am wrong and this is outside the scope of the GPU API, and a GPU texture should be passed to the platform-specific camera API instead.

In any case, given the rising interest in augmented reality, it might be useful to potential users to have a note on that question.

**Comment by grovesNL** [comment]
Hi, there is no special API for this yet, but there could be in the future if there is a good use case (i.e. fast path like you mentioned). It would most likely be added as an extension to WebGPU, webgpu-headers, or specific to wgpu-native.

If you're interested in looking into this it would be useful to compare graphics APIs like Vulkan, D3D12, and Metal to understand whether device cameras are exposed there. As an example, the [gpuweb repository contains some useful investigations](https://github.com/gpuweb/gpuweb/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Ainvestigation+) that have been completed already.

**Comment by stephanemagnenat** [comment]
Do you think it is ok to collect such investigations here, or is there a better place. Currently found:
- Vulkan on Android: There is an extension, [VK_ANDROID_external_memory_android_hardware_buffer](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_ANDROID_external_memory_android_hardware_buffer) allowing Vulkan to access [Android's native hardware buffer](https://developer.android.com/ndk/reference/group/a-hardware-buffer).

**Comment by kvark** [comment]
@stephanemagnenat it would be useful for the group to have such an investigation contributed. If you are doing this, try to see what can be generalized across platforms, so that a single extension will be considered. Note: you'd then file an issue to `gpuweb` repo, where the group works.
