### ISSUE TITLE
OpenGL examples doesn't compile

### ISSUE THREAD

**Issue by SimonWoodburyForget** [gfx-rs/wgpu-rs#173]
Issues:
- the project doesn't have the `gl` feature flag anymore,
- `wgpu-rs` doesn't seem to have `Instance` anymore,

edit: I just found https://github.com/gfx-rs/wgpu/issues/450 which seems to state OpenGL support was deprecated?

**Comment by grovesNL** [comment]
Support for GL was temporarily removed because of some restrictions in GL that we haven't worked around yet (mostly handling GL contexts/surfaces/swapchain).

gfx-rs/wgpu#450 is the best tracking issue for re-enabling GL support

**Comment by zicklag** [comment]
Not everything has been fixed yet, but OpenGL support has been re-enabled on master! #606
