### ISSUE TITLE
`RenderPass.set_bind_group` causes unexpected issues when you set bind group 1 before bind group 0

### ISSUE THREAD

**Issue by maroider** [gfx-rs/wgpu-rs#178]
I was modifying some code that was based on  [sotrh/learn-wgpu](https://github.com/sotrh/learn-wgpu) when I ran into issues with code that originated from [this section](https://github.com/sotrh/learn-wgpu/blob/077f1b740e2986e6259257de00e69efb25fd5916/code/beginner/tutorial6-uniforms/src/main.rs#L510-L511) in the tutorial.
The issue was that I had swapped the lines around so I had this:
```Rust
render_pass.set_bind_group(1, &self.uniform_bind_group, &[]);
render_pass.set_bind_group(0, &self.diffuse_bind_group, &[]);
```
instead of this:
```Rust
render_pass.set_bind_group(0, &self.diffuse_bind_group, &[]);
render_pass.set_bind_group(1, &self.uniform_bind_group, &[]);
```
The end result of that was that instead of getting a textured pentagon, I got a window filled with the clear color.
[`RenderPass.set_bind_group`](https://docs.rs/wgpu/0.4.0/wgpu/struct.RenderPass.html#method.set_bind_group) does not document this behaviour (if this, for some reason, is the desired behaviour).

**Comment by kvark** [comment]
Duplicate for https://github.com/gfx-rs/wgpu/issues/494, which just got fixed.
