### ISSUE TITLE
BufferMapAsyncResult should be bound to a gfx-rs Pod like trait.

### ISSUE THREAD

**Issue by rukai** [gfx-rs/wgpu-rs#19]
gfx-rs prevented UB via limiting types to the Pod (plain old datatype) trait https://docs.rs/gfx/0.18.1/gfx/traits/trait.Pod.html
We should create a similar trait bounds for BufferMapAsyncResult.

**Comment by paulkernfeld** [comment]
This can probably already be closed, but #46 addresses this in a more rigorous way using the `zerocopy` crate.
