### ISSUE TITLE
Decoupling Vertex Buffers from Render Pipeline

### ISSUE THREAD

**Issue by erlendp** [gfx-rs/wgpu-rs#191]
Currently it seems the buffer layout is tightly coupled to a specific render pipeline (via a VertexBufferDescriptor). If my understanding is correct, this means I can only ever use the same buffer layout with any given pipeline, so I can't draw with buffers from multiple different source memory layouts.

The reason this might be useful, for example, could be to render all your assets with a debug shader that only needs positional information. Under the current setup, you would either need to copy the positional data to a new buffer, split the positional data out into its own buffer and use non-interleaved draw calls, or set up a new pipeline for each source format.

My question is, first of all, is my understanding correct? If so, what was the reason for this design choice, and is there any likelihood of this changing in future releases?

**Comment by kvark** [comment]
The reason a pipeline has vertex buffer layout defined is simply because all the low level APIs require that. The low level reason is that the driver may need to generate the shader code for fetching that data from the vertex buffers, and this code needs to be hooked up to the vertex shader.

> Under the current setup, you would either need to copy the positional data to a new buffer, split the positional data out into its own buffer and use non-interleaved draw calls, or set up a new pipeline for each source format.

You don't need to copy anything anywhere. You can just provide the layout of the vertex buffer containing the positions to the render pipeline that does debug drawing, i.e. you can tell it to expect a vertex buffer at index 0 with stride 20, and to read the position vec4 at offset 4.

**Comment by erlendp** [comment]
Yes, you're right. After digging in to Vulkan's API, I can see things are almost identical there. This was not the case in OpenGL, in which it was possible to bind different sets of vertex attributes, as desired. It seems like a slightly strange design decision to me, but I can only assume it's either done for performance on certain hardware, or because I'm the only one who would have preferred it a different way!

> You don't need to copy anything anywhere. You can just provide the layout of the vertex buffer containing the positions to the render pipeline that does debug drawing, i.e. you can tell it to expect a vertex buffer at index 0 with stride 20, and to read the position vec4 at offset 4.

That would only work if the stride and offset were the same for all your buffers. One might have a buffer with positions and texture coordinates, and another with positions and colours, but because they have a different stride, you would need two 'debug' render pipelines, correct?

In my opinion it would be much nicer if one could either define the attributes separately from the pipeline, or better, define some kind of compatibility layer between buffers and pipelines. In OpenGL I did this by using named attributes. As long as the vertex buffers contained all of the attributes with a corresponding named input in the shader, they would be considered compatible.

But anyway - love your work, and thanks for the explanation. I'll structure my code accordingly.

**Comment by kvark** [comment]
> That would only work if the stride and offset were the same for all your buffers. One might have a buffer with positions and texture coordinates, and another with positions and colours, but because they have a different stride, you would need two 'debug' render pipelines, correct?

I understand. What is a common practice is have the positional data in a separate vertex buffer all the time. That allows you to avoid killing the vertex data cache when rendering the depth pass (or shadow pass), and makes each object compatible with the same depth/shadow pipeline. It's a double win.

**Comment by sir-earl** [comment]
That makes sense. Do you know if there's any kind of performance hit to using non-interleaved buffers in shaders that use multiple attributes? I.e. Is there any compelling reason not to just keep all attributes in their own buffers?

**Comment by kvark** [comment]
There is a bit of a hit, I don't have links by hand, but in case of positions vs the rest - it's absolutely not something to worry about. Just group things in the way they are used. If positions are used independently - have them in a buffer. If normals + texture coords are used together, have them in a buffer, etc.

**Comment by siavashserver** [comment]
I would use depth/shadow pass specific meshes, since discarding unnecessary vertex attributes (texture coords, ...) allows the mesh simplification algorithms to further reduce vertex count.

**Comment by kvark** [comment]
@siavashserver you could probably get away with just a different index buffer. Having an entirely mesh for depth/shadow doesn't seem to make sense, given that it's supposed to be all the same positions, just with less repetition.

**Comment by siavashserver** [comment]
@kvark that's a great idea, thanks for sharing!
