### ISSUE TITLE
When will the next version be published?

### ISSUE THREAD

**Issue by lachlansneff** [gfx-rs/wgpu-rs#195]
I'm curious when 0.5.0 will be published to crates.io.

**Comment by kvark** [comment]
We can't publish unless at least the low hanging fruits are addressed with regards to the API changes. See https://github.com/gfx-rs/wgpu-rs/milestone/1 . I'll be adding more items to it soon. Help is appreciated! We can continue discussing here or in the Matrix chat, but I don't think the issue needs to be open given that there is a milestone.

**Comment by kvark** [comment]
See also - https://github.com/gfx-rs/wgpu-rs/issues/196
it's a lot of issues, but they are trivial and mechanical for the most part
