### ISSUE TITLE
RenderPass Usage

### ISSUE THREAD

**Issue by erlendp** [gfx-rs/wgpu-rs#198]
Given that CommandEncoder::begin_render_pass is mutably borrowing from the encoder, therefore preventing any further borrows on the encoder, is it safe to assume I should be creating a new RenderPass for each draw call? If not, how should I structure my code to avoid this?

**Comment by kvark** [comment]
You need a render pass per set of render targets. For each target, you begin a render pass and then draw all the objects that need to be drawn in it, switching pipelines, vertex buffers, bind groups, and other states on the way.

**Comment by erlendp** [comment]
That was my initial assumption, but I'm a little confused about how to implement that from a lifetime point of view (probably due to my greenness with Rust).

If RenderPass borrows the encoder, I'm forced to make my RenderPasses short lived, but I'd like to design a library that puts the render flow into the hands of the user, so the RenderPass needs to hang around for the duration of their calls. i.e.

`lib-redraw-event -> user-draw -> user-set-target  -> lib-begin-render-pass -> user-draw-with-pass -> lib-finish-encoder -> lib-submit-to-queue`

Where **lib-*** is code in my library and **user-*** is calling user code.

The problem occurs at the **lib-begin-render-pass** step, because the lifetime must either be that of my libraries context object (which it can't, because it can't borrow the encoder for that long), or the duration of the containing library function (which it also can't, because then the pass will end before the user code can do any actual drawing.

The only solutions I can think of would be to return the render pass to the user (probably wrapped in a temporary context), or to have a unique encoder for each render pass, (then we can potentially create the passes in parallel)?

Any thoughts on this?

**Comment by kvark** [comment]
I'm afraid I don't quite see what the exact problem is. Perhaps, you can provide more specific API entry points that you'd want to work?

> which it can't, because it can't borrow the encoder for that long

You could return some kind of a wrapper around `wgpu::CommandEncoder`. They that thing would return wrappers around `wgpu::RenderPass`, everything lifetimed appropriately.

If nothing works, we could have render passes that don't borrow the encoder but instead check that nothing else is happening at run-time (i.e weaker type system, more freedom for you to organize the engine).

**Comment by erlendp** [comment]
Ideally the library I'm designing would be used like this (with some similarity to ggez):

```
impl State for AppState {
    fn new(ctx: &mut Context) -> AppState {
        AppState {
            canvas_1: Canvas::new(&mut ctx, 1024, 1024),
            ...
        }
    }

    fn draw(&mut self, ctx: &mut DrawContext) {
        ctx.set_canvas(&self.canvas_1);
        ctx.draw(...);

        ctx.set_canvas(None);
        ctx.draw(...);
    }
}
```
Internally the library looks something like this (off the top of my head):

```
impl DrawContext {
    fn set_canvas(...) {
        // If canvas is set to None, the render pass will use the window_attachment
        // as a target, otherwise it will use the canvas' target.
        self.render_pass = self.encoder.begin_render_pass(...);
    }

    fn draw(...) {
        self.render_pass.set_vertex_buffers(...);
        self.render_pass.set_index_buffer(...);
        self.render_pass.draw_indexed(...);
    }
}

...

RedrawRequested => {
    let frame = swap_chain.get_next_texture().unwrap();

    user_state.draw(DrawContext {
        encoder,
        window_attachment: &frame.view,
        render_pass: ... // Set default render pass here?
    });

    queue.submit(&encoder.finish());
}

```
I _think_ the problem occurs above because **DrawContext::render_pass** has the same lifetime as the DrawContext, and as it needs to borrow the encoder for its lifetime, no other calls can be made to the encoder, including beginning more render passes.

**Comment by erlendp** [comment]
The most obvious solution that came to mind after typing out the above, is user code that looks more like this:

```
fn draw(&mut self, ctx: &mut DrawContext) {
    let mut pass_1 = ctx.begin_pass(&self.canvas_1);
    pass_1.draw(...);

    let mut pass_final = ctx.begin_pass(None);
    pass_final.draw(...);
}
```
This now more closely reflects the API of **wgpu**, whereby the user code is new responsible for managing the lifetime of each render pass.

**Comment by kvark** [comment]
Distinct encoder for each pass is slightly worse, but not a big deal, as long as you still submit them all at once.

**Comment by erlendp** [comment]
So I had a little play with distinct encoder per pass, and was not able to come up with a solution that works without again pushing the render pass lifetime in to the user code (and all examples using **wgpu-rs** I've seen are the same.

Perhaps it's just my lack of familiarity with Rust, but it feels like my options are quite limited with the current design.

**Comment by kvark** [comment]
@erlendp please clarify what you mean by "pushing the render pass lifetime in to the user code". The approach you suggested in https://github.com/gfx-rs/wgpu-rs/issues/198#issuecomment-599309493 should work.

**Comment by erlendp** [comment]
@kvark Yes, the above solution does indeed work (and is probably how I will design my library), but it seems like the only approach that works due to the lifetime constraints on the RenderPass.

The only other approach I can think of would be to record all draw calls that are made in user code, and then process them in one place, so the RenderPasses can be scoped appropriately.

Happy to be proven wrong by someone with my Rust experience!

**Comment by parasyte** [comment]
IIUC, what you describe about recording draw calls is exactly what a `CommandEncoder` does. The `RenderPass` returned from the encoder is just the interface for recording draw operations, and the recording are all submitted in a batch once they are finalized.

If you want to map your API to wgpu, that would be a good place to start. Abstracting beyond that could give you some trouble.
