### ISSUE TITLE
Enabling vsync?

### ISSUE THREAD

**Issue by expenses** [gfx-rs/wgpu-rs#209]
Hi, sorry if this is a really obvious question, but I'm struggling with finding out how to enable vsync with the vulkan backend.

**Comment by mitchmindtree** [comment]
Hi @expenses! I believe if you specify [`PresentMode::Vsync`](https://docs.rs/wgpu/0.4.0/wgpu/enum.PresentMode.html#variant.Vsync) in your `SwapChainDescriptor`, the swap chain will use a double-buffer and synchronise access to the swap chain textures with the display refresh rate. It's worth noting that this mode has been renamed to `Fifo` on master I believe and a couple of other modes have been added too. Hope this helps!

**Comment by expenses** [comment]
@mitchmindtree Ah, great, thanks!
