### ISSUE TITLE
RGB texture format?

### ISSUE THREAD

**Issue by kaimast** [gfx-rs/wgpu-rs#215]
Hello,
This might be a noobish question, but I am trying to load a RGB image without an alpha channel and do not really understand how to do it.

There seems to be no TextureFormat::Rgb8* here: https://docs.rs/wgpu/0.4.0/wgpu/enum.TextureFormat.html

Are 24 bit colors just not supported by WGPU or am I reading this enum wrong?

**Comment by kvark** [comment]
Correct, 24 bit colors are bad and not universally supported by the backends (and not in the WebGPU upstream spec).

**Comment by kaimast** [comment]
Thanks kvark! For future reference it would be great if that enum had some documentation.

**Comment by kvark** [comment]
Yeah, docs should be improved. Help is appreciated!
