### ISSUE TITLE
Object lifetimes

### ISSUE THREAD

**Issue by aloucks** [gfx-rs/wgpu-rs#217]
Are the object/handle lieftimes documented anywhere?

For example, if I create a `TextureView` from from a `Texture`, do I need to keep the texture alive? Similarly, if I create a bind group from a texture view or buffer, do I need to keep the texture view and buffer alive?

I've assumed that we need to keep the parent objects alive, but it would be convenient if we didn't always have to.

**Comment by kvark** [comment]
We should document this clearly, but so far you don't need to keep anything alive on top of the compile-enforced lifetimes. At least, not in wgpu land. You still need to hold the external dependencies alive, e.g. `winit::Window` that you created a surface from.

**Comment by aloucks** [comment]
* Surface lifetime: #224
