### ISSUE TITLE
List friendly ecosystem projects in README

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu-rs#22]
Starting with https://github.com/hecrj/wgpu_glyph

**Comment by hecrj** [comment]
Hi there! I am the author of [`wgpu_glyph`].

Not sure if it applies, but I would also like to introduce you to [`coffee`], a 2D game engine that [uses `wgpu`] as a graphics backend. We just landed a [basic GUI runtime] and [simple mesh support]! Feel free to check out the [examples].

[`wgpu_glyph`]: https://github.com/hecrj/wgpu_glyph
[`coffee`]: https://github.com/hecrj/coffee
[uses `wgpu`]: https://github.com/hecrj/coffee/tree/master/src/graphics/backend_wgpu
[basic GUI runtime]: https://github.com/hecrj/coffee/pull/35
[simple mesh support]: https://github.com/hecrj/coffee/pull/50
[examples]: https://github.com/hecrj/coffee/tree/master/examples

**Comment by kvark** [comment]
Done in #23
