### ISSUE TITLE
Move CI to Github Actions

### ISSUE THREAD

**Issue by Gordon-F** [gfx-rs/wgpu-rs#225]
How about use CI with Github Actions ?

**Comment by kvark** [comment]
What's the motivation?

**Comment by Gordon-F** [comment]
@kvark Some pros of Github Actions:
1.  Build speed up (7m vs 17-20m)
1.  Better GitHub integration (we can add clippy action, for example - https://github.com/marketplace/actions/rust-clippy-check)
1. 20 concurrent jobs (not for now, but i think it useful in future)

Cons: Bad build environment with only latest OS.

**Comment by kvark** [comment]
Thank you for the answer!
How did you measure the times?
We might want to move to GH actions if the current Travis crisis doesn't resolve soon-ish... Let's give it a month and re-evaluate at the end of April.

**Comment by Gordon-F** [comment]
@kvark 
> How did you measure the times?

I use fork with same CI process in Github Actions - https://github.com/Gordon-F/wgpu-rs/actions?query=workflow%3ACI

**Comment by kvark** [comment]
@Gordon-F let's proceed, if you are still interested.
Travis seems to be forcing us to move to Travis.com, so some kind of disruption is inevitable. We might as well try moving to GH actions.
