### ISSUE TITLE
Examples panic

### ISSUE THREAD

**Issue by factorsofx** [gfx-rs/wgpu-rs#226]
I've cloned the repository and am attempting to run the examples using `cargo run --example` but all of them have panicked. [Here is a link to the output from running one](https://pastebin.com/hfBWEbcB).

System information:
Linux Mint 19.3 - Kernel 5.3.0-40
RX 5700 XT with AMDGPU-Pro drivers installed

**Comment by Keavon** [comment]
Are you running the latest version of Rust? Try running `rustup update` and see if that fixes things. I just had the same problem (different compilation errors than yours though) and it fixed things to update Rust.

**Comment by kvark** [comment]
@factorsofx does Vulkan work for you in general? i.e. you could try running `vkcube` from vulkan-tools or any of the Ash examples.

**Comment by kvark** [comment]
I'm actually seeing the same thing now on Linux:
```
[2020-03-30T22:31:13Z ERROR gfx_backend_vulkan] 
    GENERAL [Loader Message (0)] : setupLoaderTermPhysDevs:  Failed to detect any valid GPUs in the current config
    object info: (type: INSTANCE, hndl: 94701927168880)
    
[2020-03-30T22:31:13Z ERROR gfx_backend_vulkan] 
    GENERAL [Loader Message (0)] : setupLoaderTrampPhysDevs:  Failed during dispatch call of 'vkEnumeratePhysicalDevices' to lower layers or loader to get count.
    object info: (type: INSTANCE, hndl: 94701927168880)
    
[2020-03-30T22:31:13Z ERROR gfx_backend_vulkan] 
    GENERAL [Loader Message (0)] : setupLoaderTermPhysDevs:  Failed to detect any valid GPUs in the current config
    object info: (type: INSTANCE, hndl: 94701927168880)
    
[2020-03-30T22:31:13Z ERROR gfx_backend_vulkan] 
    GENERAL [Loader Message (0)] : setupLoaderTrampPhysDevs:  Failed during dispatch call of 'vkEnumeratePhysicalDevices' to lower layers or loader to get count.
    object info: (type: INSTANCE, hndl: 94701927168880)
    
[2020-03-30T22:31:13Z ERROR gfx_backend_vulkan] Could not enumerate physical devices! Initialization of a object has failed
thread 'main' panicked at 'internal error: entered unreachable code', /home/kvark/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/3065546/wgpu-native/src/device.rs:177:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by kvark** [comment]
In my case though, it's simply a mushed up configuration after a system update. Rebooting fixes it. Did you try turning it off and then on again? :)

**Comment by factorsofx** [comment]
Ah, vulkan in general didn't work. I've fixed that and now I'm exhibiting #227 instead (examples only showing the clear color). Thanks!

**Comment by kvark** [comment]
#227 got closed though. Are you seeing this after a driver update?
I wasn't able to test on AMD Windows recently to look into that.

**Comment by iulianR** [comment]
> #227 got closed though. Are you seeing this after a driver update?
#227 is what I posted and it's not closed yet :D

**Comment by factorsofx** [comment]
As iulianR said, #227 is still open. I'm running the latest drivers for my card. This is my first time trying to use wgpu-rs, so it's not a regression after a driver update that I'm aware of.

**Comment by kvark** [comment]
Sorry @iulianR I thought I got an email about this being closed, I confused it with another one. Will prioritize taking care of it soon!

**Comment by buxx** [comment]
I think I'm affected too: https://github.com/gfx-rs/wgpu-rs/issues/324
