### ISSUE TITLE
Examples only show clear color

### ISSUE THREAD

**Issue by iulianR** [gfx-rs/wgpu-rs#227]
Hello, I cloned the repository and tried `cargo run --example hello-triangle` and `cargo run --example cube` and nothing, except the clear color, is displayed. Am I missing something? Thanks!

I am using Windows 10 1909, AMD RX590 GPU (latest drivers)

![image](https://user-images.githubusercontent.com/6775259/77968490-219ee380-72f0-11ea-8781-ff19e8116012.png)
![image](https://user-images.githubusercontent.com/6775259/77968505-2b284b80-72f0-11ea-933c-6927b1935ca8.png)

**Comment by kvark** [comment]
I'm still unable to get my hands on an AMD machine with Windows... In the meantime, here are the things you could do in order to help:
  - Check if you have Vulkan validation layers installed. If yes, the examples should be printing any validation errors.
  - Change [the backend](https://github.com/gfx-rs/wgpu-rs/blob/02f7ac9c02bf2e7313fa1b17a996b1a882a39a27/examples/framework.rs#L106) to `DX12` and see if that works.
  - Post output made with `RUST_LOG=warn` environment

**Comment by AlcyZ** [comment]
I can reproduce the same bug on my machine. Using Win10 and RX 580 with up to date drivers. Here is the log (validation layer installed):

```
C:\Users\Shindex\PhpstormProjects\wgpu_test>cargo run --example hello-triangle
   Compiling wgpu v0.4.0 (C:\Users\Shindex\PhpstormProjects\wgpu_test)
    Finished dev [unoptimized + debuginfo] target(s) in 10.14s
     Running `target\debug\examples\hello-triangle.exe`
[2020-04-01T23:40:55Z ERROR gfx_backend_vulkan]
    VALIDATION [VUID-VkDescriptorPoolCreateInfo-poolSizeCount-arraylength (0)] : vkCreateDescriptorPool: parameter pCreateInfo->poolSizeCount must be greater than 0. The Vulkan spec states: poolSizeCount must be greater than 0 (https://www.khronos.org/registry/vulk
an/specs/1.1-extensions/html/vkspec.html#VUID-VkDescriptorPoolCreateInfo-poolSizeCount-arraylength)
    object info: (type: UNKNOWN, hndl: 0)

[2020-04-01T23:40:55Z WARN  wgpu_core::device] Surface does not support present mode: MAILBOX, falling back to FIFO
```

When i change the backend to DX12, the application starts and i can see the triangle. But after a couple of seconds (2-3), the application crashed with the following stack trace (env: RUST_BACKTRACE=full)
```
C:\Users\Shindex\PhpstormProjects\wgpu_test>cargo run --example hello-triangle
   Compiling wgpu v0.4.0 (C:\Users\Shindex\PhpstormProjects\wgpu_test)
    Finished dev [unoptimized + debuginfo] target(s) in 4.55s
     Running `target\debug\examples\hello-triangle.exe`
[2020-04-01T23:47:14Z WARN  wgpu_core::instance] Missing features: VERTEX_STORES_AND_ATOMICS | FRAGMENT_STORES_AND_ATOMICS
[2020-04-01T23:47:15Z WARN  wgpu_core::instance] max_bind_groups limit is missing
[2020-04-01T23:47:15Z WARN  wgpu_core::device] Surface does not support present mode: MAILBOX, falling back to FIFO
[2020-04-01T23:47:18Z ERROR gfx_backend_dx12::pool] error on command list creation: 8007000e
thread 'main' panicked at 'assertion failed: !self.is_null()', C:\Users\Shindex\.cargo\registry\src\github.com-1ecc6299db9ec823\d3d12-0.3.0\src\com.rs:75:9
stack backtrace:
thread 'main' panicked at 'Unexpected wait status 0xFFFFFFFF', C:\Users\Shindex\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-dx12-0.5.0\src\device.rs:3291:18
stack backtrace:
error: process didn't exit successfully: `target\debug\examples\hello-triangle.exe` (exit code: 101)
```
And i just want to say that i really appreciate your work on this technology and hope that I can help with this information.

**Comment by kvark** [comment]
Finally got my hands on it. The problem here is that gfx-backend-vulkan attempts to use AMD_NEGATIVE_VIEWPORT_HEIGHT, which doesn't end up working exactly like the KHR_MAINTENANCE1. The former is just about height flip, the latter expects the Y coordinate to also be adjusted...

**Comment by kvark** [comment]
This is now fixed upstream in gfx, you can grab the fix by doing
```
cargo update -p gfx-backend-vulkan
```

**Comment by m4b** [comment]
That was fast :) yes this fixes for me too
