### ISSUE TITLE
Segfault when incorrect shader specified

### ISSUE THREAD

**Issue by chao-mu** [gfx-rs/wgpu-rs#231]
Specifying a vertex shader as a fragment shader causes wgpu-rs to later segfault.

I am on Ubuntu 19.10 using the NVIDIA drivers with the GeForce RTX 2060 Mobile.

I was able to reproduce this by modifying the hello-triangle example to specify the vertex shader file for the fragment shader which you can see here in my fork of the repo with under segfault-when-wrong-shader: https://github.com/chao-mu/wgpu-rs/tree/segfault-when-wrong-shader

[lshw -c video](https://github.com/gfx-rs/wgpu-rs/files/4411870/lshw-video.txt)
[modinfo nvidia](https://github.com/gfx-rs/wgpu-rs/files/4411871/modinfo-nvidia.txt)
[valgrind -v target/debug/examples/hello-triangle](https://github.com/gfx-rs/wgpu-rs/files/4411872/valgrind-output.txt)

**Comment by kvark** [comment]
Thank you for filing! This could be considered a part of https://github.com/gfx-rs/wgpu/issues/269

**Comment by huangjj27** [comment]
I saw #269 is fixed, is this issue fixed too?

**Comment by kvark** [comment]
The validation has landed, but it's not yet complete:
  - missing a lot of cases, likely
  - only works when the input SPIR-V module is parsed by Naga successfully, which doesn't happen a lot

So let's keep this open until we can confirm that at least this exact case works fine. Would you mind rebasing on top of master and checking?
