### ISSUE TITLE
resize on windows 10 amd dx12 not responding and crash

### ISSUE THREAD

**Issue by m4b** [gfx-rs/wgpu-rs#233]
Resizing the window when `BackendBit::DX12` for, e.g., cube example, causes application to not respond, and occasionally crash with out of memory error, or `ResizeBuffers failed with 0x887a005`, with panic in `wgpu-core/src/device/mod.rs:1980:13` "Unexpected wait status 0xFFFFFFF"

**Comment by kvark** [comment]
In DX12 backend, we are not handling `WAIT_FAILED` code properly. It's fairly trivial to do (return an error). Do you want to try making a patch?

**Comment by kvark** [comment]
I believe this is fixed by https://github.com/gfx-rs/gfx/pull/3239, which is now published as a patch. You can pick it up by `cargo update -p gfx-backend-dx12`. Please feel free to re-open if the issue persists!
