### ISSUE TITLE
Shared Uniform Buffer

### ISSUE THREAD

**Issue by erlendp** [gfx-rs/wgpu-rs#235]
I'm wondering how best to share uniform buffers between different pipelines. I understand broadly how to use descriptors and descriptor sets, etc. What I'm not clear on is the best practices around how to configure the bindings in the case where my shaders may only need a subset of some global buffer.

For example, I might have a set of global state (such as view and projection matrices, total elapsed time, window size, etc). If I store all of this in a single uniform buffer, how can I configure my bindings for shader A, which only needs, say a view and projection matrix, versus shader B, which may needs view, projection and total elapsed time. Do I set the bindings up by specifying multiple bindings to the same buffer but with a different range? Is there any overhead to doing this, and having, say, a binding for each matrix or vector? Would I be better to have a separate global buffer for each pipeline, and copy the global state into each of them?

This seems like a very common use case, so just wondering if anyone has any tips / insights, etc.

**Comment by aloucks** [comment]
You generally want to organize your bind groups by frequency of update. For example, you probably only change the view/projection matrix once per frame (or camera), but you need to change your model matrix once per mesh. You would put these two things in different bind_groups (or descriptor sets in vulkan nomenclature). You can also pack multiple things onto a single buffer and create mutliple bindings at different offsets (or use dynamic offsets).

You might find this helpful: https://developer.nvidia.com/vulkan-shader-resource-binding

**Comment by erlendp** [comment]
Yes, that was my understanding regarding update frequency. My question was more around whether it makes sense to keep all this shared state together in a single buffer, then use bindings with split it up according to each pipelines requirements. Also, is one binding per field appropriate, or should I strive to group multiple fields into a single binding?

**Comment by kvark** [comment]
You can only assume 4 bind groups to be supported, more is optional, so that is a forcing function to group your bindings tighter.

**Comment by kvark** [comment]
In the future, we should use Discussions for this.
