### ISSUE TITLE
Device limits

### ISSUE THREAD

**Issue by aloucks** [gfx-rs/wgpu-rs#239]
There should be a way to query device limits **in addition to** specifying what you prefer via `request_adapter`. 

The current limits are also missing every except for the max bind groups. I'm interested in getting the max vertex attributes and uniform/storage buffer alignment and range requirements. 

The vulkan equivalents: 

- minStorageBufferOffsetAlignment
- maxStorageBufferRange
- minUniformBufferOffsetAlignment
- maxUniformBufferRange
- maxVertexInputAttributes

**Comment by kvark** [comment]
The upstream logic is: Adapter has a set of limits (yet to be enabled in the spec), and you can request them when creating a device.

**Comment by cwfitzgerald** [comment]
This has since been implemented and is usable in the released version of wgpu :)
