### ISSUE TITLE
Copying buffer to texture causes device to be lost

### ISSUE THREAD

**Issue by ThatsNoMoon** [gfx-rs/wgpu-rs#240]
You can see my minimal example that reproduces the panic, along with the panic message, [here](https://github.com/ThatsNoMoon/wgpu-rs-problem).

I can't tell why this is substantially different from the cube example, where I cannot reproduce this problem.

I'm on Windows 10.0.18362, with a GTX 1070, GeForce driver version 445.75

**Comment by aloucks** [comment]
I don't get the device lost error, however..

Your intermediate buffer isn't large enough for an `Rgba8Unorm` image of those dimensions and your `copy_buffer_to_texture` parameters are incorrect. Do you see the validation errors?

This might help:

```diff
index c722465..0a34cf6 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -50,7 +50,7 @@ fn main() {

     log::trace!("creating intermediate buffer");
     let buf = device.create_buffer(&wgpu::BufferDescriptor {
-        size: (WIDTH * HEIGHT) as u64,
+        size: 4 * (WIDTH * HEIGHT) as u64,
         usage: wgpu::BufferUsage::COPY_SRC,
     });

@@ -59,13 +59,13 @@ fn main() {
         wgpu::BufferCopyView {
             buffer: &buf,
             offset: 0,
-            row_pitch: WIDTH,
+            row_pitch: 4 * WIDTH,
             image_height: HEIGHT,
         },
         wgpu::TextureCopyView {
             texture: &texture,
-            mip_level: 1,
-            array_layer: 1,
+            mip_level: 0,
+            array_layer: 0,
             origin: wgpu::Origin3d::ZERO,
         },
         wgpu::Extent3d {

```

**Comment by ThatsNoMoon** [comment]
No, I don't see any validation errors. I see I forgot to multiply the width by 4. Your changes to the `mip_level` and `array_layer` seem to have fixed the problem, thank you!

If I understand correctly, I specified one mip level and one array layer, and those are the indices of the first mip level and first array layer?

My problem is resolved, should this issue remain open to track wgpu not validating this correctly, or is this another problem on my end?

**Comment by aloucks** [comment]
@kvark It might be helpful to emit a log warning in debug builds if the khronos validation layer wasn't found / couldn't be loaded.

**Comment by kvark** [comment]
@ThatsNoMoon we are responsible for validating this. Created https://github.com/gfx-rs/wgpu/issues/554 to follow-up.

@aloucks I think this is a good idea! We'd need to put this into the Vulkan backend specifically.
