### ISSUE TITLE
Logs indicate memory leak when running hello-compute example.

### ISSUE THREAD

**Issue by lachlansneff** [gfx-rs/wgpu-rs#242]
When running the hello-compute example with `RUST_LOG=info`, the following is outputted twice:

```
[2020-04-06T20:50:09Z ERROR gfx_memory::allocator::general] Allocated `Chunk` was freed, but memory is still shared and never will be destroyed
```

This seems to indicate a memory leak, but I'm not sure.

**Comment by RoyJacobs** [comment]
I'm seeing this as well in my (non-compute) application. It's weird, because I didn't see this error when building with the wgpu `master` branch yesterday. It only popped up when I moved to `0.5`. Yet I don't see any major changes that could've caused this.

**Comment by tfgast** [comment]
I'm seeing a this error in the shadow example when resizing the window (on Windows 10).

**Comment by kvark** [comment]
Was also reported in https://github.com/gfx-rs/wgpu/issues/557
This is fixed as of this morning, please do `cargo update -p gfx-memory`
