### ISSUE TITLE
CommandEncoderDescriptor no longer implements Default

### ISSUE THREAD

**Issue by aloucks** [gfx-rs/wgpu-rs#243]

**Comment by grovesNL** [comment]
`Default` probably won't be useful for many descriptors in general so it might be nice to be consistent here. Maybe alternatively we could accept `&Option<CommandEncoderDescriptor>` or `Option<&CommandEncoderDescriptor>` (which would match the spec pretty closely https://gpuweb.github.io/gpuweb/#dom-gpudevice-createcommandencoder)?

**Comment by kvark** [comment]
Why don't we just implement `Default` by putting `NULL` in the label?

**Comment by grovesNL** [comment]
Sure, we could do that if we don't mind having `Default` on some descriptors but not others. e.g. we can't have `Default` on any descriptors which have required fields without obvious defaults.

`label` is already `Option<&'a str>`, so we could just default to `label: None` for `CommandEncoderDescriptor`

**Comment by kvark** [comment]
We have WebGPU upstream that we can just follow: if the upstream has `Default`, we should have it too.

**Comment by grovesNL** [comment]
Alright, sounds good to me
