### ISSUE TITLE
Docs.rs failed to build WGPU 0.5

### ISSUE THREAD

**Issue by aloucks** [gfx-rs/wgpu-rs#244]

**Comment by grovesNL** [comment]
Opened https://github.com/rust-lang/rust/issues/70874

**Comment by iulianR** [comment]
Related issue seems to be fixed. Any update?

**Comment by kvark** [comment]
I suppose we need to try releasing a patch version.

**Comment by grovesNL** [comment]
I think we can request the docs be rebuilt manually

**Comment by grovesNL** [comment]
Created https://github.com/rust-lang/docs.rs/issues/726

**Comment by grovesNL** [comment]
Fixed by rust-lang/docs.rs#726

https://docs.rs/wgpu/0.5.0/wgpu/

**Comment by iulianR** [comment]
Thanks for the quick response and fix. Glad I checked to see issue status as I've been waiting for a while and I thought the issue is more complex than that :)
