### ISSUE TITLE
VKTrace/DXR Support

### ISSUE THREAD

**Issue by r4nd0m1z3r** [gfx-rs/wgpu-rs#247]
I saw a C++ WGPU hardware raytracing(https://github.com/maierfelix/dawn-ray-tracing)
And I also saw that they specify shader type in create_shader_module(), which means I cannot simply port it to Rust because in Rust create_shader_module() only takes &[u32] array.

TL;DR Is hardware RT(VKTrace/DXR) support will be added to WGPU-rs?

**Comment by kvark** [comment]
We'd be adding something when there is an agreed API to do so. It hasn't been done yet. Felix's work in "dawn-ray-tracing" is great, but it's not an API anybody discussed yet. We'd need something that supports all of DXR/VKTrace/metal stuff . If you want to make this investigation, that would be a great step!

**Comment by kvark** [comment]
Already filed upstream
