### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by dhardy** [gfx-rs/wgpu-rs#276]
Congrats on the 0.5 release!

Is there a changelog?

**Comment by kvark** [comment]
We have changelog for the core logic - https://github.com/gfx-rs/wgpu/blob/master/CHANGELOG.md#v05-06-04-2020

It would be good to have one here as well!

**Comment by dhardy** [comment]
Ta!

I'm mostly done updating KAS, but just opened #277. I also noticed `create_buffer_with_data` makes some things easier (after starting to use the new [create_buffer_mapped](https://docs.rs/wgpu/0.5.0/wgpu/struct.Device.html#method.create_buffer_mapped) API — some migration hints in places like this would be nice for users).

**Comment by kvark** [comment]
Added in 2f839699b516595f9cdafeef9adaefe2687dabfd, really needs to be populated though
