### ISSUE TITLE
Usage of RenderPass

### ISSUE THREAD

**Issue by dhardy** [gfx-rs/wgpu-rs#277]
I see that 25584eb263830b01e84fc436fadf266597060b40 added this lifetime restriction to wgpu 0.5:

https://github.com/gfx-rs/wgpu-rs/blob/242a596e2c60c1d179b75046face2dc07d05e95d/src/lib.rs#L965

Presumably this is because [this style of usage](https://github.com/kas-gui/kas/blob/836807e30ed4173518e7c0784a2509adbe92f61b/kas-wgpu/src/draw/flat_round.rs#L157) is dangerous (the buffer is potentially destroyed before the render uses it — though I haven't noticed this issue in practice).

So, what is good practice?

To construct a new `RenderPass` per pipeline per pass? As you can see [here](https://github.com/kas-gui/kas/blob/master/kas-wgpu/src/draw/draw_pipe.rs#L96), my toolkit uses 3-4 pipelines each per clip region (typically 1-5), so that's potentially quite a few render passes. (This also means passing the frame, load_op and scissor rect into each render function.)

Or to make each pipe return a temporary buffer object which outlives the `RenderPass`? I have a partial implementation doing that and would say it's fine, but it does add complexity and requires use of [GATs](https://github.com/rust-lang/rust/issues/44265) (still highly unstable) for the custom render pipe.

**Comment by grovesNL** [comment]
Did you see #188? I think it covers some of the same questions

**Comment by dhardy** [comment]
Thanks — and sorry, I should have checked first!

It still doesn't answer my question of whether many small passes or fewer shared ones are preferable. I guess re-using an existing pass makes the most sense (optimising for min resource usage rather than speed).
