### ISSUE TITLE
lag when resizing window, black bg when maximizing

### ISSUE THREAD

**Issue by d3bgger** [gfx-rs/wgpu-rs#282]
I first noticed this when trying out iced examples, but then saw the same thing in wgpu-rs examples.
1. The window resize seems slow and lagging.
2. When maximizing the window, re-render seems slow and a black background is shown for a moment.

![maximize](https://cdn.discordapp.com/attachments/441714251359322144/703986919788249118/max.gif)

GPU: 1660 Ti
CPU: TR 2950x

**Comment by kvark** [comment]
Thank you for filing! Do you have Vulkan drivers? Would be nice to confirm if we are running on Vulkan or on D3D12 here.

**Comment by d3bgger** [comment]
Can you please tell me how to verify that in win10? I have no experience with Vulkan.

**Comment by kvark** [comment]
Once you updated the drivers, `wgpu` detected Vulkan and preferred it by default.

I believe your problem is still visible on D3D12 backend, and I can observe it too. Let's keep it open.

**Comment by Gordon-F** [comment]
Duplicate of #233 ?

**Comment by kvark** [comment]
Right, thanks!
