### ISSUE TITLE
Examples are down

### ISSUE THREAD

**Issue by inguar** [gfx-rs/wgpu-rs#283]
All WASM examples on wgpu.rs don't start. Tested on current Chrome and Firefox.

**Comment by grovesNL** [comment]
Hi! Currently the examples will only run on Firefox Nightly or Chrome Canary with the experimental WebGPU flags enabled, there are instructions for each browser at https://github.com/gpuweb/gpuweb/wiki/Implementation-Status

**Comment by rukai** [comment]
Are you using the nightly versions of those browsers with their respective webgpu settings enabled as per https://github.com/gpuweb/gpuweb/wiki/Implementation-Status ?

**Comment by inguar** [comment]
Aha. Thank you for explanation. Just tested the examples in Chrome Canary with a special flag, and they start as expected there.

**Comment by inguar** [comment]
I think it might help to link to [that page](https://github.com/gpuweb/gpuweb/wiki/Implementation-Status) from the examples, so the visitors know why nothing is happening on the screen. But all in all, the issue is closed.

**Comment by grovesNL** [comment]
That's a good idea, I've added a note to https://wgpu.rs/examples/ that links to the implementation status page (probably need to refresh your browser's cache to see the change). cc @kvark

**Comment by inguar** [comment]
Yes, the banner is showing up now. Thanks @grovesNL !
