### ISSUE TITLE
[wasm] Send Sync impl for types

### ISSUE THREAD

**Issue by gzp-crey** [gfx-rs/wgpu-rs#287]
Most wgpu structs are Send and sync by default. Unfortunately this is not true for the wasm implementation. As far as I know wasm is single threaded and the specification about shared array and threads is just a plan, but it makes really hard (if not impossible) to write source that support both the native and wasm compilation.
Specifically in my case I've tried to add the wgpu queue, textures etc to resource managers provided by `legion` or `specs`. They require these object to be Send (and Sync). I could provide an unsafe impl for my wrappers but I'm not sure if this is the correct solution. 

Any plan, suggestion on this issue ?

A related web-sys ticket:
https://github.com/rustwasm/wasm-bindgen/issues/1061
https://github.com/rustwasm/wasm-bindgen/pull/1645

EDIT: I've just found the #272 PR. So it is a work in progress.

**Comment by kvark** [comment]
Let's consider this fixed by #272 for now
