### ISSUE TITLE
Creating an unrelated buffer stops text from rendering

### ISSUE THREAD

**Issue by MichaelBaker** [gfx-rs/wgpu-rs#288]
Hello, I'm not sure if this is a problem with wgpu, wgpu_glyph, or my understanding of wgpu so I'm posting it to both projects.

I've created a minimal runnable example here: https://github.com/MichaelBaker/wgpu-glyph-example

This is the line that causes the problem. If you comment this line out, the text renders correctly: https://github.com/MichaelBaker/wgpu-glyph-example/blob/5bcd7200d1a27df7add4a68b744b41df9b1de681/src/main.rs#L70

My best guess is that creating a buffer here corrupts or invalidates wgpu_glyph's cached transform buffer because if I remove this check from the pipeline it starts rendering correctly: https://github.com/hecrj/wgpu_glyph/blob/e53659e8bc7f4f8295365366354642778587cc84/src/pipeline.rs#L353

I'm on a Macbook Pro running macOS 10.15.3 (Catalina).

Here is the wgpu_glyph issue: https://github.com/hecrj/wgpu_glyph/issues/38

**Comment by kvark** [comment]
Tested on "10.15.5 Beta (19F72f)" with "Intel Iris Graphics 550 1536 MB" GPU. It renders the same way with and without the line in question. No Metal validation errors are present.

**Comment by kvark** [comment]
What is the expected output? Please attach both screenshots from your side here.

**Comment by MichaelBaker** [comment]
Here is the window with the line included:
<img width="800" alt="Screen Shot 2020-04-30 at 4 46 35 PM" src="https://user-images.githubusercontent.com/285296/80762526-51fdbb80-8b02-11ea-84ed-3ab76f3bc352.png">

Here is the window with the line commented out:
<img width="802" alt="Screen Shot 2020-04-30 at 4 47 16 PM" src="https://user-images.githubusercontent.com/285296/80762529-52965200-8b02-11ea-826a-62d2c47f425f.png">

This is my system info. I suppose it could be that I'm on an older version of macOS, but that would be surprising.

<img width="252" alt="Screen Shot 2020-04-30 at 4 48 56 PM" src="https://user-images.githubusercontent.com/285296/80762676-99844780-8b02-11ea-94a5-e32e4ea0128c.png">

**Comment by kvark** [comment]
Looks like this got stalled, sorry about this!
We are moving to `wgpu` now, so please re-open there if still a bug!
