### ISSUE TITLE
Future returned by `Buffer::map_write` on native is !Send again

### ISSUE THREAD

**Issue by kyren** [gfx-rs/wgpu-rs#293]
Also presumably `Buffer::map_read`, but I haven't checked it.

This is in current master (49640d2497ffac1936feb1cebb0ef64a39c31dce), looks to be due to #281 maybe?

**Comment by rukai** [comment]
winit has unittests for ensuring types remain send, might be useful here https://github.com/rust-windowing/winit/blob/master/tests/send_objects.rs

**Comment by kvark** [comment]
Will be fixed by #294

**Comment by kyren** [comment]
Should now be fixed by #272!
