### ISSUE TITLE
wgpu memory leak

### ISSUE THREAD

**Issue by cart** [gfx-rs/wgpu-rs#299]
I have observed in both the "cube" example and my own personal project that wgpu programs slowly increase the amount of memory they are using over time (in what appears to be an unbounded fashion). Generally this is about 0.5 MB per second. On my machine the cube example starts at around 10 MB. I left for a bit and came back to it using **over 200 MB**.

I did some memory profiling by setting the allocator to jemalloc (from the [jemallocator crate](https://github.com/gnzlbg/jemallocator)) with the `profiling` feature enabled.

I ran the example with this command and let it run for a bit:
```
env _RJEM_MALLOC_CONF="prof_leak:true,lg_prof_sample:0,prof_final:true" JEMALLOC_SYS_GIT_DEV_BRANCH=1 cargo run --example cube
```

This dumped a *.heap file (attached), which i converted to a pdf (also attached) using the following command;

```
jeprof --show_bytes target/debug/examples/cube jeprof.2090320.0.f.heap --pdf > out.pdf
```

This seems to point to `wgpu_render_pass_set_pipeline` generating the memory (specifically a call to `RawPass.ensure_extra_size`)
![image](https://user-images.githubusercontent.com/2694663/81126746-23f8ec80-8ef1-11ea-8bd1-b840986fb33a.png)

[jeprof.2090320.0.f.heap.txt](https://github.com/gfx-rs/wgpu-rs/files/4584315/jeprof.2090320.0.f.heap.txt)
[out.pdf](https://github.com/gfx-rs/wgpu-rs/files/4584317/out.pdf)

**Comment by kvark** [comment]
Thank you for filing this!
I believe this is a regression from #281
Will fix ASAP.

**Comment by cart** [comment]
Thats good news :smile:. I have another (extremely nasty) memory leak that only surfaces in a multi-threaded context. I'm hoping fixing this issue also fixes that one.

**Comment by cart** [comment]
Repro for the multi-threaded issue here: https://github.com/cart/wgpu-rs/tree/multi-threaded-leak
It adds crossbeam_util::thread / crossbeam_channel to the cube example.

It leaks in the hundreds of MBs within seconds.

**Comment by cart** [comment]
and if it helps, here is the jemalloc prof pdf for the multithreaded example (which also has RawPass.ensure_extra_size as the hot spot)

[out.pdf](https://github.com/gfx-rs/wgpu-rs/files/4584469/out.pdf)

**Comment by kvark** [comment]
Aren't both of these the same?

**Comment by cart** [comment]
The pdfs are slightly different (note the crossbeam function calls).

Your changes fixed the original issue! They also vastly improved app shutdown time (which would sometimes hang for a second when quitting).

Sadly the multi-threaded issue remains. I can still repro it on the branch above (which i rebased onto the latest changes).

Should I open a new issue?

**Comment by kvark** [comment]
Please, yes!

**Comment by cart** [comment]
Thanks for the quick response!
