### ISSUE TITLE
Create an image gallery on wgpu.rs

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu-rs#303]
There is a lot of really good screenshots and gifs out there! Putting them all in Readme becomes too heavy. We need a dedicated section on "wgpu.rs" website instead.

**Comment by Uriopass** [comment]
I would've liked to help with this issue, but I couldn't find the repository holding the website code ?

**Comment by grovesNL** [comment]
@Uriopass the website is under the `gh-pages` branch of this repository: https://github.com/gfx-rs/wgpu-rs/tree/gh-pages

**Comment by Uriopass** [comment]
I made a first try in #312, but it's just raw HTML/CSS. 
I'm not sure what you meant by image gallery, I hope it's enough?

**Comment by kvark** [comment]
@Uriopass would be fine by me, thank you! If there are any web devs around, please feel free to provide feedback :)

**Comment by Uriopass** [comment]
I think it could be worth it to remove some screenshots that clutter the README and add a link to wgpu.rs instead.
We can also add more screenshots now :-)

**Comment by kvark** [comment]
@Uriopass yes, thank you for all the good work!
We can leave only a handful in Readme

**Comment by kvark** [comment]
Note that https://github.com/gfx-rs/wgpu-rs/wiki/Applications is growing, and there is a lot more material out there than we currently feature on the gallery. We need to catch up!

**Comment by siavashserver** [comment]
I was looking through **help wanted** tasks and came across this issue. I made a new one using [Bulma CSS framework](https://bulma.io/), [Handlebars templating system](https://handlebarsjs.com/), and [Font Awesome icons](https://fontawesome.com/).

Online Demo: [https://siavashserver.github.io/temp/wgpu-rs/](https://siavashserver.github.io/temp/wgpu-rs/)
Source Code: [https://gist.github.com/siavashserver/0fcb45b3dbd439be58b0e26caff3a4cd](https://gist.github.com/siavashserver/0fcb45b3dbd439be58b0e26caff3a4cd)

It would be nice if you could replace the wgpu-rs logo with an *SVG* one, and use higher resolution thumbnails. You can add or remove projects by modifying the `showcase_list` variable. See here:
[https://gist.github.com/siavashserver/0fcb45b3dbd439be58b0e26caff3a4cd#file-index-html-L195](https://gist.github.com/siavashserver/0fcb45b3dbd439be58b0e26caff3a4cd#file-index-html-L195)

I hope you like it :)

**Comment by kvark** [comment]
@siavashserver I love it! Would you want to make a PR against the "gh-pages" branch to replace the current website with this one?

**Comment by siavashserver** [comment]
Done, I'm glad that you like it :)
