### ISSUE TITLE
Rendering a BGR image

### ISSUE THREAD

**Issue by lovesegfault** [gfx-rs/wgpu-rs#304]
I have a cross-process channel of a type that looks like this:
```Rust
struct BgrFrame {
    height: usize,
    width: usize,
    data: Vec<u8>,
}
```
It describes an image in a packed BGR8 representation.

I wanted to write a simple program that does something like this:
```Rust
fn main() {
    let win = Window::new(); // create a window
    let chan: IpcChan<BgrFrame> = IpcChan::new(); // open the channel
    loop {
        win.render(chan.next()); // continuously render frames
    }
}
```
While `wgpu-rs` was suggested to me on IRC I couldn't find some example code that showed how to render a BGR (or RGB) image, and never having played with this class of code before I was unable to figure out on my own how to do this.

What is the correct way to render a packed BGR image, in the form of `&[u8]`, using `wgpu-rs`?

**Comment by kvark** [comment]
WebGPU texture formats [are here](https://docs.rs/wgpu/0.5.0/wgpu/enum.TextureFormat.html). There is no BGR in it, only BGRA8 and RGBA8 are the closest.

Note that any data uploads to textures have to go through buffers anyway. So there is a step where you'd create a buffer and fill out the data on the CPU, before you copy that into a texture. At this step you can insert padding for the missing alpha. Check out how [examples initialize textures](https://github.com/gfx-rs/wgpu-rs/blob/9f19533462bd7c8c043eee8b914d051da95fcd91/examples/cube/main.rs#L184).

**Comment by cwfitzgerald** [comment]
Closing as this seems to have been answered, if you have more questions yet, feel free to re-open.
