### ISSUE TITLE
Reading from buffer never finishes

### ISSUE THREAD

**Issue by br-lewis** [gfx-rs/wgpu-rs#305]
I've run into an issue where reading from a buffer never finishes but only in certain circumstances. It seems to be related to both how I'm executing the pipelines and the size of the buffer. Interestingly the behavior differs between debug and release builds.

I've put together a stripped down version to demonstrate the issue [here](https://github.com/br-lewis/wgpu-hang-test). I only noticed this behavior on Windows, Linux and Mac both worked fine for my other project, I haven't tested them with the different test cases in the example repo.

This was with the Vulkan API (aside from on Mac, of course) with an RTX 2060.

Edit: tried this on Ubuntu with Nvidia's 440.64 drivers and all the test cases worked fine.

**Comment by kvark** [comment]
This is an old issue that is likely fixed. We are moving to wgpu now, so please re-open there if still a bug!
