### ISSUE TITLE
Segfault while running hello-triangle on v0.5

### ISSUE THREAD

**Issue by Yamakaky** [gfx-rs/wgpu-rs#308]
When running the hello-triangle example, it crashes  with`exit code: 0xc0000005, STATUS_ACCESS_VIOLATION`. By println debugging, it seem to crash at `device.create_bind_group`. Same thing if I move the shader loading after this line. Is this a known problem? What can I do to debug it?

I'm on intel integrated gpu on Windows.

**Comment by kvark** [comment]
This is basically https://github.com/gfx-rs/wgpu/issues/240
It's not something you'd hit in your own app, just a bit of API that the upstream spec hasn't figured out yet, and we haven't put any workarounds in.

**Comment by Yamakaky** [comment]
Oh OK, so I need to have at least one binding for each pass?
Maybe add an assert for now with a reference to the issue?

**Comment by kvark** [comment]
You don't need at least one binding for *each pass*. You need at least one binding in a bind group. Your pipeline layouts (and pipelines) can work with zero bind groups too.
Adding an assert for now is a good step.

**Comment by kvark** [comment]
This is an old issue that is likely fixed. We are moving to wgpu now, so please re-open there if still a bug!
