### ISSUE TITLE
Describe example panics

### ISSUE THREAD

**Issue by MichaelMcDonnell** [gfx-rs/wgpu-rs#309]
The `describe` example panics when I run it:

```terminal
thread 'main' panicked at 'not implemented', src\lib.rs:976:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\examples\describe.exe` (exit code: 101)
```

It was broken by commit ba953547346ec230726c03e35ee0e6f977742f95. If I roll back to commit 309cc1ceddb72494c1880436900543d228697cdb then it works fine:

```terminal
AdapterInfo { name: "GeForce GTX 970", vendor: 4318, device: 5058, device_type: DiscreteGpu, backend: Vulkan }
```

It looks like a line in `get_info` in `lib.rs` was commented out and the function left unimplemented?

```rust
pub fn get_info(&self) -> AdapterInfo {
    //wgn::adapter_get_info(self.id)
    unimplemented!()
}
```

**Comment by kvark** [comment]
Thank you for filing!
This `adapter_get_info` API is not currently compatible with the Web, so it may as well be disabled. Alternatively, we'd have a "native" feature that enables the extra APIs for native use only, including the `describe` example.

**Comment by MichaelMcDonnell** [comment]
It looks like the [`WebGPU spec`](https://gpuweb.github.io/gpuweb/#gpuadapter) defines how to get the adapter info. Should it be changed to work like it?

**Comment by kvark** [comment]
Yeah, it looks like the Web version should be able to implement it. How do you feel about this, @grovesNL ?

**Comment by grovesNL** [comment]
Sure, we'd need to adjust `AdapterInfo` somehow though (e.g. we don't have vendor/device/device type on the web), or maybe just returning a string.

**Comment by kvark** [comment]
This is an old issue that is likely fixed. We are moving to wgpu now, so please re-open there if still a bug!
