### ISSUE TITLE
Inconsistent cubemap sampling

### ISSUE THREAD

**Issue by Limeth** [gfx-rs/wgpu-rs#310]
I ran into a weird issue which I am having trouble debugging.
I have a compute pass and a render pass, both of which sample from a cubemap texture.
The passes use different bind groups & bind group layouts.
The compute pass samples the texture correctly, whereas all samples in the render pass fragment stage seem to be 0. (I only access the first component)

I shared my issue in the Matrix room, and was pointed towards the tracing feature: https://github.com/gfx-rs/wgpu/wiki/Debbugging-wgpu-Applications#tracing-infrastructure
However, I will have to update my code to wgpu-rs master first, as this feature is supposedly not available on "0.5.0".

**Comment by kvark** [comment]
Please provide more info. Best thing you can do is porting to wgpu-rs master and taking an API trace. In the meantime, sharing the shader source, bind group layouts, any relevant code pieces, screenshots, would be helpful.

**Comment by kvark** [comment]
This is an old issue that is likely fixed. We are moving to wgpu now, so please re-open there if still a bug!
