### ISSUE TITLE
Manage variable sized texture

### ISSUE THREAD

**Issue by Yamakaky** [gfx-rs/wgpu-rs#325]
I use a texture as a depth map from a IR sensor. I use it to show a 3D mesh of the things in front of the sensor. This sensor has a constant bitrate, so you can change the resolution between 4 settings to get higher framerates. For now, I create a new texture and bindgroup each time the resolution change. Is it possible to have a texture with the maximum size and only use a subset for render? The main problem is AddressMode which would not work as expected for lower resolutions. Manually doing the clamp and setting an extra border would work but is annoying. You also have to pass the subtexture dimensions to the shader.

**Comment by kvark** [comment]
There is nothing in the works that would help your case. Does the resolution change often? Is the overhead of creating a new texture something you are concerned about?

**Comment by Yamakaky** [comment]
No, it only changes on demand so the perf impact should be negligeable. It's more about the need to create new bind groups at resolution change instead of only at startup. I use a compute shader to generate the vertices position, normal and index buffer, and I use buffers of the max possible size created once, while I have to create new textures.

**Comment by kvark** [comment]
I see. Generally, it's perfectly normal for applications to recreate some of the textures when window resizes, for example, and consequently recreate the bind groups affected. Your case seems very similar. I don't think we need any extra functionality to make it easier.

**Comment by Yamakaky** [comment]
ok, thanks
