### ISSUE TITLE
Validate compute bind groups against the specified layout

### ISSUE THREAD

**Issue by Yamakaky** [gfx-rs/wgpu-rs#326]
I have a compute pipeline with two bind groups. I messed up and mixed the two:

```rust
        let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            bind_group_layouts: &[&layout_b, &layout_a],
        });
...
            cpass.set_bind_group(0, &self.binding_a, &[]);
            cpass.set_bind_group(1, &binding_b, &[]);
```

One binding is two buffers and the other is texture + sampler. It didn't trigger any error. Swapping the bind group layouts fixed it. I didn't try with a render pipeline.

`wgpu` should validate that the bind group matches with the bind group layout. If that's too expensive, maybe only on debug?

**Comment by kvark** [comment]
This is basically https://github.com/gfx-rs/wgpu/issues/552

**Comment by Yamakaky** [comment]
Oops, didn't check, sorry
