### ISSUE TITLE
queue.write_buffer causes vulkan validation error about used commandbuffer

### ISSUE THREAD

**Issue by Wumpf** [gfx-rs/wgpu-rs#333]
I've been updating from wgpu-rs from 0.5 to master. All good until I started swapping scratch buffer creation against queue.write_buffer. Doing so in my fork of imgui-wgpu-rs spams me with vulkan validation errors:

```
VALIDATION [VUID-vkResetCommandBuffer-commandBuffer-00045 (511214570)] : Validation Error: [ VUID-vkResetCommandBuffer-commandBuffer-00045 ] Object 0: handle = 0x2300a297780, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x1e7883ea | Attempt to reset VkCommandBuffer 0x2300a297780[] which is in use. The Vulkan spec states: commandBuffer must not be in the pending state (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkResetCommandBuffer-commandBuffer-00045)
object info: (type: COMMAND_BUFFER, hndl: 2405352175488)
```
fairly simple change, didn't change anything around the encoders:
https://github.com/Wumpf/imgui-wgpu-rs/commit/05110e90b2efae4d606bfdab446f6e614e8ae16b#diff-b4aea3e418ccdb71239b96952d9cddb6R444-R447

To repro check out the linked commit and run `cargo run --example hello_world`

**Comment by kvark** [comment]
We'll fix this ASAP!

**Comment by Wumpf** [comment]
So quick! Thank you!!
