### ISSUE TITLE
Create Surface/Instance only for targeted backend

### ISSUE THREAD

**Issue by AlexCharlton** [gfx-rs/wgpu-rs#337]
When calling `Surface::create` in the 0.5 release, or `Instance::new` in master, one Instance is created per backend that's supported. On Windows this means three Instances are created: one for Vulkan, DX12, and DX11. Perhaps my Vulkan drivers are particularly bad, but out of the 711ms it takes to create those three Instances on my computer, 706ms are taken up by the Vulkan Instance. If I chose to use a non-Vulkan Adapter/Device, it seems silly to have to pay the price for all that Vulkan instantiation.

**Comment by kvark** [comment]
Thank you for filing! Looking at the [gfx-backend-vulkan](https://github.com/gfx-rs/gfx/blob/f85c8571136e89de8759c71939f6284cbb9d7dfb/src/backend/vulkan/src/lib.rs#L336-L469), it does indeed do quite some stuff on instance initialization.
How do you feel about passing the `BackendBit` value to `Instance::new`? I'm not sure if we'd need that in `request_adapter` if we have that, we could probably just remove it there for now.

**Comment by AlexCharlton** [comment]
Passing `BackendBit` value to `Instance::new` sounds perfect to me. Having an instance be "an instance of a backend" rather than "all possible instances of a backend" feels right.

**Comment by Kimundi** [comment]
This is now implemented on master.

**Comment by AlexCharlton** [comment]
Works great! Thanks 🙏
