### ISSUE TITLE
Pick a specific Adapter

### ISSUE THREAD

**Issue by giordi91** [gfx-rs/wgpu-rs#341]
I am using wgpu-rs and so far so good. Thank you for your hard work. I am facing a small issue in picking the wanted Adapter. 
I am currently running on a rig which has a 5700XT and a 2080Ti. The 5700XT is the main driver and the 2080ti is the second driver (on a lower PCIe slot). The 5700XT is the one driving the main monitor and is the one I would like to use. Mostly because I had much slower performance in the past if render happens on the card not connected to the main monitor (most likely due to the frame buffer being moved over PCIe to the card actually outputting to the monitor. 

No matter what configuration I pass to request, there is no way to not make it pick the 5700XT. Is there a way to just iterate all the available adapter and pick the one I want? (That would also allow me to chose at runtime based on config as I do in my Vulkan engine). 
If not possible at the moment, will it be possible in the future?

By looking at the Dawn implementation it seems to be possible to get a list of adapters, not sure if that is just not exposed in wgpu-rs

Apologies if this is a silly question but I am fairly new to wgpu.

Best regards.

**Comment by Yamakaky** [comment]
Did you try https://docs.rs/wgpu/0.5.0/wgpu/struct.Adapter.html#method.enumerate?

**Comment by giordi91** [comment]
Apologies, I must have looked at the wrong version of the docs. I will be testing shortly and report back. Thank you very much

**Comment by giordi91** [comment]
Works like a charm. Thank you very much.

```
Adapter: AdapterInfo { name: "GeForce RTX 2080 Ti", vendor: 4318, device: 7687, device_type: DiscreteGpu, backend: Vulkan }
Adapter: AdapterInfo { name: "AMD Radeon RX 5700 XT", vendor: 4098, device: 29471, device_type: DiscreteGpu, backend: Vulkan }
```

**Comment by kvark** [comment]
@giordi91 did you provide the compatible surface pointer to the adapter selection? If so, it's quite sad that Vulkan would report both GPU to be capable of presenting to a surface, given that only one of them is directly connected to it :/

**Comment by Yamakaky** [comment]
What about optimus/prime and rendering offloading? I can use my Intel to display to a screen connected to my Nvidia.

**Comment by kvark** [comment]
There is no interaction between GPU adapters in WebGPU today, so no offloading yet.

**Comment by Yamakaky** [comment]
So how should it work? Need to recreate all the pipeline with the new device when the program switches window ?

**Comment by giordi91** [comment]
@kvark so this is by far not my area of expertise but shouldn't the surface just be a blob of memory you can write to and the OS knows what to do with it? In my Vulkan and dx12 engine (C++) I can pick any of the GPU and will work no problem, albeit the copy overhead.

**Comment by giordi91** [comment]
Interesting in my case I was not using them in combination. Only one GPU at the time picked dynamically at runtime. and that seemed to work. I am going to test here more but so far it has been running off the second GPU happily. I don't see why should not actually work from the main GPU connected to the display.

**Comment by kvark** [comment]
This isn't about combination usage, only one GPU was picked at run-time.

You have the Vulkan spec. It says that you have to query surface presentation capability before trying to work on it with a particular physical device queue family. I understand if you decide to not follow it in your engine, but it's not something we can afford here. We have to follow the native API specs for valid usage.

**Comment by giordi91** [comment]
Sorry, here I was not trying to compare what I was doing in vk or dx12, different API different granularity.  Here I was trying to solve a problem I had at hand with my current system config. 

Indeed, having the ability to iterate the adapters does not mean the adapter would work with the surface, what would be the chances to expose a method to validate that?
Such that after I have run whatever logic I might want to run, I have an iterator that I can validate against the given surface, if the result is positive I can move forward knowing everything is in check. 
otherwise, I will have to fallback and/or abort.

**Comment by kvark** [comment]
Yes, that sounds good. We should expose a way to check the compatibility if you are querying all adapters at once, instead of picking a single one.
