### ISSUE TITLE
Data written to a uniform buffer not visible

### ISSUE THREAD

**Issue by RoyJacobs** [gfx-rs/wgpu-rs#361]
Hi, I'm rendering a very basic scene with 2 cubes whereby I have two bind groups, each containing a single matrix. The 'global' bind group 0 contains the camera matrix, the 'local' bind group 1 contains the current entity's matrix. For every entity I update the buffer containing the local matrix. This is obviously not efficient etc, but I'm just trying to experiment.

**The issue:** Updating the local uniform buffer doesn't actually seem to do anything, i.e. both cubes are rendered on top of each other. Changing the code to use two separate uniform buffers and changing which one to use in the bind group *does* render two cubes, though.

The inner loop is really straightforward, per entity:

```
let local_uniforms = Uniforms {
    transform: /* the matrix of the entity */,
};

// Update the local uniforms buffer, used in the bind_group
device
    .queue()
    .write_buffer(&self.local_uniforms_buffer, 0, local_uniforms.std140().as_raw());

let mut pass = /* create pass */
pass.set_bind_group(0, &bind_group_global, &[]);
pass.set_bind_group(1, &bind_group_local, &[]);
pass.set_pipeline(&pipeline);
// draw
```
Even recreating the full pipeline and bind groups *after* the buffer is updated (i.e. between the `write_buffer` call and the creation of the render pass) doesn't help. Am I misunderstanding how to update buffers somehow? Apologies if this is the case.

I've tried this with wgpu commits `b1f3fba` (currently master) and `45b79a21`.

For reference, the bind group is created like this:
```
let bind_group_local = device.create_bind_group(&wgpu::BindGroupDescriptor {
    layout: &bind_group_layout_local,
    bindings: &[wgpu::Binding {
        binding: 0,
        resource: wgpu::BindingResource::Buffer(self.local_uniforms_buffer.slice(..)),
    }],
    label: None,
});
```

**Comment by Yamakaky** [comment]
Did you make sure that your buffer was created with https://docs.rs/wgpu/0.5.0/wgpu/struct.BufferUsage.html#associatedconstant.VERTEX?

Could you show more code to help us debug? Like the vertex shader for example.

**Comment by RoyJacobs** [comment]
To be clear, I'm setting a matrix in a uniform buffer. This should not require `BufferUsage::VERTEX`, right?

I'm creating the buffer similarly to the `shadow` example:
```
device.create_buffer(&wgpu::BufferDescriptor {
    ...
    usage: wgpu::BufferUsage::UNIFORM | wgpu::BufferUsage::COPY_DST,
    ...
});
```

In my vertex shader I use it like this:
```
layout(set = 1, binding = 0) uniform Locals {
    mat4 objectMatrix;
};
```

So all in all pretty similar to how the shadow example works, except much more basic.

**Comment by Yamakaky** [comment]
Sorry, I meant https://docs.rs/wgpu/0.5.0/wgpu/struct.ShaderStage.html#associatedconstant.VERTEX

**Comment by RoyJacobs** [comment]
Right, I've set that up. As I said, it does work, it just doesn't update if I re-use a single uniform buffer. Having separate uniform buffers per entity (and separate bind groups referring to the buffers) works fine, though.

**Comment by cwfitzgerald** [comment]
Thanks for the bug report! 

Do you have a full runnable example of the problem, it's hard to tell what's going on without a full program.

**Comment by RoyJacobs** [comment]
I don't, since it's tied up in a fairly large program. But I can see if I can modify an existing example to repro the behaviour.

**Comment by RoyJacobs** [comment]
I've added a repro based on the 'cube' example in this commit: https://github.com/RoyJacobs/wgpu-rs/commit/9a438538fe18f78b5e618d2606411412652825b6

I'm rendering the same cube twice, but with an updated 'local' matrix. I would expect to see two cubes, this does not happen.

Additionally, on shutdown I get a panic saying `SizeEntry(768) is still used`. By the way, this is on Metal, MacOS 10.15.5.

**Comment by cwfitzgerald** [comment]
So think about the view from the perspective of the queue. It sees the first write_buffer, then the second, and only then does it run the command buffers. The command buffers will only ever see the data from the second write buffer. I would recommend either using two buffers, or using a single buffer which contains both matrices at the same time, padded to the appropriate alignment.

**Comment by RoyJacobs** [comment]
Ok, sure, that makes sense!  I was just not clear on the precise semantics, but this behaviour is then completely as expected.

Do I need to keep my fork around in order for someone to take a look at the panic on exit?

**Comment by cwfitzgerald** [comment]
Could you post the full backtrace (check to see if there are more than one stack traces and make sure you get both)?

**Comment by RoyJacobs** [comment]
Hmm, I'm getting a very limited backtrace output. Is there something else that needs to be done than setting `RUST_BACKTRACE=1`?

Occasionally I'm also getting an error from the allocator, though:
```
RUST_BACKTRACE=1 cargo run --example cube
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `target/debug/examples/cube`
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: SizeEntry(768) is still used', /Users/rjacobs/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/macros.rs:16:9
stack backtrace:
[1]    55941 segmentation fault  RUST_BACKTRACE=1 cargo run --example cube
[2020-06-12T07:33:36Z ERROR gfx_memory::allocator::linear] Not all allocation from LinearAllocator was freed
```

Please note, this also occurs with the regular unmodified `cube` example, on rev 
7b887f1 (the current `master`).

**Comment by kvark** [comment]
Given that this is unrelated to the subject, would you mind creating an issue with this stack trace? I work with macOS often and I haven't seen this.

**Comment by RoyJacobs** [comment]
Yes, certainly. I've created #368.
