### ISSUE TITLE
Creating unused buffer causes DeviceLost

### ISSUE THREAD

**Issue by rukai** [gfx-rs/wgpu-rs#362]
OS Arch Linux
GPU: nvidia GTX 960
driver: nvidia proprietary drivers 440.82-18

```rust
let data = vec!(0; 1000);
let buffer = device.create_buffer_with_data(&data, wgpu::BufferUsage::VERTEX);
```

Adding these lines to the skybox or cube example render function causes the entire machine to become unresponsive for 5 seconds before the program panics with DeviceLost.
I couldnt reproduce the problem by modifying the triangle example.
Please refer to this full log [full_log.txt](https://github.com/gfx-rs/wgpu-rs/files/4764408/full_log.txt)

The issue does not occur with smaller sized buffers, even when creating many of them.

Notice how the buffer constructors don't run till the panic.

**Comment by cwfitzgerald** [comment]
Any validation errors?

**Comment by rukai** [comment]
no validation errors.

**Comment by kvark** [comment]
That's fun! I wonder if we are internally deleting these buffers while the initial data transfer is still in progress.
