### ISSUE TITLE
Panic on running capture and hello-compute examples

### ISSUE THREAD

**Issue by imjasonmiller** [gfx-rs/wgpu-rs#364]
Hi, 

I'm wondering whether this might be something on my end. Running the mentioned examples  on b1f3fba results in a `panic` on my system. 

I'm currently running Wayland on Arch Linux 5.6.15 with `sway` as a window manager.

```shell
$ cargo run --example capture
$ cargo run --example hello-compute 1 2 3 4
```
Both result in the following `panic` message:
```shell
thread 'main' panicked at 'You cannot unmap a buffer that still has accessible mapped views', src/lib.rs:379:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'unable to remove range from map context', src/lib.rs:411:21
```

Commenting out `output_buffer.unmap()` in the [`capture example`](https://github.com/gfx-rs/wgpu-rs/blob/b1f3fbaab0ae18fb97f9126d6994605731a35311/examples/capture/main.rs#L156) allows it to not crash.

**Comment by kvark** [comment]
@lachlansneff could be related to your latest mapping changes?

**Comment by cwfitzgerald** [comment]
Adding a
```
drop(padded_buffer)
```
or not manually unmapping at `capture/main:156` solves htis issue.

**Comment by lachlansneff** [comment]
Oops, this looks related!
