### ISSUE TITLE
WrongType when sending instance vertex attribute data to the vertex shader

### ISSUE THREAD

**Issue by hasenbanck** [gfx-rs/wgpu-rs#365]
When sending Mat4 data as instance vertex attributes to the vertex shader, I have to de-compose the Mat4 colums in the ```VertexBufferDescriptor``` into it's four Vec4:

```rust
        wgpu::VertexBufferDescriptor {
            stride: 16 * 4,
            step_mode: wgpu::InputStepMode::Instance,
            // 4: mat4 MVP matrix
            attributes: &vertex_attr_array![4 => Float4, 5 => Float4, 6 => Float4, 7 => Float4],
        }
```

I normaly would assume that I could then use the Mat4 data inside the vertex shader like this (GLSL):
```glsl 
layout(location=4) in vec4 a_mvp;
```

This will currently (b1f3fba) result in the following error:
```rust
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Stage { flag: VERTEX, error: Input { location: 4, error: WrongType } }', C:\Users\Username\.cargo\git\checkouts\wgpu-rs-40ea39809c03c5d8\7b866b1\src\backend\direct.rs:460:9
```

As a workaround I can use the following shader definitions and composing the Mat4 myself:

```glsl
layout(location=4) in vec4 a_mvp_c0;
layout(location=5) in vec4 a_mvp_c1;
layout(location=6) in vec4 a_mvp_c2;
layout(location=7) in vec4 a_mvp_c3;

void main() {
    mat4 mvp = mat4(a_mvp_c0, a_mvp_c1, a_mvp_c2, a_mvp_c3);
}
```

Is this the intended behavior or might this be a bug?

Edit: Tested under Windows 10 with the Vulkan backend.
Edit2: And DX12.

**Comment by cwfitzgerald** [comment]
Unrelated: is there a wgpu party going on somewhere? I feel like there are a whole bunch of issues coming in in the last 3-4 hours.

Seems like a problem re https://github.com/gfx-rs/wgpu/pull/705

**Comment by hasenbanck** [comment]
When turning off the shader validation also provides a workaround.

**Comment by kvark** [comment]
> layout(location=4) in vec4 a_mvp;

Did you mean `layout(location=4) in mat4 a_mvp;` ?
Note that `wgpu::VertexFormat` doesn't have a matrix type, so we simply do not support what you want. The naga validation error is right here (happy to see it firing!).

**Comment by hasenbanck** [comment]
Yeah, simple copy paste error. If that's the intended design, then it's fine and I will just use SSBO to transfer the instance data.

**Comment by kvark** [comment]
FWIW, you never actually need a mat4 in case of, say, instanced rendering.
You can provide it a 3 vec4 attributes (for the columns of matrix except the last one, which is responsible for perspective transform). Or you can do vec4 position_scale with vec4 rotation_quat.

**Comment by hasenbanck** [comment]
@kvark thanks for the tip!
