### ISSUE TITLE
Scene not displaying on windows.

### ISSUE THREAD

**Issue by lachlansneff** [gfx-rs/wgpu-rs#371]
I've been developing an application using wgpu-rs on my macbook, but when I go to test it on my windows machine, the scene doesn't display.

I'm using wgpu-rs 0.5 and the adapter info is:
```
AdapterInfo { name: "GeForce RTX 2060 SUPER", vendor: 4318, device: 7942, device_type: DiscreteGpu, backend: Vulkan }
```

I've also tested with the DX12 backend and the same thing happens.

I know something is working because the FPS counter is displaying, which is being rendered by iced through wgpu, so the gpu is working here, but my scene isn't.

To duplicate, run the `billboard` branch of https://github.com/AtomCAD/atomCAD.

**Comment by lachlansneff** [comment]
I've been able to narrow this down to a even stranger issue. I can now render spheres (which is what this application is supposed to do at the moment), but it'll only show 3 of them. I never ran into this issue when running on my mac, so I'm quite confused.

I'm installing the Vulkan SDK to see if that can provide further information.

**Comment by lachlansneff** [comment]
Weirdly enough, the issue is only present when I use `create_buffer_mapped` and then write into that buffer. `create_buffer_with_data` does not seem to have issues.

**Comment by kvark** [comment]
RenderDoc shows that all the particles are condensed around the origin. Something is off with the way data is prepared/computed for the particles, not with the rendering itself.

**Comment by lachlansneff** [comment]
Okay, that makes me feel better, but still, it worked on my mac. Maybe there's still a bug with how the shader indexes into the point buffer?

**Comment by lachlansneff** [comment]
This got fixed by

1. Unmapping the buffer.
2. Actually binding the buffer with the right bounds.
