### ISSUE TITLE
Surface appears to be invalid

### ISSUE THREAD

**Issue by lachlansneff** [gfx-rs/wgpu-rs#372]
After updating to the master branch of wgpu-rs, I've found that my application crashes before any of the rendering even starts running. And by crash, I mean my entire computer freezes up for 30 seconds before the application panics with: `thread 'main' panicked at 'Surface[0] does not exist'`.

This appears to occur within `instance.request_adapter` if you pass the surface into the `compatable_shader` field, or within `device.create_swap_chain` if you don't.

I'm running Windows 10 with an RTX 2060 Super and the Vulkan backend and the latest winit.

**Comment by kvark** [comment]
Can you run the examples from `master`, as opposed to your app?

**Comment by lachlansneff** [comment]
Yes, the examples run fine. I'm making sure my setup is the same as the examples.

**Comment by kvark** [comment]
Are you dropping the surface?

**Comment by lachlansneff** [comment]
Nope, the window and the surface are stored in a struct that lives throughout the life of the program.

**Comment by lachlansneff** [comment]
Looks like it's hitting this line:

https://github.com/gfx-rs/wgpu/blob/475696af59bbf57a5c08f5bd403961ba6623df96/wgpu-core/src/hub.rs#L109

**Comment by lachlansneff** [comment]
Which then goes and hits this line:

https://github.com/gfx-rs/wgpu/blob/ad34c37127c8361bc2b07e8775816b2bbf8c0a73/wgpu-core/src/instance.rs#L378

which implies that the surface isn't being created successfully by `instance.create_surface` since it can't retrieve the first surface?

**Comment by lachlansneff** [comment]
I made a pretty idiotic mistake here. I was creating two instances by accident and using the one that was immediately dropped to create the adapter and device.
