### ISSUE TITLE
Currently Outstanding Documentation Issues

### ISSUE THREAD

**Issue by yutannihilation** [gfx-rs/wgpu-rs#378]
### `Surface::create`

This still suggests `Surface::create`, but it's removed by https://github.com/gfx-rs/wgpu-rs/commit/ba953547346ec230726c03e35ee0e6f977742f95, IIUC.

https://github.com/gfx-rs/wgpu-rs/blob/7b887f12a35c26a21f56f6540b1b771177dabd6a/src/lib.rs#L471-L472

### The descriptions about `Instance` and `Adapter`

They use the same phrases, so either of them is not the corresponding one?

https://github.com/gfx-rs/wgpu-rs/blob/092d5bb6fdf765ff4c80344a4f3de1b49a0879ec/src/lib.rs#L314-L329

**Comment by cwfitzgerald** [comment]
I'm currently working on a documentation pass of both wgpu-rs and wgpu, so I'll fix this up in that pass. Thanks for bringing it to my attention!

**Comment by yutannihilation** [comment]
Thanks!

I'm tweaking the existing code to try the dev version of wgpu (as I said at https://github.com/sotrh/learn-wgpu/issues/52#issuecomment-640959623), so I might find more tiny documentation issues like this. Which is convenient for you to file a separate issue or to add a comment here?

**Comment by cwfitzgerald** [comment]
Let's use this issue as a single tracking issue

**Comment by yutannihilation** [comment]
Sure!
