### ISSUE TITLE
master documentation

### ISSUE THREAD

**Issue by Yamakaky** [gfx-rs/wgpu-rs#379]
It would be nice to have master push it's documentation to github pages for example. It would be easier to follow the developpement.

**Comment by rukai** [comment]
cargo doc makes it super easy to generate the docs yourself:

```bash
git clone https://github.com/gfx-rs/wgpu-rs
cd wgpu-rs
cargo doc --open
```

**Comment by Yamakaky** [comment]
I know, it's just convenient to always have the latest version available. A lot of Rust projects do that.
