### ISSUE TITLE
Multiple times more GPU usage on Vulkan than DX12

### ISSUE THREAD

**Issue by OptimisticPeach** [gfx-rs/wgpu-rs#383]
I modified the water example to set the `SIZE` constant to 100, and changed the `framework` file for examples to forcibly use DX12 and Vulkan. 

When running in Vulkan, my GPU usage looks like this:

![image](https://user-images.githubusercontent.com/24464956/84926612-a43a7200-b099-11ea-8a47-dc3314a6a52b.png)

When running in DX12, my GPU usage looks like this:

![image](https://user-images.githubusercontent.com/24464956/84926756-dea40f00-b099-11ea-8d18-fe736218c10e.png)

**Comment by OptimisticPeach** [comment]
Average FPS for Vulkan is 42.
FPS for DX12 is `[37, 42]`. Average is 38.

**Comment by cwfitzgerald** [comment]
Windows gpu measurements are notoriously inaccurate/misleading, does some rivatuner based tool (afterburner, xoc, etc) also report similar numbers?

**Comment by OptimisticPeach** [comment]
Afterburner shows that the DX12 version is doing about the same amount of work.

Thanks for the heads up!
