### ISSUE TITLE
Object of type AAA is simultaneously used in thread XXX and thread YYY

### ISSUE THREAD

**Issue by Yamakaky** [gfx-rs/wgpu-rs#386]
Main parts of my code:
- smol setup: https://github.com/Yamakaky/joy/blob/async/src/main.rs#L39-L45
- cleaning loop: https://github.com/Yamakaky/joy/blob/async/src/render/mod.rs#L245-L253
- staging buffers: https://github.com/Yamakaky/joy/blob/async/src/render/mod.rs#L234-L243
- copy texture to buffer: https://github.com/Yamakaky/joy/blob/async/src/render/mod.rs#L335-L359
- buffer map and read: https://github.com/Yamakaky/joy/blob/async/src/render/mod.rs#L441-L452

The cleaning loop is there so that I can use the async stuff transparently. If I remove the sleep my app freezes at startup. Also, I'm not sure if the destructors would run correctly if my app shutdowns during a poll?

I get a bunch of validation errors:
```
[2020-06-17T20:12:19Z ERROR gfx_backend_vulkan]
    VALIDATION [UNASSIGNED-Threading-MultipleThreads (337425955)] : Validation Error: [ UNASSIGNED-Threading-MultipleThreads ] Object 0: handle = 0x7cb00000007cb, type = VK_OBJECT_TYPE_COMMAND_POOL; | MessageID = 0x141cb623 | THREADING ERROR : vkCmdBindIndexBuffer(): object of type VkCommandPool is simultaneously used in thread 0x7ff496338700 and thread 0x7ff4ae0dd0c0
    object info: (type: COMMAND_POOL, hndl: 2193525697415115)

[2020-06-17T20:12:19Z ERROR gfx_backend_vulkan]
    VALIDATION [UNASSIGNED-Threading-MultipleThreads (337425955)] : Validation Error: [ UNASSIGNED-Threading-MultipleThreads ] Object 0: handle = 0x7cb00000007cb, type = VK_OBJECT_TYPE_COMMAND_POOL; | MessageID = 0x141cb623 | THREADING ERROR : vkResetCommandBuffer(): object of type VkCommandPool is simultaneously used in thread 0x7ff4ae0dd0c0 and thread 0x7ff496338700
    object info: (type: COMMAND_POOL, hndl: 2193525697415115)
```
I'm on vulkan + linux + wgpu 0.5.

What can I do to help debug this?

**Comment by Yamakaky** [comment]
Additionally, sleeping longer increase the fps but shows more warnings. The whole thing feels like a hack, maybe it could eventually be simplified to `thread::spawn(|| device.poll_forever())` or something?

**Comment by kvark** [comment]
Thank you for filing this!
What would be most valuable to us is knowing how `master` behaves in this situation. I don't want to force you updating the app to `master`, but maybe you could try modifying an existing example according to what your code does, to reproduce it on `master`?

**Comment by Yamakaky** [comment]
There it is: https://github.com/Yamakaky/wgpu-rs/commit/03a22565ad88c7441d95d8d97e6fec6b8384d389

What does device.poll actually do? It is not needed if I use futures_timer::Delay::new instead of thread::sleep in the render loop. I assume it's because if I don't do that, the main future never awaits so smol doesn't have a chance to run the mapping.await.

**Comment by kvark** [comment]
`poll(Wait)` can be used when building on native *outside* of the async context. It doesn't make sense in your case.

**Comment by Yamakaky** [comment]
Ok, good. I ended up doing that: https://github.com/Yamakaky/joy/commit/55a47d5c4ae17451afc7267c008e59fed5033971.

**Comment by kvark** [comment]
This is an old issue that is likely fixed. We are moving to wgpu now, so please re-open there if still a bug!
