### ISSUE TITLE
Merge `capture` example into another one as a screenshot feature

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu-rs#387]
I'm trying to get us less code to maintain, while still demonstrating all the features. A screenshot feature is useful, it could be added on top of any of the framework-based examples.

**Comment by rukai** [comment]
I think it has value as is because it demonstrates headless rendering. But I understand your point about making it harder to maintain.

**Comment by kvark** [comment]
ooh, you are right, it has headless stuff, which other examples aren't bothering with...
