### ISSUE TITLE
Status of wasm support

### ISSUE THREAD

**Issue by gzp-crey** [gfx-rs/wgpu-rs#388]
I while back my pet project was working on wasm and on pc as well.
I was focusing on the pc and now I've tried to fix the wasm version. The web.rs backend contains a lot of unimplemented functions. (ex a "simple" create_buffer_with_data panic). 

What is the status of it ? Is anyone working on it or I have to put wasm away for a while again ?

Thanks.

**Comment by kvark** [comment]
It's working great, there is a section in README explaining how to use it: https://github.com/gfx-rs/wgpu-rs#run-examples-on-the-web-wasm32-unknown-unknown

There are important caveats though:
  1. Levels of browser support are different between vendors. We have the [gecko branch](https://github.com/gfx-rs/wgpu-rs/tree/gecko) that matches Firefox Nightly support.
  2. We only have WebGPU WASM backend, there is no support for WebGL WASM yet.

**Comment by gzp-crey** [comment]
I was not clear and did not mentioned I'm using main. Here as I see
`create_buffer_with_data` calls `buffer_get_mapped_range_mut` in `backend/web.rs` and it is unimplemented.
Am I missing something ?

**Comment by kvark** [comment]
Again, if you are interested in the code that can run on the Web target, you need to use the [gecko branch](https://github.com/gfx-rs/wgpu-rs/tree/gecko), which is behind `master`.
