### ISSUE TITLE
GPU hung on one of our command buffers (VK_ERROR_DEVICE_LOST)

### ISSUE THREAD

**Issue by Yamakaky** [gfx-rs/wgpu-rs#392]
While trying to write an example for https://github.com/gfx-rs/wgpu-rs/issues/386, I get the following:

```
[examples/hello-compute/main.rs:127] _mapping.as_slice()[0] = 0
[examples/hello-compute/main.rs:128] "good" = "good"
[examples/hello-compute/main.rs:127] _mapping.as_slice()[0] = 0
[examples/hello-compute/main.rs:128] "good" = "good"
INTEL-MESA: error: ../mesa-20.1.1/src/intel/vulkan/anv_device.c:3202: GPU hung on one of our command buffers (VK_ERROR_DEVICE_LOST)
```

https://github.com/Yamakaky/wgpu-rs/commit/e7ddb611d1ad299a8c69bb81c2820b8dfa93c55b

**Comment by kvark** [comment]
Thank you for digging this up!
I'm seeing this in XCode log:
> 2020-06-18 14:57:23.244806-0400 hello-compute[16184:527253] Execution of the command buffer was aborted due to an error during execution. Internal Error (IOAF code 2067)

**Comment by kvark** [comment]
@Yamakaky is this still an issue for you?

**Comment by Yamakaky** [comment]
Yes, just tested with latest master.

**Comment by kvark** [comment]
This is an old issue that is likely fixed. We are moving to wgpu now, so please re-open there if still a bug!
