### ISSUE TITLE
dpulls to manage your dependent PRs

### ISSUE THREAD

**Issue by dpulls-support** [gfx-rs/wgpu-rs#399]
Hi, Walid the founder of [dpulls](https://github.com/marketplace/dpulls) here.

We noticed that you are working with dependent PRs https://github.com/gfx-rs/wgpu-rs/pull/396 and we thought that maybe [dpulls](https://github.com/marketplace/dpulls) could be interesting for you.
[dpulls](https://github.com/marketplace/dpulls) will help working with dependent PRs by offering these features:

- A submission check to make sure your PR cannot be merged before the dependency PR gets merged first.
- It has support for cross-repository dependency, which means a PR can depend on a PR from another repository (as long as they belong to the same organisation/owner), like this one https://github.com/gfx-rs/wgpu-rs/pull/396
- Conditional merge: If your PR is ready to merge but waiting for a dependency PR to resolve, just put a comment and dpulls will merge it for you once the dependency gets resolved.
- And [more](https://www.dpulls.com/#features)

So if you are interested, give it a try and let me know what you think. The setup process doesn't take more than 1 min.
cc @kvark 

If you have questions, feel free to send me an email:
- support email: support@dpulls.com
- personal email: wberrahal@dpulls.com

Thanks and have a good day :)

**Comment by kvark** [comment]
Our CI is already set up in a way that prevents PRs like #396 to be merged before their dependencies go in.
It's not clear to me what `dpulls` can offer on top of that.

**Comment by dpulls-support** [comment]
@kvark I didn't notice you were already using something for that, is it something internal or are you using an open source tool ?

**Comment by kvark** [comment]
@dpulls-support in most cases when there is a PR here that depends on another PR, the code will just not pass the CI checks until the dependency is all in, and we switched our dependency reference accordingly. We are currently using Github CI (previously, Travis CI), and we have the https://bors.tech/ merge bot to ensure CI passes.
