### ISSUE TITLE
ensure device.poll(true); is run when destructing.

### ISSUE THREAD

**Issue by rukai** [gfx-rs/wgpu-rs#41]
As mentioned in https://github.com/gfx-rs/wgpu-rs/pull/38

I'll look into this, I'm not even sure if it still occurs but I dont have time to check right now.

**Comment by kvark** [comment]
We are definitely polling on drop: https://github.com/gfx-rs/wgpu-rs/blob/0ec9f184aa2eb56be7e16c4c4bc93433f32566c3/src/lib.rs#L795
Perhaps, it's the locking problem solved by https://github.com/gfx-rs/wgpu/pull/258 that you were observing?

**Comment by cwfitzgerald** [comment]
Is this still an issue on the latest wgpu master?

**Comment by rukai** [comment]
Yeah lets close it.
The capture example doesnt poll at the end anymore, so this is probably not even a thing you would want to do anymore.
