### ISSUE TITLE
Descriptor set isn't correctly bound

### ISSUE THREAD

**Issue by Nehliin** [gfx-rs/wgpu-rs#411]
When refactoring I stumbled upon an Issue I'm not sure is a bug but I might be wrong. When debugging with renderdoc I get the following error: `Inorrect API Use: Shader referenced a descriptor set 4 that was not bound`. The given render pass uses 5 bindgroups in total. One in the vertex shader and 4 in the fragment shader. Seeing that error I thought I had just missed calling `set_bind_group` for the given index but I don't think I have. Here is a snippet of the code that sets all the bind groups:

```rust
        let mut render_pass = command_encoder.begin_render_pass(&render_pass_descriptor);
        render_pass.set_pipeline(&self.pipeline);
        let local_iter = self.local_uniform_bind_groups.iter();
        self.shared_uniform_bind_groups
            .iter()
            .map(|shared| shared.deref())
            .chain(local_iter)
            .enumerate()
            .for_each(|(i, group)| {
                render_pass.set_bind_group(
                    // The textures are bound in the second snippet shown
                    (self.texture_types.len() + i) as u32,
                    group.get_bind_group(),
                    &[],
                );
                // This prints the index 3 and 4 are bound to the correct groups
                println!("i: {}, group: {}", self.texture_types.len() + i, group);
            });
```
The prints proved to me at least that the correct bind group is set to the correct index. But to be extra sure I added another explicit `set_bind_group` call in the draw loop as well: 

```rust
        let mut offset_map = HashMap::new();
        let query =
            <(Read<Transform>, Tagged<ModelHandle>)>::query().filter(!component::<PointLight>());
        for chunk in query.par_iter_chunks(world) {
            // This is the call that sets the bind group again as a test
            runner.set_bind_group(4, self.test.get_bind_group(), &[]);
            runner.set_texture_data(2, &self.shadow_texture);
            let model = chunk.tag::<ModelHandle>().unwrap();
            let offset = *offset_map.get(model).unwrap_or(&0);
            let transforms = chunk.components::<Transform>().unwrap();
            offset_map.insert(model.clone(), offset + transforms.len());
            let model = asset_manager.get_model(model).unwrap();
            // This call sets the 2 separate texture + sampler bind groups indexed 0 and 1
            runner.draw_model_instanced(model, offset as u32..(offset + transforms.len()) as u32);
        }
```
I still get the same error and I can see that the bind group is correctly part of the pipeline layout so that shouldn't be an issue (and should give me a different error). I have also requested the device with `max_bind_groups` set to 6 (even though I only need maximum of 5 as of now). The refactor was quite large but the biggest difference as far as I can tell is that one larger bind group containing two pairs of texture + sampler ended up being divided up to 2 separate bind groups increasing the total number from 4 to 5. The newly separated bind groups has identical layout (using the exact same resource). 

Looking at the Vulkan callstack I see that there are two separate calls to `vkCmdBindDescriptorSets` the first one binds a single bind group with `firstSet = 0` and `setCount = 1`. That binds one of the two parts that was split up as previously mentioned.  The second call binds 3 others and has `firstSet = 1` and `setCount = 3` as expected but It is missing the final bind group. 

Please let me know if you want more clarifications, Thanks

**Comment by kvark** [comment]
Thank you for such a detailed issue! Could you provide a repro case, or simply record an [API trace](https://github.com/gfx-rs/wgpu/wiki/Debugging-wgpu-Applications#tracing-infrastructure) and attach here?

**Comment by Nehliin** [comment]
Sure would you prefer a frame capture that you can inspect for your self in renderdoc or just an vulkan api trace? @kvark

**Comment by kvark** [comment]
@Nehliin please visit the link. I ideally want a wgpu API trace.

**Comment by Nehliin** [comment]
Will do, I realized I'm currently using the crates.io version of wgpu so I will see if this even is still a problem on the latest master after I've migrated.

**Comment by Nehliin** [comment]
So I have now migrated to the wgpu master branch (`18be98d4bb625c5f0e3fecdf5a06cd790bcb8025`) and I now get a new error: 
`thread 'main' panicked at 'index out of bounds: the len is 4 but the index is 4', /home/<username>/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/3b6e128/wgpu-core/src/command/bind.rs:175:15`

I have double checked the pipeline layout to make sure the length of the bindgroup layouts is in fact 5 and not 4. Two layouts are identical however. I'm not sure if I have introduced some new bug in the refactor but I don't think so. This is the pipeline in the trace.ron:
```
CreatePipelineLayout(
    id: Id(1, 1, Vulkan),
    bind_group_layouts: [
        Id(4, 1, Vulkan),
        Id(4, 1, Vulkan),
        Id(1, 1, Vulkan),
        Id(0, 1, Vulkan),
        Id(3, 1, Vulkan),
    ],
),
```
Is two identical layouts supported within the same pipeline? I can attach the rest of the trace if you think that would still be useful.

**Comment by kvark** [comment]
There is no requirement to have all binding layouts to be different. Each is completely independent in the pipeline layout, so we are totally fine if some of them are the same.

> I now get a new error

This is caused by https://github.com/gfx-rs/wgpu/blob/349c02104948fea7aee38c3e7dc197427b1f2414/wgpu-core/src/lib.rs#L57

Do you need 5 bind groups necessarily? This isn't going to be supported everywhere. 4 is the baseline value we do support.
Anyway, I made a PR to bump it to 8 - https://github.com/gfx-rs/wgpu/pull/759

**Comment by Nehliin** [comment]
Thank you for the help! I did however change the limits to 6 when requesting the device so how come I didn't get an error earlier if it was in fact not supported? Here is a link to the entire trace folder if you'd like to look at it: https://drive.google.com/drive/folders/1kA9lNln4NuiflhA0Vz-UIK6foer5wema?usp=sharing

**Comment by kvark** [comment]
@Nehliin our current check for the `max_bind_groups` is broken:
```rust
            if limits.max_bound_descriptor_sets == 0 {
                log::warn!("max_bind_groups limit is missing");
            } else {
                assert!(
                    u32::from(limits.max_bound_descriptor_sets) >= desc.limits.max_bind_groups,
                    "Adapter does not support the requested max_bind_groups"
                );
            }
```
It compares against the hardware-exposed limits, while it should be comparing against the parent adapter limits.
Want to help with a PR?

**Comment by Nehliin** [comment]
Sure I can give it a shot!

**Comment by Nehliin** [comment]
@kvark I might have misunderstood you but am I correct in that it should be as simple as changing it to [this](https://github.com/gfx-rs/wgpu/pull/761)?

**Comment by kvark** [comment]
@Nehliin right, it's very simple.
Note that we are trying to convert wgpu-core methods to return `Result` instead of panicking, so this would be one case where an error is returned.

**Comment by Nehliin** [comment]
Ah of course, I will fix that this evening then👍

**Comment by kvark** [comment]
Thank you for fixing this!
