### ISSUE TITLE
WebGL support

### ISSUE THREAD

**Issue by BrandonDyer64** [gfx-rs/wgpu-rs#418]
Having the ability to target WebGL would be very helpful in the short term while we wait for WGPU to stabilize.

This would obviously be quite a bit of work, but might be worth it if browsers don't see WGPU support for a while.

**Comment by BrandonDyer64** [comment]
Just found https://github.com/gfx-rs/wgpu/issues/115

**Comment by cwfitzgerald** [comment]
Ah, beat me to it 😄
