### ISSUE TITLE
wgpu::Operations and wgpu::LoadOp are missing some useful derives

### ISSUE THREAD

**Issue by HeroesGrave** [gfx-rs/wgpu-rs#422]
Could implement `Copy`, `Eq`, `Serialize`, `Deserialize` where `V` has the appropriate trait. (`LoadOp` already has copy but `Operations` doesn't).

`Default` is also a possibility but it depends on whether there's a consensus on what is a sensible default. I'm thinking `LoadOp<V>` would have a default of `LoadOp::Clear(V::default())` (`where V: Default`) and `Operations<V>` could just derive `Default` (clear with the default value for `V` and no store).

**Comment by kvark** [comment]
Thank you for filing! Yes, I agree more traits need to be implemented for them.
For the default, we should follow WebGPU upstream defaults, which is Clear(V::default) for clears and `store = true` for stores.
