### ISSUE TITLE
Bind group ShaderStage platform-dependent behavior

### ISSUE THREAD

**Issue by antonok-edm** [gfx-rs/wgpu-rs#438]
I recently started experimenting with running my application on MacOS, after having developed on Linux (currently using the latest wgpu-rs 32de700ef908029cc5f8ac3b0befd7439f5bd7bd). Once I got the window setup working properly, _almost_ everything worked correctly out of the box - which was amazing!

However, I did end up struggling with one set of entities not showing up for some time. It turns out I had (incorrectly) specified a bind group entry for a uniform as only `ShaderStage::FRAGMENT` when I was actually using it in both vertex and fragment shaders. This had not caused me any issues before on Linux, but changing it to `ShaderStage::VERTEX | ShaderStage::FRAGMENT` instead solved the issue on MacOS as well.

It appears that the Vulkan backend isn't correctly restricting uniform bindings by shader stage. It's unclear to me whether or not this is intended, but I suspect not as it is a form of undocumented undefined behavior.

**Comment by kvark** [comment]
Thank you for reporting! This isn't an issue with backends. it's an issue with `wgpu` not yet validating your shader needs properly. This is being actively worked on. As soon as Naga is able to load all the SPIR-V modules we have, you'll see the validation happening properly.

**Comment by kvark** [comment]
This is an old issue that is likely fixed. We are moving to wgpu now, so please re-open there if still a bug!
