### ISSUE TITLE
`Limits` values do not affect the right limits

### ISSUE THREAD

**Issue by bch29** [gfx-rs/wgpu-rs#448]
I have a compute stage that binds 6 storage buffers and no storage textures. When I set the `max_storage_buffers_per_shader_stage` limit to 6, I get a panic:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TooManyBindings(BindingTypeMaxCountError { kind: StorageTextures, stage: COMPUTE, count: 6 })', /home/brad/.cargo/git/checkouts/wgpu-rs-40ea39809c03c5d8/8e4d001/src/backend/direct.rs:564:9
```

However, it works when I instead set `max_storage_textures_per_shader_stage` to 6.

**Comment by kvark** [comment]
This was fixed in https://github.com/gfx-rs/wgpu/pull/798, we just need to update the github rev in here (will be done by any of the follow-up updates).

**Comment by cwfitzgerald** [comment]
Ack, sorry about that one :)
