### ISSUE TITLE
Panic with dynamic uniform buffer binding and no dynamic offsets

### ISSUE THREAD

**Issue by parasyte** [gfx-rs/wgpu-rs#456]
When a dynamic uniform buffer binding is present in a render pipeline without the required dynamic offset in the bind group on a `RenderPass`, a panic will occur in the command encoder:

```
[2020-07-19T21:58:00Z ERROR wgpu_core::binding_model] BindGroup has 1 dynamic bindings, but 0 dynamic offsets were provided
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Bind(MismatchedDynamicOffsetCount { actual: 0, expected: 1 })', src/backend/direct.rs:1056:87
```

https://github.com/gfx-rs/wgpu-rs/blob/8e4d0015862507027f3a6bd68056c64568d11366/src/backend/direct.rs#L1056

This is easy to reproduce by changing `dynamic: true` in the cube example _without adding any dynamic offsets in the bind group on the RenderPass_: https://github.com/gfx-rs/wgpu-rs/blob/8e4d0015862507027f3a6bd68056c64568d11366/examples/cube/main.rs#L142 https://github.com/gfx-rs/wgpu-rs/blob/8e4d0015862507027f3a6bd68056c64568d11366/examples/cube/main.rs#L344

----

Can anything be done to make this error graceful? Maybe the encoder (or queue?) can be made fallible by doing validation ahead of time. This validation is done right now when the `RenderPass` is dropped. E.g. this appears in the backtrace:

```
  16: <wgpu::RenderPass as core::ops::drop::Drop>::drop
             at src/lib.rs:1996
```

https://github.com/gfx-rs/wgpu-rs/blob/8e4d0015862507027f3a6bd68056c64568d11366/src/lib.rs#L1993-L2001

**Comment by kvark** [comment]
Generally in `wgpu-core`, we do all the validation at the end of render pass recording, since during recording nothing reaches into `wgpu` context and/or objects.
We could also duplicate some of the validation at `wgpu-rs` level if you see it being useful, i.e. `wgpu-rs`'s `BindGroup` could store the number of dynamic offsets expected, and compare it with the given one at binding.

**Comment by cwfitzgerald** [comment]
Wgpu's errors and messages just got an overhaul, so I'm going to close this. If this is still an issue on current master, feel free to re-open.
