### ISSUE TITLE
BufferUsage::COPY_SRC and COPY_DST have the same doc comment.

### ISSUE THREAD

**Issue by JMS55** [gfx-rs/wgpu-rs#461]
I think one of these should instead say `copy_texture_to_buffer`

`pub const COPY_SRC: BufferUsage`
Allow a buffer to be the source buffer for a CommandEncoder::copy_buffer_to_buffer or CommandEncoder::copy_buffer_to_texture operation.

`pub const COPY_DST: BufferUsage`
Allow a buffer to be the source buffer for a CommandEncoder::copy_buffer_to_buffer, CommandEncoder::copy_buffer_to_texture, or Queue::write_buffer operation.

**Comment by kvark** [comment]
Fixed by https://github.com/gfx-rs/wgpu/pull/829
