### ISSUE TITLE
[meta] Solving the cow-gonomics

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu-rs#478]
(short for `Cow` API ergonomics)
With #460 and #477, our API is updated to use `Cow` in places we had borrowing of `[]` and `str`. This is needed for `wgpu` mostly, to have a single struct declaration used in different parts (`wgpu-core`, `wgpu-types`, `player`). But now it affects the user-facing API, and it hurts the ergonomics: `Cow::Borrowed(&[...])` is longer than `&[...]`.

We have the following proposals to improve this:
  1. do nothing, leave `Cow` in the API
  2. #470 - wrap it in a builder pattern
  3. redefine structures in wgpu-rs with just plain slices `&[..]`.

Both (2) and (3) have the benefit of making `wgpu-types` types to not be generic any more. But they involve more code, obviously.

**Comment by zakarumych** [comment]
I'm not have much of a context. But both '&[T]' and 'Vec<T>' implement 'Into<Cow<[T]>'

**Comment by kvark** [comment]
We've been discussing the problem with `Cow` in the API on the matrix, and we realize the urgency of this change, since it affects a lot of code. Current consensus is converging around #470 with a custom trait instead of `Into<Cow<>>` bound.

Another choice to make is:
  a) totally hide `wgpu-types` structures in wgpu-rs behind the new builders
  b) just add builder methods to `wgpu-types` structs

With (a) we can make `wgpu-types` non-generic and lighter, but we'll end up with more code in total.
It seems like we are going to try (b) first, @cwfitzgerald was about to start experimenting on that.

**Comment by kvark** [comment]
Good news is, @Andful implemented the builders in `wgpu-types` 🎉 
Bad news is, we are now reconsidering if the builders are truly the way to go in `wgpu-rs`. We want to try out redefining plain structures and see what comes out of it. If anybody wants to help, let's talk on the matrix!

**Comment by kvark** [comment]
Fixed by #501
