### ISSUE TITLE
Flickering with multiple draw calls within the same render pass after compute pass on Vulkan with Intel Linux drivers

### ISSUE THREAD

**Issue by dragly** [gfx-rs/wgpu-rs#49]
Flickering occurs when performing two draw calls within the same render pass after an empty compute pass with the Vulkan backend. This is using Intel's Linux drivers - it does not happen with Nvidia drivers. 

A modified version of the cube examples with larger number of instances flickers between the following two images:

![image](https://user-images.githubusercontent.com/220658/62059924-7bf91900-b224-11e9-9874-835d9fe7965f.png)
![image](https://user-images.githubusercontent.com/220658/62059963-916e4300-b224-11e9-8788-ae1f29b2f787.png)

The larger boxes are drawn after the many small instances. Please ignore the wrong depth ordering. A depth buffer was not enabled. However, I am also seeing the same flickering in a larger application with a depth buffer enabled.

The modified example can be found here:

https://github.com/dragly/wgpu-rs/tree/dragly/comp-issue/examples/cube

The relevant changes to the cube example are in this commit:

https://github.com/dragly/wgpu-rs/commit/cc36db229b416390892457c0bd0d3bb430dbec2a

The issue also appears in RenderDoc. I am able to capture each type of frame above (with and without the large boxes). However, they appear equal when saving and re-opening the captures in RenderDoc and do not appear to have any differences in data or calls.

My guess is that there is either a bug in the Intel drivers or something wrong with the barriers. This is based on a similar issue I am seeing in a different example where two compute shaders appear to be run out of order.

**Comment by dragly** [comment]
I simplified the example bit by removing the texture and removed the additional `framework`. Removing the `cpass.set_pipeline(...)` and `cpass.dispatch()` fixed the issue and resulted in no more flickering, so I have left those in. The latest version can be found here:

https://github.com/dragly/wgpu-rs/tree/e221ad4d22b646c3bcd1bb9e9b302f14bbe54470/examples/cube

I have attached two RenderDoc captures, one for a bad frame and one for a good frame. However, when loading them in RenderDoc, they both appear good again.

I have also attached a vktrace. When running this through vkreplay, the flickering still appears.

[comp-issue.zip](https://github.com/gfx-rs/wgpu-rs/files/3450826/comp-issue.zip)

**Comment by dragly** [comment]
As discussed with @kvark on [Gitter](https://gitter.im/gfx-rs/webgpu), this is starting to look more and more like a graphics driver bug. I filed a [bug report](https://bugs.freedesktop.org/show_bug.cgi?id=111267) and it was immediately reported as a duplicate of [this bug](https://bugs.freedesktop.org/show_bug.cgi?id=109630), which reports a similar issue in vkQuake.

**Comment by kvark** [comment]
Thank you for the investigation! I think we can close this and keep the "wgpu" repo bug open (labeled as "vendor-bug" now).
