### ISSUE TITLE
Depth + Stencil attachment is discarded after RenderPass regardless of `stencil_ops::store` value

### ISSUE THREAD

**Issue by DasEtwas** [gfx-rs/wgpu-rs#499]
**Backend**: Vulkan

When using a Depth24PlusStencil8 format texture as depth + stencil attachment in a renderpass, the attachment can be observed (e.g. via RenderDoc) to be discarded after its stencil was written to, even if it is used in the next renderpass as a depth + stencil attachment.

It seems like wgpu ignores the `RenderPassDepthStencilAttachmentDescriptor::stencil_ops.store` flag and decides to discard the attachment based on solely `RenderPassDepthStencilAttachmentDescriptor::depth_ops.store`.

Note: RenderDoc marks discarded textures with a pixel pattern: https://github.com/baldurk/renderdoc/issues/284

```
DepthStencilStateDescriptor {
    depth_write_enabled: false,
    stencil_back: StencilStateFaceDescriptor {
        pass_op:       StencilOperation::Keep,
        depth_fail_op: StencilOperation::IncrementWrap,
        fail_op:       StencilOperation::Keep,
        compare:       CompareFunction::Always,
    },
    stencil_front: StencilStateFaceDescriptor {
        pass_op:       StencilOperation::Keep,
        depth_fail_op: StencilOperation::DecrementWrap,
        fail_op:       StencilOperation::Keep,
        compare:       CompareFunction::Always,
    },
    stencil_write_mask: !0,
    stencil_read_mask: !0,
    format: TextureFormat::Depth24PlusStencil8,
    // we use reversed Z buffers, thus Greater
    depth_compare:       CompareFunction::Greater,
}
```

**Comment by kvark** [comment]
Hmm strange. I'm looking at the code, and it appears to be respecting the stencil ops in both wgpu and gfx-rs:
  - https://github.com/gfx-rs/wgpu/blob/430b29d781200009ef02839e41136718ff62456a/wgpu-core/src/command/render.rs#L633
  - https://github.com/gfx-rs/gfx/blob/14b32e5aed7f79ca309880f479e96517758d70b5/src/backend/vulkan/src/device.rs#L585

Would you be able to debug your case further and see where we are losing the values?
Also, RenderDoc should be able to show you exactly what the store ops are on the render pass. I think you can click on the render pass object, and then see usage history, and it will give you the descriptor, with which the render pass was created.

**Comment by cwfitzgerald** [comment]
Can you reproduce this on the current master?

**Comment by kvark** [comment]
This is an old issue that is likely fixed. We are moving to wgpu now, so please re-open there if still a bug!
