### ISSUE TITLE
Prevent any drop() logic if inside a panic

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu-rs#50]
It's annoying to see a panic inside a panic if we are seeing drop() failing because we are in process of stack unwinding. We should check for this in drop() implementations and avoid doing anything that can fail.

**Comment by yanchith** [comment]
I'd like to take this. Will post progress reports and eventual questions in this thread.

**Comment by yanchith** [comment]
So browsing through the `Drop` impls, 3 seem they could use this:

- `impl<'a> Drop for SwapChainOutput<'a>`
- `impl<'a> Drop for ComputePass<'a>`
- `impl<'a> Drop for RenderPass<'a>`

They have in common that they act more like RAII guards with more logic than just destructors happening on drop. I personally only ever encountered the `SwapChainOutput` double panic in the wild.

@kvark do you think we should be preventing the drop logic for all three, or just `SwapChainOutput`? I also might have missed a place where this would be useful...

**Comment by kvark** [comment]
In all three, if the drop is happening inside a panic, just don't do anything.
