### ISSUE TITLE
Examples rendered upside down

### ISSUE THREAD

**Issue by mbenoukaiss** [gfx-rs/wgpu-rs#518]
**OS**: Debian 9
**GPU**:  Intel(R) HD Graphics 620, with vulkan
**Output of `vulkaninfo`**: https://pastebin.com/2P9TCaMu

I was trying to use `bevy` to render 2D  stuff but couldn't get anything to draw, I showed someone how `wgpu` examples render for me and was told the following which "fixed" the problem : 
> maybe your driver has a bug where all the normals are flipped, which is inverting the box, and also back face culling all the 2d sprites in the breakout example. What if you try rotating all the sprites 180 deg in the x axis?

Here is what the examples look like
![image](https://user-images.githubusercontent.com/34457865/90678745-63a8d180-e25f-11ea-90a4-bbd0b6265955.png)

Is it something that can be fixed in `wgpu` ?

**Comment by kvark** [comment]
Looks like your driver is so old that it doesn't have the `KHR_MAINTENANCE1` extension implemented. We require this on non-AMD devices. We also add a warning to the log for this case, but I guess it's now easy to miss, see https://github.com/gfx-rs/wgpu-rs#logging
We could make `wgpu` just don't use such adapters, but that would mean that you'd not have any `wgpu` at all...
Could you try updating the drivers?

**Comment by kvark** [comment]
This is an old issue that is likely fixed. We are moving to wgpu now, so please re-open there if still a bug!
