### ISSUE TITLE
Water example validation error when resize

### ISSUE THREAD

**Issue by happydpc** [gfx-rs/wgpu-rs#519]
Test on wgpu-rs 0.6, windows 10, GTX2070s
When resizing the water example, the Vulkan validation comes this log:

[1.956601 ERROR]()(no module):
VALIDATION [VUID-VkPresentInfoKHR-pImageIndices-01296 (-945112042)] : Validation Error: [ VUID-VkPresentInfoKHR-pImageIndices-01296 ] Object 0: handle = 0x23a9c726310, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0xc7aabc16 | Images passed to present must be in layout VK_IMAGE_LAYOUT_PRESENT_SRC_KHR or VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR but is in VK_IMAGE_LAYOUT_UNDEFINED. The Vulkan spec states: Each element of pImageIndices must be the index of a presentable image acquired from the swapchain specified by the corresponding element of the pSwapchains array, and the presented image subresource must be in the VK_IMAGE_LAYOUT_PRESENT_SRC_KHR layout at the time the 
operation is executed on a VkDevice (https://github.com/KhronosGroup/Vulkan-Docs/search?q=)VUID-VkPresentInfoKHR-pImageIndices-01296)
object info: (type: QUEUE, hndl: 2450756100880)

**Comment by kvark** [comment]
Yeah, water example does something funky on resize: it tries to skip the first resized frame, and `wgpu` doesn't like that.

**Comment by happydpc** [comment]
I also have a question about the "early_fragment_tests" here too. Because there's no depth buffer here to compare within terrain shader.

**Comment by kvark** [comment]
Where do you see `early_fragment_tests` mentioned?

**Comment by happydpc** [comment]
> Where do you see `early_fragment_tests` mentioned?

in terrain.frag

**Comment by kvark** [comment]
So you are asking something unrelated to the original issue filed here? I got confused. Please join us on "#wgpu-users:matrix.org", ideally, or file another issue.
