### ISSUE TITLE
Better init-time validation errors, add more variants to hal::pso::CreationError

### ISSUE THREAD

**Issue by yanchith** [gfx-rs/wgpu-rs#52]
First, let me thank you for this project. The API is super-nice to work with!

As I am writing this issue, I realize this might be a long shot, but would still like to know whether this is possible with the current architecture, so please bear with me. Also, maybe I should have reported this in gfx-hal instead 🤔 

I tried (by mistake) to create a `wgpu::RenderPipeline` with empty `vertex_buffers` while the vertex shader was expecting input attributes. The system panicked as expected, but it did so with a cryptic error caused by an unwrap rather deep down the stack, in `gfx_backend_metal` - 'called `Result::unwrap()` on an `Err` value: Other'.

Once enabling logging, I found this:

```
2019-07-31T06:53:08Z ERROR gfx_backend_metal::device] PSO creation failed: Vertex function has input attributes but no vertex descriptor was set.
```

The log originates from here: https://github.com/gfx-rs/gfx/blob/master/src/backend/metal/src/device.rs#L1580

Would it be possible to add more descriptive variants to `pso::CreationError` for better development experience, or is there something preventing this from happening? (I can imagine we wouldn't want to pollute the error with e.g. backend specific variants).

On a similar note: knowing almost nothing about the project, I would expect `wgpu` to validate and catch this before it reaches `gfx-hal` or one of the backends. Is there something in the architecture preventing the validation, or is it just not implemented yet? If the latter is the case, I would be for some implementation work 🙂 

Versions:

wgpu-rs: `5dd361fc639e71af328504f9e27a08daf83d7633` (a quite recent master)
wgpu-native: `0.2.6`
gfx-hal: `0.2.1`
gfx-backend-metal: `0.2.3`

The stacktrace:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Other', src/libcore/result.rs:999:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:308
   7: <T as core::any::Any>::type_id
             at src/libcore/panicking.rs:85
   8: gfx_backend_metal::device::MemoryTypes::bits
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/macros.rs:18
   9: gfx_backend_metal::device::MemoryTypes::bits
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/result.rs:800
  10: wgpu_native::device::wgpu_queue_submit::{{closure}}
             at /Users/monad/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/32399cf/wgpu-native/src/device.rs:1686
  11: wgpu_native::device::device_create_render_pipeline::{{closure}}
             at /Users/monad/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/32399cf/wgpu-native/src/device.rs:1728
  12: wgpu::Device::create_pipeline_layout::{{closure}}
             at /Users/monad/.cargo/git/checkouts/wgpu-rs-40ea39809c03c5d8/5dd361f/src/lib.rs:686
  13: hurban_selector::viewport_renderer::ViewportRenderer::new
             at src/viewport_renderer.rs:106
  14: hurban_selector::main
             at src/main.rs:45
  15: std::rt::lang_start::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  16: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  17: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:85
  18: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:394
             at src/libstd/rt.rs:48
  19: std::rt::lang_start
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  20: hurban_selector::create_swap_chain
```

**Comment by Napokue** [comment]
Hi @yanchith,

At first thanks fot the issue! That is indeed unfortunate when you experience an error, but are not easily able to see what it is. I have encountered this too, but the debugger often shows more information. That is how I do it for now, but it definitely would be a good addition.

I am not sure if this is a gfx or wgpu issue, do you know this @kvark?

**Comment by kvark** [comment]
Great issue, thank you for filing this @yanchith !

The validation and error handling story of wgpu-rs is at the early stages.
  - Right now: we have a few essential validation pieces related to bind groups and vertex indices. We aren't doing any validation based on the shader introspection yet, which is a very large gap that happens to include the case you hit (vertex shader expecting a buffer that is not provided by the pipeline).
  - Milestone 1: validate everything at least with some sort of a panic on error. Make it so if an app doesn't panic in our code, then it is a valid app from both gfx-hal and the driver/hardware point of view. Shader introspection *could* be done with [Spirv-Cross](https://github.com/KhronosGroup/SPIRV-Cross) (which is currently used by gfx-hal), but I'd really like to just start doing it with [rspirv](https://github.com/gfx-rs/rspirv) as it's structured representation is being worked on.
  - Milestone 2: handle errors in the way [designed by WebGPU](https://github.com/gpuweb/gpuweb/blob/master/design/ErrorHandling.md) specification. That means *no panics*!

There is a number of issues open related to Milestone 1 that you could help with (if interested). I created the [validation](https://github.com/gfx-rs/wgpu/issues?q=is%3Aissue+is%3Aopen+label%3Avalidation) label to discover them quickly.

Let us know if that doesn't address all of your concerns :)

**Comment by yanchith** [comment]
Thanks for the explanations, they make perfect sense! Also thanks for adding the validation label. I'll try to contribute as time permits in the coming days/weeks.
