### ISSUE TITLE
An issue of reading a buffer

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [gfx-rs/wgpu-rs#520]
Using the exact same code when running the shader:

```glsl
#version 450

layout(binding = 0) buffer Input
{
   float inputs[];
};

layout(binding = 1) buffer Output
{
   float outputs[];
};

void main() {
    outputs[gl_GlobalInvocationID.x] = inputs[gl_GlobalInvocationID.x]; 
}
```

It works as expected, but when running the shader:

```glsl
#version 450

layout(binding = 0) buffer Input
{
   float inputs[];
};

layout(binding = 1) buffer Output
{
   float outputs[];
};

void main() {
    outputs[gl_GlobalInvocationID.x] = 3; 
}
```

It does not.

Minimal reproducible example: [test-project.zip](https://github.com/gfx-rs/wgpu-rs/files/5104472/test-project.zip)

Output when running the test project:

```
Copying:[1, 2, 3, 4, 5]
Setting:[1077936128, 1077936128, 1077936128, 1077936128, 1077936128]
```

What am I getting wrong here?

**Comment by cwfitzgerald** [comment]
Thanks for filing this report!

When you are converting data from bytes <-> numbers, you are converting to u32, not f32. Your shader thinks it is handling floats. In the first passthrough shader, it is just copying the bit pattern from one to the other, it doesn't matter what it interprets them as. When you ask the shader to set a value, it knows it needs to set the bit pattern for the float `3.0`. When this bit pattern is reinterpreted as a u32, the value is `1077936128`. If you change the code to accumulate to a `Vec<f32>` using `f32::from_ne_bytes()` everything works as expected.

**Comment by JonathanWoollett-Light** [comment]
Well... another dumb mistake to add to my collection. Thnaks for the help.
