### ISSUE TITLE
How should I pass f32 push constants?

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [gfx-rs/wgpu-rs#524]
Since all push constants are required to be passed as `u32`s I've encountered some issues passing `f32`s.

As examples here are 2 shaders, the 1st works (gets the correct floating point result), the 2nd does not.
```
#version 450

layout(local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0) buffer Buffer0 {
    float x[];
};
layout(binding = 1) buffer Buffer1 {
    float y[];
};
layout(push_constant) uniform PushConsts {
    uint a;
};

void main() {
    uint indx = gl_GlobalInvocationID.x;
    y[indx] += x[indx] * a;
}
```
```
#version 450

layout(local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0) buffer Buffer {
    float x[];
};
layout(push_constant) uniform PushConsts {
    uint a;
};

void main() {
    uint indx = gl_GlobalInvocationID.x;
    x[indx] *= a;
}
```
I have tried variations of `x[indx] *= a;`, replacing it with `x[indx] *= float(a);`, `x[indx] = x[indx]*a;` and a couple more and non seem to work.
Defining `uint a;` instead as `float a;` does not work either.

Test project (run `cargo test`): [gpu_blas.zip](https://github.com/gfx-rs/wgpu-rs/files/5110784/gpu_blas.zip)

**Comment by kvark** [comment]
You could do something like this:
```rust
struct PushConstants {
  a: [f32; 2],
  b: [u32; 2],
}
```
And then `slice::from_raw_parts(&my_struct as *const _ as *const u32, size_of::<PushConstants>() / 4)`

**Comment by cwfitzgerald** [comment]
Closing as it seems like this issue is solved, if any more questions come up, feel free to re-open.

**Comment by Acidic9** [comment]
How do you access the push constants from the shader? I get an error:
```
Failed to parse WGSL code: expected global item, found 'layout'
```

**Comment by kvark** [comment]
Try following https://github.com/gfx-rs/naga/blob/db455af04ba888e197d5831497f84830914248dd/tests/in/texture-array.wgsl#L6

**Comment by Acidic9** [comment]
Thanks for the help @kvark !
Unfortunately my program crashes with:
```
ERROR gfx_backend_metal::command] Command buffer not released properly!
Memory block wasn't deallocated
```

**Comment by kvark** [comment]
do you have `VALIDATION` flag enabled?
if so, please file an issue, and attach an [API trace](https://github.com/gfx-rs/wgpu/wiki/Debugging-wgpu-Applications#tracing-infrastructure) please (just drop the ZIP to the issue body).
