### ISSUE TITLE
`STATUS_ACCESS_VIOLATION` when running the hello example

### ISSUE THREAD

**Issue by huangjj27** [gfx-rs/wgpu-rs#525]
## Output
```
PS > $env:RUST_LOG="trace"     
PS > cargo run --example hello
    Finished dev [unoptimized + debuginfo] target(s) in 0.55s
     Running `target\debug\examples\hello.exe`
[0.058891 WARN](Global::new)(no module): Unable to find layer: VK_LAYER_KHRONOS_validation
error: process didn't exit successfully: `target\debug\examples\hello.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

## Environment
`wgpu-rs` commit hash: 854b3f1c5d79a27d59c3eb3d8b2ff70080dbad1b
rustc version: rustc 1.45.2 (d3fb005a3 2020-07-31)
cargo version: cargo 1.45.1 (f242df6ed 2020-07-22)
OS: Windows 10 Pro 1909 (DirectX 12 installed)
Processer: AMD A10-5750M with Radeon(tm) HD graphics
Graphics: AMD Radeon HD 8650G + AMD Radeon HD 8790M (Microsoft detected dirvers, date to 2019/8/16, driver version: 26.20.12028.2) (Not update to AMD drivers for the super slow download.)

NOTE that my graphics don’t support newer drivers which support vulkan.

**Comment by huangjj27** [comment]
Closes as is mentioned in https://github.com/bevyengine/bevy/issues/140#issuecomment-683379069

**Comment by cwfitzgerald** [comment]
Would you be able to test on current master to see if the issue still occurs for you?

**Comment by huangjj27** [comment]
> Would you be able to test on current master to see if the issue still occurs for you?

Sorry for the late replying. My old laptop, which caused this issue, has been broken for a long time and I can't find a trusted engineer to fix it, so I have no environment to reproduce this issue.

**Comment by cwfitzgerald** [comment]
No worries, I'm going to close the issue for now, but if you can reproduce it, feel free to re-open the issue or file a new one! Best of luck getting it fixed.
