### ISSUE TITLE
How to setup textures in bind groups?

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [gfx-rs/wgpu-rs#528]
In attempting to use a texture I have ecnountered issues setting up the bindgroup, specifically issues with defining `gpu::BindingResource::TextureView` (since `BindGroupEntry` requires `BindingResource` which requires `TextureView`).

My view is simply the entire texture without any alteration. As such my definition looks like this:

```rust
texture.create_view(&wgpu::TextureViewDescriptor {
    label:None,
    format:None,
    dimension:None,
    aspect: wgpu::TextureAspect::All,
    base_mip_level: 0,
    level_count:None,
    base_array_layer: 0,
    array_layer_count: None
})
```

Since I don't plan on reusing this view, I first tried:

```rust
wgpu::BindGroupEntry {
    binding: binding as u32,
    resource: wgpu::BindingResource::TextureView(
        &texture.create_view(&wgpu::TextureViewDescriptor {
            label:None,
            format:None,
            dimension:None,
            aspect: wgpu::TextureAspect::All,
            base_mip_level: 0,
            level_count:None,
            base_array_layer: 0,
            array_layer_count: None
        })
    )
}
```
(`binding` is a value from a iteration and thus is a `usize`, this is why it is then casted to `u32`).

This unfortunately didn't work just due to the rules Rust. So although it would be annoying having to pointlessly hold onto values I would never resuse I pulled the definition of `TextureView`s outside and held them in a `vec`:

```rust
let views:Vec<wgpu::TextureView> = textures.iter().map(|t|
    t.create_view(&wgpu::TextureViewDescriptor {
        label:None,
        format:None,
        dimension:None,
        aspect: wgpu::TextureAspect::All,
        base_mip_level: 0,
        level_count:None,
        base_array_layer: 0,
        array_layer_count: None
    })
).collect();
```

Then simply passed references from this (e.g. `get_texture_BindGroupEntry(0,&texture,&views[0])`):

```rust
fn get_texture_BindGroupEntry(binding:usize,texture:&wgpu::Texture,view:&wgpu::TextureView) -> wgpu::BindGroupEntry {
    wgpu::BindGroupEntry {
        binding: binding as u32,
        resource: wgpu::BindingResource::TextureView(view)
    }
}
```

But now I get the error:

```
explicit lifetime required in the type of `view`
lifetime `'static` required rustc(E0621)
```

Which leaves me at a loss. It seems to me unreasonable for `TextureView`s to occupy static lifetimes, since this inherently means `Texture`s must be static. But I do not know.

How should I setup textures in bind groups?

test project (in `tests.rs` see functions `get_texture_BindGroupEntry` and `get_compute_bind_group`, lines 595->600 and 520->601 respectively): [gpu_blas.zip](https://github.com/gfx-rs/wgpu-rs/files/5113701/gpu_blas.zip)

**Comment by JonathanWoollett-Light** [comment]
So trying to stick a simpler implementation I tried a bunch of different ways with less functions and iteration and more manually set values, every one resulted in:

```
process didn't exit successfully: `C:\Users\jonat\Projects\gpu_blas\target\debug\deps\tests-ba0876ace194f64c.exe` (exit code: 0xc0000374, STATUS_HEAP_CORRUPTION)
```

With this version, the bind group is created without any iteration or any of my own functions: [gpu_blas.zip](https://github.com/gfx-rs/wgpu-rs/files/5115288/gpu_blas.zip)

In this case it is not apparent to me what is wrong, even comparing to some of the examples.

**Comment by kvark** [comment]
Thank you for the test case!
The issue you hit is bad, but also - fairly trivial, and unrelated to your original problem.
Your `mip_level_count` is `0`, which is invalid, but we are missing a check for this.
In general, if you don't know what you are doing, you can take an example, and then tweak your way into something you need.
In the meantime, we'll work on getting the validation more comprehensive.

**Comment by JonathanWoollett-Light** [comment]
That's fixed it! Thank you.

(Admittedly now I'm getting the error:
```
'bytes per row does not respect `COPY_BYTES_PER_ROW_ALIGNMENT`'
```
 when running `copy_texture_to_buffer`, but that's a seperate issue for me to look into.)
