### ISSUE TITLE
Question about `copy_texture_to_buffer` and specifically `COPY_BYTES_PER_ROW_ALIGNMENT`

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [gfx-rs/wgpu-rs#530]
In using `copy_texture_to_buffer` it requires that the `bytes_per_row` be a multiple of `COPY_BYTES_PER_ROW_ALIGNMENT`. Am I right to assume this means there will be inevitable unused space in the destionation buffer of this operation?

In my case I have a r32 10 by 10 texture. Thus ideally the buffer would only need to be 10\*10\*4 in size, but due to the restriction of `bytes_per_row` it has to be 10*256, changing the buffers size from 400 bytes to 2560 bytes (admittedly at larger sizes the change becomes less impactful).

Doing this works and I can read the result fairly nicely with:

```
let rows_bytes:Vec<Vec<u8>> = data.chunks_exact(256).map(|r| r[0..40].to_vec()).collect();
println!("[{},{}]",rows_bytes.len(),rows_bytes[0].len()); // [10,40]
let rows_vals:Vec<Vec<f32>> = rows_bytes.iter().map(|r| r.chunks_exact(4).map(|v| f32::from_ne_bytes(v.try_into().unwrap())).collect()).collect();
println!("[{},{}]",rows_vals.len(),rows_vals[0].len()); // [10,10]
```

While the wasted memory is not that significant (and becomes less significant at larger scales) I still thought it something worth asking about, is there a better way to do this?

Test project: [gpu_blas.zip](https://github.com/gfx-rs/wgpu-rs/files/5116239/gpu_blas.zip) (run: `cargo test`)

(PS: Apologies for my barrage of issues/question here recently)

**Comment by kvark** [comment]
> Am I right to assume this means there will be inevitable unused space in the destionation buffer of this operation?

That's right. This restriction comes from the hardware as well as D3D12.

> (PS: Apologies for my barrage of issues/question here recently)

Please do continue asking them and filing issues! Also, please consider joining `#wgpu-users:matrix.org` for more immediate help.

**Comment by cwfitzgerald** [comment]
Closing as resolved, feel free to re-open if it isn't.
