### ISSUE TITLE
Question about validating bind group layouts with "empty" BindGroupLayout

### ISSUE THREAD

**Issue by gzp-crey** [gfx-rs/wgpu-rs#533]
When a pipeline is created it was easier to create "empty" bind_group_layout in the bind_group_layouts, that contains no BindGroupLayoutEntry.  Before validation missing/skipping the call for the `RenderPass::set_bind_group` for the "empty" bind-groups my solution was working. Now with validation enabled it is rejected: `'current render pipeline has a layout which is incompatible with a currently set bind group, first differing at entry index 2'`

My question is that is it the expected behavior, or the validation is too aggressive?

Thanks.

**Comment by kvark** [comment]
If you are creating an empty bind group layout, why not create an empty bind group that matches it?

**Comment by gzp-crey** [comment]
I could but most bind-group are cached and only the uniform buffers are updated as needed. I felt as bind-group creation is an expensive operation, thus I've tried to minimize them and perform as few as I possible. I can create a "static" empty group and reuse them as well for each such case if that is the preferred way.
Could you please confirm that caching the bind-group is a good practice ? If constructing them (from existing buffer) is considered a lightweight operation I'll refactor my source and drop the caching part and simplify the source.

**Comment by kvark** [comment]
I don't understand the concern. If you are already caching the bind groups, than having an empty one is hardly to cost you anything.

> Could you please confirm that caching the bind-group is a good practice ?

I guess it depends on how often do you create the bind groups. If you create them one or more times per frame, then definitely do cache them.

**Comment by gzp-crey** [comment]
Thanks, I'm caching the empty groups as well and all is working fine again.
