### ISSUE TITLE
instancing?

### ISSUE THREAD

**Issue by sam0x17** [gfx-rs/wgpu-rs#54]
Is it possible to do instancing with wgpu-rs?

**Comment by grovesNL** [comment]
Yes, in [`draw` and `draw_indexed`](https://github.com/gfx-rs/wgpu-rs/blob/3b336ef75ba9e0266a8584faabc6752f4aa0f49d/src/lib.rs#L1179) accept an argument to specify  the range of instances (start and end) to use for drawing.

Vertex buffer descriptors can [specify a step mode](https://github.com/gfx-rs/wgpu-rs/blob/3b336ef75ba9e0266a8584faabc6752f4aa0f49d/src/lib.rs#L298) (`InputStepMode`) to indicate whether they're per-vertex or per-instance.

**Comment by sam0x17** [comment]
thanks!
