### ISSUE TITLE
Can't change uniform buffer data during render pass due to borrow checker

### ISSUE THREAD

**Issue by john01dav** [gfx-rs/wgpu-rs#542]
I'm currently working in wgpu in order to reap the efficiency benefits over OpenGl. A common pattern in my code is to draw many meshes with separate buffers, separate uniform data, but the same shaders. It looks something like this (in C++):
```cpp
glUseProgram(m_myProgram();
for(Mesh &mesh : m_meshes){
    glBindVertexArray(mesh.vaoId());
    glUniformMatrix4fv(m_transformationMatrixId, camera.getMatrix(mesh.getLocation());
    glDrawElements(GL_TRIANGLES, mesh.indexCount(), GL_UINT, nullptr);    
}
```
(there may be some subtle and irrelevant error — I haven't used OpenGl in awhile)

Yet, when I try to replicate the same pattern in Rust with wgpu, I run into issues.
```rust
            let view_projection = self.camera.build_view_projection_matrix();

            let mut render_pass = encoder.begin_render_pass(&RenderPassDescriptor {
                color_attachments: &[RenderPassColorAttachmentDescriptor {
                    attachment: &frame.view,
                    resolve_target: None,
                    load_op: LoadOp::Clear,
                    store_op: StoreOp::Store,
                    clear_color: Color {
                        r: 0.1,
                        g: 0.2,
                        b: 0.3,
                        a: 1.0,
                    },
                }],
                depth_stencil_attachment: None,
            });

            render_pass.set_pipeline(&self.render_pipeline);
            render_pass.set_bind_group(0, &self.uniform_buffer_bind_group, &[]);
            for mesh in &self.mesh{
                mesh.render(&mut encoder, &mut render_pass, &view_projection, &self.uniform_buffer, &self.device); //ERROR! Can't borrow `encoder` mutably becuase `render_pass` is itself a mutable borrow, which already exists
            }
```

The render function looks like this:
```rust
        //build matrix
        let model_matrix = Matrix4::from_translation(self.location);
        let final_matrix = view_projection*model_matrix;

        //send matrix to gpu
        let uniforms = Uniforms::new_from_matrix(final_matrix);
        let buffer = device.create_buffer_with_data(
            bytemuck::cast_slice(&[uniforms]),
            BufferUsage::COPY_SRC
        );
        command_encoder.copy_buffer_to_buffer(&buffer, 0, &uniform_buffer, 0, std::mem::size_of_val(&uniforms) as BufferAddress); //A mutable borrow to the command encoder is needed here in order to update uniforms

        //setup buffers
        render_pass.set_vertex_buffer(0, &self.vertex_buffer, 0, 0);
        render_pass.set_index_buffer(&self.index_buffer, 0, 0);

        //render
        render_pass.draw(0..self.index_count, 0..1);
```

Clearly, the mutable borrow is needed to update uniforms. I strongly prefer, for efficiency, to not start a new render pass for every mesh. So, I ask, how can I update uniform data in wgpu during a render pass, to render many meshes with the same settings (aside from the uniforms)? Is this a missing feature? Is there a better way to accomplish this?

**Comment by cwfitzgerald** [comment]
You should add a second pass in the beginning which uploads all the mesh data at once to reach uniform buffer. Once that's done, you can iterate over the meshes and use each buffer.

This is a much more efficient pattern for using the modern apis, and allows a more optimal barrier set.

**Comment by john01dav** [comment]
How much should I be duplicating for each mesh? Do I need separate bind groups, etc. or just a separate uniform buffer?

**Comment by kvark** [comment]
OpenGL is often too much abstracted away from the HW. In this case, uniforms act as push constants, which `wgpu` supports as an extension, but not on the Web.
All the regular data on GPU (i.e. uniform buffers) that is used in a render pass can *not* be updated in this render pass. I.e. you have to have everything ready by the time you submit the pass. If you are drawing objects with different uniform data, make sure to have all that data somewhere. You can use it then by binding separate bind groups, or the same bind group with different value of the dynamic offset.

**Comment by john01dav** [comment]
> OpenGL is often too much abstracted away from the HW. In this case, uniforms act as push constants, which `wgpu` supports as an extension, but not on the Web.
> All the regular data on GPU (i.e. uniform buffers) that is used in a render pass can _not_ be updated in this render pass. I.e. you have to have everything ready by the time you submit the pass. If you are drawing objects with different uniform data, make sure to have all that data somewhere. You can use it then by binding separate bind groups, or the same bind group with different value of the dynamic offset.

Thanks for the information! It seems like you know a lot about what's going on behind the high-level-ish APIs (basically anything but Vulkan or DX12, including wgpu and opengl). I've been wanting to learn more about this for awhile, in order to more effectively use said high-level-ish APIs. Learning Vulkan proved to not be a good way to do this (hence why I'm using wgpu now, instead of Vulkan). Can you recommend some resources to learn more in this direction from? Something like an hour or so talk on Youtube that goes over CPU architecture from a perspective of someone with a decent understanding of how CPU circuits are designed (I read a book on this, and now I think that if I was given enough time and resources, I could design any part of a very, very slow CPU), and how the APIs in software are related, would be great.

**Comment by kvark** [comment]
I wish https://gpuweb.github.io/gpuweb/#programming-model would be describing this clearly. It certainly does try.

**Comment by john01dav** [comment]
Thanks for all the help! I now have this part of my code working :)

**Comment by john01dav** [comment]
@cwfitzgerald I tried doing it that way, updating a buffer for each mesh every frame, and performance is abysmal (worse than OpenGl on Nvidia drivers — I can't test on an AMD card since I don't have one) with more than ~64 draw calls (each with its own uniform data). After our discussion on Discord, I tried to implement it in a variety of other ways, but to no avail, as there are small details that prevent me from getting working code with those methods. Can you point me towards a working example that renders many independent meshes with wgpu?

**Comment by kvark** [comment]
https://github.com/gfx-rs/wgpu-rs/tree/master/examples/shadow ?

**Comment by john01dav** [comment]
@kvark That's what I need, thanks!
