### ISSUE TITLE
nouveau support?

### ISSUE THREAD

**Issue by donpdonp** [gfx-rs/wgpu-rs#546]
im doing a hello-world with bevy and this is what I get when running it:

```
thread 'main' panicked at 'Unable to find a GPU! Make sure you have installed required drivers!'
```

from lspci:
```
	Subsystem: eVga.com. Corp. GK104 [GeForce GTX 660 Ti] [3842:3660]
	Kernel driver in use: nouveau
	Kernel modules: nvidiafb, nouveau
```

the backtrace shows the error from bevy_wgpu/src/wgpu_renderer.rs

```rust
request_adapter(&wgpu::RequestAdapterOptions {
  power_preference: wgpu::PowerPreference::HighPerformance,
  compatible_surface: None,
})
.await
.expect("Unable to find a GPU! Make sure you have installed required drivers!");
```

is using the nouveau drive supported?

**Comment by Abendstolz** [comment]
Does `nouveau` support Vulkan?

Can you check with

`ls /usr/share/vulkan/icd.d/`

?

The last info I had (albeit from 2019) was that `nouveau` doesn't support `Vulkan` but the devs were working on it - `wgpu` currently has no OpenGL backend, so `Vulkan` is a must on Linux.

**Comment by donpdonp** [comment]
after googling around it does appear that nouveau is opengl only. it'd be helpful if the error said "Make sure you have  installed required *vulkan* drivers!" and for the wgpu-rs README to say something about vulkan being a requirement. When I read "It's designed to be suitable for general purpose graphics and computation needs of Rust community." I would think that would run on nearly any graphics card/driver. 

not sure what this shows, but here is the ls output you asked for. thanks for the help!
```
$ ls /usr/share/vulkan/icd.d/
intel_icd.i686.json  intel_icd.x86_64.json  radeon_icd.i686.json  radeon_icd.x86_64.json
```

**Comment by Systemcluster** [comment]
A platform support matrix is shown in the https://github.com/gfx-rs/wgpu repo. You can track the OpenGL backend progress in https://github.com/gfx-rs/wgpu/issues/450, @zicklag has made some great advances there recently.
