### ISSUE TITLE
Mipmap example does not downsample correctly

### ISSUE THREAD

**Issue by LaylConway** [gfx-rs/wgpu-rs#55]
This bug is for the current git version.

The mipmap example currently downsamples using Nearest rather than Linear.
Changing the enum on `mag_filter` to `Linear` instead fixes it and correctly averages pixels:
https://github.com/gfx-rs/wgpu-rs/blob/master/examples/mipmap/main.rs#L137

I was under the impression that `mag_filter` refers to the filtering method used when upsampling, not when downsampling. Is this a bug in my understanding, or a bug in the code?

**Comment by kvark** [comment]
This looks fairly linear sampled to me: https://github.com/gfx-rs/wgpu-rs/pull/23#issuecomment-502123406
What backend are you using? Could you provide the screenshots?

Briefly reading [the Wiki](https://en.wikipedia.org/wiki/Texture_filtering) it appears to me that we are correctly setting the minification filter here. It could be a problem with a particular backend though if this setting is not respected properly.

**Comment by LaylConway** [comment]
This is on the Vulkan backend.

To show the issue better, this is with `mag_filter: wgpu::FilterMode::Nearest`

![mipmap_2019-08-05_23-52-16](https://user-images.githubusercontent.com/3094382/62497421-3e742d00-b7dc-11e9-8402-dba8040d99c7.png)

And with `mag_filter: wgpu::FilterMode::Linear`

![mipmap_2019-08-05_23-52-59](https://user-images.githubusercontent.com/3094382/62497429-43d17780-b7dc-11e9-8106-fdc131557c0b.png)

You can see the artifacts in the first image. Inspect the levels with RenderDoc also shows that it's not being correctly sampled.

**Comment by LaylConway** [comment]
Additionally, in my own rendering engine it's made the difference between

![qrenderdoc_2019-08-05_21-03-53](https://user-images.githubusercontent.com/3094382/62497522-872be600-b7dc-11e9-93c4-d8532a7522ab.png)

and

![qrenderdoc_2019-08-05_21-30-08](https://user-images.githubusercontent.com/3094382/62497528-8c893080-b7dc-11e9-946b-0d645166a9e7.png)

On the same mip level, with the original image being

![dev_grid_text](https://user-images.githubusercontent.com/3094382/62497546-9d39a680-b7dc-11e9-9ae1-0689ce8791bd.png)

**Comment by kvark** [comment]
@LaylConway thanks for the screenshot!
I think I just misread the info on the wiki, and we simply need to fix the example. Want to submit a PR? :)
