### ISSUE TITLE
Segfault when setting bind group

### ISSUE THREAD

**Issue by Binero** [gfx-rs/wgpu-rs#550]
I was trying to figure out how to get bind groups to work, when my code segfaulted. There is no unsafe code except `let surface = unsafe { instance.create_surface(window) };` which appears unrelated to the segfault.

The offending line is here:

https://github.com/Binero/learn-wgpu/blob/60533e77ebd4ba73d803f72eb2072639f46e5114/code/beginner/tutorial3-pipeline/src/main.rs#L193

I adapted the https://github.com/sotrh/learn-wgpu example as a minimal reproducible example. The segfault occurs in `/usr/lib/libvulkan_intel.so`, so it might be driver related.

**Comment by kvark** [comment]
It still amazes me how easy the drivers and validation layers can be crashed by code that is just not fully following the spec (i.e. doesn't pass garbage pointers around).

**Comment by kvark** [comment]
Fixed in wgpu-core-0.6.3
