### ISSUE TITLE
Open questions about errorsinkifying

### ISSUE THREAD

**Issue by scoopr** [gfx-rs/wgpu-rs#552]
I was looking at what next to errorsinkify, and started listing some open questions I have.

Missing bits
• No `swap_chain_error()` for fallback error id
• No `render_bundle_error()`

Errors "above" `Device`, like in `Adapter` or `Instance`, the current behaviour is probably the only reasonable one, as there is no uncaptured error handlers there, and just returning error-ids would just be confusing, so I'm fine with those being just panics.

Should `Device::poll` and `*_drop` call out to error_sink, are they recoverable? I would hate to have some special case errors in a normal loop that wouldn't be recoverable, but I guess those are a bit special.

Should `MapAsyncFuture` (from `buffer_map_async`) error type be wgpu::Error? Should it be sent to uncaptured handler just the same, right before completing the future?

What should `buffer_get_mapped_range` return as a fallback? Should it be Option?

`swap_chain_get_current_texture_view` returns most of the errors as status, but some not, should it synthesize some bad status on validation error, or does it need to be made recoverable outside of the status?

**Comment by kvark** [comment]
> No swap_chain_error()

That one isn't needed by the browsers, so I didn't make it. But we should totally make this consistent by having this error function!

> No render_bundle_error()

there is one!

> Errors "above" Device, like in Adapter or Instance, the current behaviour is probably the only reasonable one, as there is no uncaptured error handlers there, and just returning error-ids would just be confusing, so I'm fine with those being just panics.

Right.

> Should Device::poll and *_drop call out to error_sink, are they recoverable?

Anything bad that happens there is our *internal* error, so we shouldn't put it into users' error sink.

> Should MapAsyncFuture (from buffer_map_async) error type be wgpu::Error? Should it be sent to uncaptured handler just the same, right before completing the future?

The WebGPU spec says:
>If any of the following conditions are unsatisfied: ...
> Record a validation error on the current scope.
> Return a promise rejected with an AbortError on the Device timeline.

So it sounds like Yes?

> What should buffer_get_mapped_range return as a fallback? Should it be Option?

The spec says it should just return an error or panic.

**Comment by kvark** [comment]
> swap_chain_get_current_texture_view returns most of the errors as status, but some not, should it synthesize some bad status on validation error, or does it need to be made recoverable outside of the status?

Not sure about this one. Sounds like the former is simpler to start with.

**Comment by scoopr** [comment]
> > What should buffer_get_mapped_range return as a fallback? Should it be Option?
> The spec says it should just return an error or panic.

I took another look at the spec, and somehow I missed that there are some places where there are exceptions thrown. I guess those can be panics, thought it kind of would make sense to have them turned in to a Result/Error types. It doesn't need to be a `wgpu::Error` though. For example `getMappedRange` seems to be specced to throw `OperationError`, so in theory the return value could be something like `Result<&[u8], wgpu::OperationError>`, but then if the spec adds a case where it would throw something else also, then that wouldn't work. I guess it could be an enum variant in `wgpu::Error` also..

**Comment by scoopr** [comment]
> > No render_bundle_error()

> there is one!

Oops, I guess I meant `render_bundle_encoder_error`

**Comment by kvark** [comment]
This is because it's not really an ID:
```rust
pub type RenderPassEncoderId = *mut crate::command::RenderPass;
pub type ComputePassEncoderId = *mut crate::command::ComputePass;
pub type RenderBundleEncoderId = *mut crate::command::RenderBundleEncoder;
```
I suppose the way to go here would be to consider `ptr::null_mut` as the error ID

**Comment by scoopr** [comment]
> This is because it's not really an ID:

Hmm, but
```    type RenderBundleEncoderId = wgc::command::RenderBundleEncoder;
```
```pub struct RenderBundleEncoder {
    base: BasePass<RenderCommand>,
    parent_id: id::DeviceId,
    pub(crate) context: RenderPassContext,
}
```
So, its the struct itself, not a pointer to it?

> Not sure about this one. Sounds like the former is simpler to start with.

Ah, but I guess this also needs `swap_chain_error()` id (unless the detail is wrapped in option or something, which seems unnecessary)

**Comment by scoopr** [comment]
Oh and `buffer_get_mapped_range` is I think the only one that may change the user facing api here, so it would be nice to settle that to some kind of a conclusion. I don't really know how the exceptions should be mapped here.

**Comment by kvark** [comment]
> So, its the struct itself, not a pointer to it?

Oh, sorry, yeah, wgpu-rs uses the struct directly to avoid an indirection...

**Comment by kvark** [comment]
>  I don't really know how the exceptions should be mapped here.

I believe the exceptions would be our `unwrap()` things.

**Comment by scoopr** [comment]
I think many of these are resolved or punted later, closing it.
