### ISSUE TITLE
Maybe a race condition problem?

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [gfx-rs/wgpu-rs#554]
In writing a shader to do the blas function `sgemv` (the notable part being carrying out a matrix multiplication) I have encountered an issue which has baffled me for days and weeks at this point off and on.

In effect the shader does not produce what I want, a common problem. Unfortunately not only have I been unable to see where it actually goes wrong, but it goes wrong inconsistently.
Above a certain number of values (specifically starting at `993` which seems random to me) it produces a streak of incorrect values, for example (where `1` is correct)(actaul examples much longer):

> [1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,1,1,1]

But as aforementioned the `2`s in this case would often change, perhaps next time run they would be `3` then next time `2` and so on. Also notably, these changes do not seem to be entirely random, in the actual larger cases, it seems to alternative between a few values (in the test project the values it alternates between seem to be `707`,`770`,`778`,`780`,`786`,`794` and `802`).

The shader (the commented out barriers have been tested and they seem to make no difference):

```
#version 450
#extension GL_KHR_shader_subgroup_arithmetic : enable

layout(local_size_x = 32, local_size_y = 32, local_size_z = 1) in; // 32^2 = 1024

layout(binding = 0) buffer Buffer1 {
    float x[];
};
layout(binding = 1) buffer Buffer2 {
    float y[];
};

layout(r32f,binding = 2) uniform image2D A;

layout(binding = 3) buffer BufferOutputs {
    float outputs[];
};

// Need shared memory with an element for each invocation
layout(r32f,binding = 4) uniform image2D internal_holder;

layout(push_constant) uniform PushConsts {
    float alpha;
    float beta;
};

void main() {
    float val_A = imageLoad(A,ivec2(gl_GlobalInvocationID.x,gl_GlobalInvocationID.y)).x;
    float new_A = val_A * x[gl_GlobalInvocationID.x];

    imageStore(internal_holder,ivec2(gl_GlobalInvocationID.x,gl_GlobalInvocationID.y),vec4(new_A));

    //barrier();

    if (gl_GlobalInvocationID.x == 0) {
        ivec2 size = ivec2(imageSize(A));
        float sum = 0;
        for(int i=0; i<size.x; i++) {
            sum += imageLoad(internal_holder,ivec2(i,gl_GlobalInvocationID.y)).x;
        }
        //barrier();

        float new_y = y[gl_GlobalInvocationID.y] * beta;
        outputs[gl_GlobalInvocationID.y] = sum * alpha + new_y;
    }
}
```

I am (and have been for quite a bit) entirely lost with this. Perhaps I am misuing something in wgpu-rs here? It's my best guess right.

I would really appreciate any help or lead at all

The project: [webgpu-test.zip](https://github.com/gfx-rs/wgpu-rs/files/5192513/webgpu-test.zip)

**Comment by kvark** [comment]
I'm not an expert in compute shaders. I think there are many correctness issues here. Going to list them all, but some may end up being the result of my misunderstanding, so please just treat them as ideas for investigation:
  1. You are loading garbage data along the edges. Given that the matrix size is not perfectly divisible by the workgroup size, your total thread count in X and Y is larger than the matrix. Therefore, you can't legally load and store values by `ivec2(gl_GlobalInvocationID.x,gl_GlobalInvocationID.y)` coordinate, you can only do this for invocations within the target matrix.
  2. `barrier` is meant to synchronize the execution *within* the workgroup, while your code seems to assume it will synchronize between workgroups as well (i.e synchronize everything?)
  3. `barrier` only synchronizes the execution. It may not guarantee that the memory operations on the storage buffers and images are going to be in-order and atomic.

P.S. for (1) our goal is to guard out-of-bounds accessed, so that you never work with garbage. This is not implemented yet.

**Comment by JonathanWoollett-Light** [comment]
> barrier is meant to synchronize the execution within the workgroup, while your code seems to assume it will synchronize between workgroups as well (i.e synchronize everything?)
> barrier only synchronizes the execution. It may not guarantee that the memory operations on the storage buffers and images are going to be in-order and atomic.
> 

With `barrier` I was really just throwing stuff against the wall to see what sticks.

> You are loading garbage data along the edges. Given that the matrix size is not perfectly divisible by the workgroup size, your total thread count in X and Y is larger than the matrix. Therefore, you can't legally load and store values by ivec2(gl_GlobalInvocationID.x,gl_GlobalInvocationID.y) coordinate, you can only do this for invocations within the target matrix.

Apologies here, I forgot to mention that I have tried:

```
ivec2 size = ivec2(imageSize(A));
if (gl_GlobalInvocationID.x < size.x && gl_GlobalInvocationID.y < size.y) {
    ...    
}
```

Which I think relates to the issue you mention here. Adding this however has no affect.

**Comment by kvark** [comment]
> With barrier I was really just throwing stuff against the wall to see what sticks.

That's the problem right there. GPU computing is not a thing that you can beat with a stick until it works. You need to get an understanding of how the threads are executed and synchronized.

In the future, we'll make sure that at least you are getting the same result on all platforms. But this will not make your program run magically: it's just going to be broken on all platforms.

**Comment by JonathanWoollett-Light** [comment]
> That's the problem right there. GPU computing is not a thing that you can beat with a stick until it works. You need to get an understanding of how the threads are executed and synchronized.

I understand your point here, just in this case I've checked everything I know to check, so doing these extra small things as tests I see no harm in, since I've run out of ideas here.

**Comment by kvark** [comment]
> I see no harm in, since I've run out of ideas here.

Ok, good.
Do you understand why `barrier` can't help you here? Do you have a plan on how to synchronize the data processed by different work groups?
I could try to assist, but I imagine this compute task has been implemented thousands of times, and should be described in great detail, so maybe you just need a good reference to follow.

>I'm not sure what this point makes.

I'm trying to say that "playing with the code until it works" will not work in the future, even less than it's possible today.

**Comment by JonathanWoollett-Light** [comment]
> Do you understand why barrier can't help you here?

In this specific case `barrier` could help given all `993` invocations are within the same workgroup, in a larger sense this may not help but was simply for helping narrow down the issue.

> Do you have a plan on how to synchronize the data processed by different work groups?

With the current issue and size used for testing it, inter-workgroup synchronisation has no affect and beleive intra-workgroup synchronisation is trivailly implemented with barrier (https://stackoverflow.com/a/39395947/4301453). Right now I'm more focussed on the current problem, although I am sure I will think more about this moving forward.

Notably this specifies `barrier` is all that is needed to synchronise access to shared memory, It was my assumption buffers and textures are considered shared memory. However I also tested using `memoryBarrier();` aswell, which made no difference.

> I imagine this compute task has been implemented thousands of times, and should be described in great detail, so maybe you just need a good reference to follow.

I thought the same and searched for such a reference, but I cannot seem to find any. If you know of one that would be great.

> I'm trying to say that "playing with the code until it works" will not work in the future, even less than it's possible today.

Fair point.

**Comment by kvark** [comment]
> In this specific case barrier could help given all 993 invocations are within the same workgroup, in a larger sense this may not help but was simply for helping narrow down the issue.

I don't understand this part. Which 993 invocations?
You have 993x993 threads. Given the workgroup size of 32x32, this makes up for 32x32 groups, or 1024 groups in total.

> It was my assumption buffers and textures are considered shared memory. 

The shared memory is *specific* GPU memory shared by the threads in the workgroup, also called "threadgroup memory". Your shaders aren't using this memory. It's not related to textures and buffers.

**Comment by JonathanWoollett-Light** [comment]
> I don't understand this part. Which 993 invocations?

Nevermind what I said there, was wrong, thinking there was 993 invocations instead of 993x993.

I need to do more research around this. Tricky part is I can't really find any good references for this stuff (maybe I don't know what to google) if you got anything which might relate to this you could link I'd appreciate it.

The fundemental difficult thing here is trying to sum rows in a matrix, something as you say one would expect there would be resources about, I just can't seem to find any.

**Comment by kvark** [comment]
I searched briefly, and I agree - it appears to be well hidden, even though it's supposed to be a standard textbook problem.
