### ISSUE TITLE
Error running the Bevy engine and wgpu example cube.

### ISSUE THREAD

**Issue by actuday6418** [gfx-rs/wgpu-rs#560]
I cloned the wgpu repo, and ran cargo run --example cube. The program crashes and I get the following output in my terminal - 
```
WARNING: vallium/llvmpipe is not a conformant vulkan implementation, testing use only.
INTEL-MESA: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

[0.102421 ERROR]()(no module): 
GENERAL [Loader Message (0)] : loader_create_device_chain: Failed to find 'vkGetInstanceProcAddr' in layer libVkLayer_MESA_device_select.so.  Skipping layer.
object info: (type: INSTANCE, hndl: 94642556444720)

Segmentation fault

```

The reason why I did this in the first place is to run Bevy, which uses the wgpu crate. 
output of vulkaninfo - https://pastebin.pl/view/0fddc576
vulkan-smoketest runs error free. 

**Result of running Bevy -** 
```
 Running `target/debug/bevy_app`
WARNING: vallium/llvmpipe is not a conformant vulkan implementation, testing use only.
INTEL-MESA: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

thread 'main' panicked at 'Failed to acquire next swap chain texture!', /home/actuday/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_wgpu-0.1.3/src/renderer/wgpu_render_resource_context.rs:291:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
My laptop is an [Acer A515-51](https://www.acer.com/ac/en/IN/content/model/NX.GSYSI.004) running ElementaryOS Hera based off Ubuntu 18.04, with an Intel® UHD Graphics 620 integrated graphics processor.

**Comment by kvark** [comment]
Can you run `vkcube` which is a part of one of the standard vulkan packages (like vulkan-tools)?

It looks like `wgpu` is trying to run on Vallium on your machine, which (as it states) is not a conformant implementation, so it's failing.
Your platform should be able to support Vulkan natively though, as long as you have the drivers installed. So either you don't have the drivers, for the platform is configured to only expose the software implementation for some reason.

**Comment by actuday6418** [comment]
`vkcube` runs okay. The terminal prints the following output - 
```
WARNING: vallium/llvmpipe is not a conformant vulkan implementation, testing use only.
INTEL-MESA: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
```

**Comment by kvark** [comment]
Thank you!
Could you run our example through gdb and see the stack trace?

**Comment by actuday6418** [comment]
I'd spent some time earlier installing vulkan and upgrading it from another PPA. For some reason, the wgpu examples run okay now with just the warnings -
```
WARNING: vallium/llvmpipe is not a conformant vulkan implementation, testing use only.
INTEL-MESA: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

```
But bevy still doesn't run. I get the same error message. Thanks for your help.

**Comment by kvark** [comment]
Yes, more complex stuff wouldn't run, because, as the warning says, your driver is non-conformant.
You should look for a way to install the real Intel iGPU Vulkan driver instead of Vallium.

**Comment by marvinsxtr** [comment]
I ran into the same issue and I followed [these steps](https://askubuntu.com/a/853655/935998) to resolve it.

**Comment by alekspickle** [comment]
ran on it with PC Ubuntu 18.04 and RTX 2060. @marvinsxtr`s way did not help.

**Comment by kvark** [comment]
@alekspickle are you having the same problem? What is your output?

**Comment by marvinsxtr** [comment]
I believe the driver I referred to is for Intel graphics cards only. @alekspickle Maybe you could find something suitable [here](https://developer.nvidia.com/vulkan-driver).

**Comment by alekspickle** [comment]
@kvark not quite. The code runs ok its just the warning is confusing. I dont get why **vallium/llvmpipe** would involved: I ran examples before and it did not appear

**Comment by actuday6418** [comment]
@marvinsxtr 's answer solved the problem for me

**Comment by cwfitzgerald** [comment]
> @kvark not quite. The code runs ok its just the warning is confusing. I dont get why **vallium/llvmpipe** would involved: I ran examples before and it did not appear, I assume this is more of nvidia vulkan driver issue

It could be that the warning shows up as soon as it enumerates devices.

Could you run the examples from latest master, it will print what device you are using to render.
