### ISSUE TITLE
USM?

### ISSUE THREAD

**Issue by jon-chuang** [gfx-rs/wgpu-rs#568]
Will there be support for page-fault based USM? Available both on HIP and CUDA.

**Comment by cwfitzgerald** [comment]
What is USM? A precursory google didn't find anything.

**Comment by cwfitzgerald** [comment]
I re-dug into this and it appears USM stands for "unified shared memory" ([info from nvidia](https://developer.nvidia.com/blog/unified-memory-cuda-beginners/)) which likely is equivalent to some kind of coherent memory type, which we should support, at least in part, through `MAPPABLE_PRIMARY_BUFFERS`. Closing for now. If there is something more specific needed, please feel free to re-open.
