### ISSUE TITLE
Shader validation error for sampler usage

### ISSUE THREAD

**Issue by antonok-edm** [gfx-rs/wgpu-rs#573]
```
thread '<unnamed>' panicked at 'error in stage FRAGMENT: error matching global binding at index 2 in set 0 against the pipeline layout: load/store access flags LOAD don't match the shader', ~/.config/cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/backend/direct.rs:1323:35
```

I've attempted to add texture support to a WIP framework I am developing, and my code causes this panic at runtime. Most of the relevant new code is modeled off of the `cube` example. This is running `wgpu` 0.6 as published to crates.io.

I have the exact same bind group configuration as `cube`, so index 2 in set 0 is the `Sampler` and index 1 is the `SampledTexture`.

This is the fragment shader I've been using:
```glsl
#version 450
#extension GL_ARB_separate_shader_objects : enable

layout(location = 0) in vec2 quadCoord;
layout(set = 0, binding = 1) uniform texture2D t_Color;
layout(set = 0, binding = 2) uniform sampler s_Color;

layout(location = 0) out vec4 outColor;

void main() {
    outColor = texture(sampler2D(t_Color, s_Color), quadCoord);
}
```

Disabling shader validation when requesting the device prevents the panic.

**Comment by kvark** [comment]
This is an old issue that is likely fixed. We are moving to wgpu now, so please re-open there if still a bug!
