### ISSUE TITLE
Document buffer mapping alignment requirements

### ISSUE THREAD

**Issue by Yamakaky** [gfx-rs/wgpu-rs#578]
```rust
                    let slice = buffer.slice(0..1);
                    slice.map_async(wgpu::MapMode::Read).await.unwrap();
```
panics with `buffer map range does not respect COPY_BUFFER_ALIGNMENT`. The slice must be aligned to COPY_BUFFER_ALIGNMENT but the doc of slice and map_async doesn't specify it.

BTW, is there a way to get better error messages ? All I get is
```
panicked at 'buffer map range does not respect `COPY_BUFFER_ALIGNMENT`', /home/xxx/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/backend/direct.rs:1323:35
```
which doesn't help a lot.

**Comment by kvark** [comment]
This is an old issue that is likely fixed. We are moving to wgpu now, so please re-open there if still a bug!
