### ISSUE TITLE
Use Proper Workgroup Sizes in Compute Shader

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu-rs#582]
(Making an issue to discuss before I went ahead and did it)

I think we should include proper workgroup sizes in the hello-compute example. This would also require shipping the actual size of the array as a uniform (would be a push constant but web support), to cut off overrun.

While normally I would consider this to be a "next step" thing after a hello world example, but a couple things changed my mind. 
- Basically all compute shaders should have a proper workgroup size and they will ship sizes as needed. This seems like a part of the "inherent complexity" of a lower level abstraction like compute shaders. 
- I was helping someone new to gpu computing in general with compute shaders and unless I had said something, nothing would've informed them of the performance ramifications of the "easy" `1x1x1` workgroup size. I think it's important tutorial-like code get things like this right, if they are hard to discover.

If you agree, I can make this change, with documentation explaining _why_ this is done.

**Comment by kvark** [comment]
I think the point of hello-compute is not to demonstrate how it *should* be done. Instead, it's the minimal example of how it *could* be done. From this perspective, adding the complexity of an extra uniform seems unnecessary.
If users want to see a more realistic example, they should look at `boids`.

**Comment by cwfitzgerald** [comment]
I think that's fair enough. I honestly forget the boids example uses compute shaders (and often that it exists as all).
