### ISSUE TITLE
water panic

### ISSUE THREAD

**Issue by notoria** [gfx-rs/wgpu-rs#592]
Since commit 4f57899b0de7fe927ed5a9c76e92283cdf58c8a0, the example `water` panics with:
```
thread 'main' panicked at 'attempt to subtract with overflow', /home/begin/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-vulkan-0.6.1/src/device.rs:1785:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by kvark** [comment]
@notoria I'm able to reproduce. This is a regression from https://github.com/gfx-rs/wgpu/pull/962. I'm fixing this ASAP. Sorry about the inconvenience!
