### ISSUE TITLE
TextureFormat::R16Unorm?

### ISSUE THREAD

**Issue by eseaflower** [gfx-rs/wgpu-rs#597]
I am trying to sample a 16-bit (unsigned int) texture in a shader using texture format R16Uint. This works great with the Vulkan backend, however when I try to use the DX12 backend I get an error informing me that HLSL does not support sampling from non-integer textures. So I thought I'd change the texture format to R16Unorm, but this format seems to have disapeared? When googling for it I find a reference in wgpu-types v. 0.4.0 but it seems to have disapeared in a later update.

Why has the R16Unorm format disapeared, has it been replaced by another format?

**Comment by kvark** [comment]
Let's continue in https://github.com/gfx-rs/wgpu/issues/999
