### ISSUE TITLE
Panic on drop of a surface with the GL backend

### ISSUE THREAD

**Issue by Lonsdaleiter** [gfx-rs/wgpu-rs#607]
`thread 'main' panicked at 'assertion failed: (left != right)`

I notice that on the master branch with the latest commit enabling the GL backend, I get the above panic with the following code:

```rust
let instance = Instance::new(BackendBit::GL);
let surface = Surface::new(&window);
drop(surface); // panic here
```

The panic occurs on line 135 of the surfman module "platform/generic/egl/context."

Display server: X11
WM: i3

**Comment by kvark** [comment]
I believe this is https://github.com/gfx-rs/gfx/issues/3467
