### ISSUE TITLE
`set_index_buffer` should accept index format

### ISSUE THREAD

**Issue by grovesNL** [gfx-rs/wgpu-rs#608]
We should accept an index format in `set_index_buffer` to match the upstream API https://github.com/gpuweb/gpuweb/blob/0480646a43fabd7de42d62ee394e085c8824c975/spec/index.bs#L5441

We'll need to:
1. update the API to accept this
2. change the native backend to use it
3. update the WebIDL in wasm-bindgen and use the new signature in the web backend (we can do this after 1 and 2 are complete)

**Comment by kvark** [comment]
In addition, render pipeline descriptor should have the index format as optional.

**Comment by kvark** [comment]
Relevant https://github.com/gfx-rs/wgpu/issues/978

**Comment by kvark** [comment]
Already filed upstream
