### ISSUE TITLE
Please add support for the new `raw-window-handle` crate

### ISSUE THREAD

**Issue by Lokathor** [gfx-rs/wgpu-rs#64]
Recently the gamedev-wg has been trying to make it easier for windowing libs and graphical libs to agree on a protocol for communication. This has resulted in the [raw-window-handle](https://crates.io/crates/raw-window-handle) crate, where the window offers up its OS window handle thingy to the graphical lib upon request and then the graphical lib is able to do its startup.

It seems like wgpu is mostly going through `wgn` and that's going through the gfx-backend stuff at the moment, [that issue here](https://github.com/gfx-rs/gfx/issues/2956) would be a natural first step towards using `raw-window-handle` with this crate.

Tracking issue where this crate was discussed and crated if you have any questions: https://github.com/rust-gamedev/wg/issues/26

**Comment by seivan** [comment]
Maybe I'm missing something, but isn't most of them unimplemented for now? 
https://github.com/rust-windowing/raw-window-handle/blob/master/src/ios.rs

**Comment by Lokathor** [comment]
Yes.

the idea is (to use the gfx-hal terms since i don't know the wpgu terms), you'd have the end user be able to write

```rust
let surface = instance::create_surface(&window);
```

and all the stuff would be _nearly_ as it is now, but wgpu wouldn't depend on `winit::Window`, it'd depend on `impl raw_window_handle::HasRawWindowHandle`.

**Comment by kvark** [comment]
Fixed in #70
