### ISSUE TITLE
WebGL Support

### ISSUE THREAD

**Issue by AlexandreKawan** [gfx-rs/wgpu-rs#642]
It should be possible to use WebGL as a backend for wgpu-rs because most browsers do not yet support WebGPU.

**Comment by kvark** [comment]
See also:
- https://github.com/gfx-rs/wgpu-rs/issues/418
- https://github.com/gfx-rs/wgpu/issues/115

**Comment by kvark** [comment]
The support for this has landed.
see https://github.com/gfx-rs/wgpu-rs/wiki/Running-on-the-Web-with-WebGPU-and-WebGL#setting-up-webgl
More work ahead to make it actually work nice.
