### ISSUE TITLE
Incorrect shader validation when using wgpu::VertexFormat::Ushort2Norm

### ISSUE THREAD

**Issue by lain-dono** [gfx-rs/wgpu-rs#645]
I use `wgpu 0.6.2` from [crates.io](https://crates.io/) and https://github.com/gfx-rs/wgpu-rs/blob/v0.6/examples/hello-triangle/main.rs as a basis

changes in main.rs:

```rust
        vertex_state: wgpu::VertexStateDescriptor {
            index_format: wgpu::IndexFormat::Uint16,
            vertex_buffers: &[wgpu::VertexBufferDescriptor {
                stride: 2 * 2,
                step_mode: wgpu::InputStepMode::Vertex,
                attributes: &wgpu::vertex_attr_array![0 => Ushort2Norm], // Float2 works without error
            }],
        },
```

shader.vert:

```glsl
#version 450

layout(location = 0) in vec2 a_TexCoord;
layout(location = 0) out vec2 v_TexCoord;

void main() { v_TexCoord = a_TexCoord; }
// void main() { } // works without error
```

shader.frag:

```glsl

#version 450

layout(location = 0) out vec4 outColor;
layout(location = 0) in vec2 v_TexCoord;

void main() { outColor = vec4(1.0, 0.0, 0.0, 1.0); }
```

```
thread 'main' panicked at 'error in stage VERTEX: error matching the stage input at 0 against the previous stage outputs: input type is not compatible with the provided', /home/lain/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.2/src/backend/direct.rs:1355:35
```

[full stderr/stdout](https://gist.github.com/lain-dono/72daaca817c8c15a4745c5c13cc193f7)

Looks like issue in naga.

```
$ glslc --version
2020.3
2020.4
11.0.0

Target: SPIR-V 1.0

$ rustc --version
rustc 1.50.0-nightly (fe982319a 2020-11-19)
```

**Comment by kvark** [comment]
Seems to validate fine in `master`. Naga integration has gone a long way since 0.6 was out.
How do you feel about either moving to `master` or disabling `DeviceDescriptor::shader_validation` for now, until we roll out 0.7?

**Comment by lain-dono** [comment]
In fact, I moved from the master to 0.6.2 only for the test.

**Comment by kvark** [comment]
@lain-dono could you confirm if this works as expected for you on master? Just in case, I pushed a commit I was testing in https://github.com/kvark/wgpu-rs/tree/test-ushort2-attrib

**Comment by Lowentwickler** [comment]
> Seems to validate fine in `master`. Naga integration has gone a long way since 0.6 was out.
> How do you feel about either moving to `master` or disabling `DeviceDescriptor::shader_validation` for now, until we roll out 0.7?

Maybe a wrong place to ask, but is there some estimation of 0.7 release?

**Comment by kvark** [comment]
I think we'll start some preparations now, just needed to finish the bind group layout changes that were hanging in the air. Should expect 0.7 to come before the end of the year.

**Comment by kvark** [comment]
This is an old issue that is likely fixed. We are moving to wgpu now, so please re-open there if still a bug!
