### ISSUE TITLE
Exclude GL backend on macOS

### ISSUE THREAD

**Issue by lordnoriyuki** [gfx-rs/wgpu-rs#646]
Any chance the GL backend could be made optional (like Vulcan) on MacOS?

**Comment by kvark** [comment]
That wasn't in the plans. OpenGL has been deprecated for years on macOS. There are no tools, no capabilities, and no good drivers on Apple ecosystem for GL. Why would you need it?

**Comment by lordnoriyuki** [comment]
Sorry, I should've been clearer. I want to turn it off on macOS, because it's just unnecessary dependencies and bloat. Right now, it builds the GL backend on macOS.

**Comment by kvark** [comment]
Oh yeah, we should totally make it Linux+Android only. In fact, the latest gfx-backend-gl on master is limited to that, and it has many times fewer dependencies. We should either limit it or remove it completely from `wgpu` for now, until we can switch the gfx dependency to master - 
Relevant bit is https://github.com/gfx-rs/wgpu/blob/dd31c924df6a139a5a5294ee8db7d83c9b2217a6/wgpu-core/Cargo.toml#L51 plus the `gfx_select` macro https://github.com/gfx-rs/wgpu/issues/1027
