### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by cloudhead** [gfx-rs/wgpu-rs#65]
With the release of 0.3.0, it would be nice if this was published to crates.io, along with wgpu-native. I'm trying to pull this in as a dependency for another crate, but cargo doesn't accept git dependencies.

**Comment by kvark** [comment]
Note that gfx-rs is an *implementation detail* here. The fact that its dependency got updated to another breaking change means no consequences for wgpu-rs.

At the same time, we've been planning on a release for a while, and are approaching it now. See https://github.com/gfx-rs/wgpu/pull/284 and https://github.com/gfx-rs/wgpu/pull/285 , which might be the last bits we need before the release.

**Comment by cloudhead** [comment]
Oh I was referring to the version bump of wgpu to 0.3.0 - though I guess that was a coincidence. Good to see that we're close to a release though!
