### ISSUE TITLE
Emscripten support

### ISSUE THREAD

**Issue by pavlukivan** [gfx-rs/wgpu-rs#661]
wasm-bindgen only supports wasm32-unknown-unknown, but you basically can't interop with C when using that target. Any chance wasm32-unknown-emscripten is added? It should be fairly simple, they implement both webgpu.h and an OpenGL port using WebGL, so emscripten apps can start using wgpu-rs right away without tweaking browser settings

**Comment by kvark** [comment]
What is that you are trying to do, exactly?

If you want to target emscripten by wgpu-rs apps, then first we need a wgpu-rs backend that works on https://github.com/webgpu-native/webgpu-headers

If you want Emscripten apps to use `wgpu`, then we'd need to have `wgpu-native` aligned with shared headers - https://github.com/gfx-rs/wgpu-native/issues/6

**Comment by pavlukivan** [comment]
I see, is there any chance to use the OpenGL backend for now then?

**Comment by grovesNL** [comment]
The OpenGL backend has recently been re-enabled on `master` so it's still missing quite a bit of functionality. The primary backends (Vulkan, Metal, DX12) are recommended for now, with a lot of progress on DX11 recently too.

WebGL support (through wasm32-unknown-unknown) hasn't been enabled yet – see #642.

**Comment by pavlukivan** [comment]
(Accidental close)

The WebGL backend won't contribute towards Emscripten support, but if the OpenGL backend is still WIP it does make sense to wait for it to become more mature before integrating with emscripten. A wgpu-rs backend for emscripten's webgpu.h is another way forward, but isn't too high priority either since browsers don't support webgpu out of the box yet.

**Comment by kvark** [comment]
We can consider this a part of GL backend support, if I understand correctly
