### ISSUE TITLE
Invalid HLSL generated for push constants in rust-gpu example

### ISSUE THREAD

**Issue by grovesNL** [gfx-rs/wgpu-rs#670]
(just filing this issue so I don't forget about it)

Invalid HLSL seems to be generated when trying to push constants on the DX12 backend in [rust-gpu's sky shader example](https://github.com/EmbarkStudios/rust-gpu/blob/adebc900706ce0b75a6ff9839b1cbbd9ddb3b939/examples/shaders/sky-shader/src/lib.rs). According to the chat on Discord, the HLSL ends up containing lines like `static ??? _765;`

I quickly glanced through the wgpu example runner and the push constant does appear to be defined and set, but we should check what's happening here in case it's a bug in SPIRV-Cross/wgpu/gfx-hal that we could address.

Also rust-gpu seems to be using wgpu 0.6 so it would also be useful to test it on `master` in case it's already addressed somewhere.

**Comment by grovesNL** [comment]
I glanced at the problematic SPIR-V a few weeks ago, and it looks like it might be related to EmbarkStudios/rust-gpu#362 on rust-gpu's side. i.e. SPIRV-Cross expects this too, because we're following the Vulkan rules when converting SPIR-V to HLSL. So maybe we can wait for that fix first in case we don't have to do anything here.

**Comment by kvark** [comment]
We are moving to wgpu now, so please re-open there if still a bug!
