### ISSUE TITLE
Add 'swap_chain_get_preferred_format' to wgpu-rs (available in wgpu-core but not exposed)

### ISSUE THREAD

**Issue by manugildev** [gfx-rs/wgpu-rs#691]
> we actually have `swap_chain_get_preferred_format` in `wgpu-core`. We should expose this in `wgpu-rs`
> _Originally posted by @kvark in https://github.com/gfx-rs/wgpu-rs/pull/511#discussion_r473203364_

This functionality was commited in https://github.com/gfx-rs/wgpu/commit/6f1d6145f555ebbe89b0cca94288990cc0368223 but never exposed to wgpu-rs.

Problem: Currently, examples make use of `wgpu::TextureFormat::Bgra8UnormSrgb` but that's unreliable and [according to the API ](https://gpuweb.github.io/gpuweb/#dom-gpucanvascontext-getswapchainpreferredformat)this method is the way of properly obtaining an optimal texture format for the swapchain based on the platform.

**Comment by kvark** [comment]
There has been recent discussions upstream about this - https://github.com/gpuweb/gpuweb/pull/1185 and https://github.com/gpuweb/gpuweb/issues/1231
Good news is that this function is still there, and it's not asynchronous! So exposing it in wgpu-rs should be trivial (and much needed).
