### ISSUE TITLE
Don't use Option for pipeline fields that are inferred

### ISSUE THREAD

**Issue by JMS55** [gfx-rs/wgpu-rs#692]
Currently in `RenderPipelineDescriptor`, a value of `None` for certain fields truly means None, while it means inferred from the shader for others. The second case should instead use something like this:

```rust
enum InformationSource<T> {
   Explicit(T),
   Inferred
}
```

**Comment by kvark** [comment]
One one hand, you are clearly correct here. `Option` isn't explicit about what's going on, and in a rich type system we can express this better.
On the other hand, that's what upstream WebGPU does, and on top if it - much simpler to use for the users. Typing `wgpu::InformationSource::Explicit(layout)` all the time is a small downside.
All in all I'm not feeling strongly about this case.

**Comment by JMS55** [comment]
I personally feel that verbosity isn't an issue. You can import the whole `wgpu::Information::Source::*`, and then do `Explicit(layout`). Basically the same verbosity as Option, it's only an extra import.

In terms of matching upstream WebGPU, I'm not sure it makes sense to copy exactly what they do for the Rust API. Javascript is a weakly typed language. wgpu-rs should not limit itself to expressiveness of javascript, when it's possible to do better.

**Comment by kvark** [comment]
It could also be `explicit_layout: Option<>`, fwiw
I don't find the argument "you can import Xxx" to be very convincing. So far the API has been developed without an assumption that anything is imported. For example, we are avoiding traits on the API side.

**Comment by kvark** [comment]
I believe these changes need to be raised upstream in WebGPU first, and we can just follow 1:1
