### ISSUE TITLE
Example to render overlay text

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [gfx-rs/wgpu-rs#704]
Hello,

Does WGPU supports text rendering ? or if it's handled by an extension ?
If it's supported, is it possible to provide an example of overlay text rendering ?

Thanks
Marc-Antoine

**Comment by cwfitzgerald** [comment]
Wgpu isn't the level of abstraction that would do text rendering, but can be used to create text renderers, take a look at [wgpu-glyph](https://github.com/hecrj/wgpu_glyph) as a convinent way of rendering text.
