### ISSUE TITLE
Unable to compile wgpu for a Wasm build on 0.6.2

### ISSUE THREAD

**Issue by sortofsleepy** [gfx-rs/wgpu-rs#712]
👋 

Hopefully I'm just doing something dumb and overlooking something but I cannot seem to build for Wasm with `0.6.2` on Windows(and if it happens to matter, I'm building with CLion and the Jetbrains Rust plugin). Right now I'm just trying to build a simple test project. 

Settings are 
* `--target wasm32-unknown-unknown`
* `RUSTFLAGS=--cfg=web_sys_unstable_apis`

Things always fail when the compiler tries to compile `web.rs`

![webgpuerrors](https://user-images.githubusercontent.com/308302/104269323-e159bd80-544a-11eb-8bca-51d73a391c53.PNG)

(apologies - figured the line number, would be easier to digest here, if it would help I can go back and add the entire error message)

Am I forgetting something? Any help is appreciated. Thank you!

**Comment by kvark** [comment]
There is no use of the published version for the Web target, since the latter is being actively developed, the API changes, and there is no stability yet. To test the web target, you need to use the `master` (which can be a bit ahead), or the `gecko` branch (which can be a bit behind, we update the pointer from time to time).

**Comment by sortofsleepy** [comment]
> 
> 
> There is no use of the published version for the Web target, since the latter is being actively developed, the API changes, and there is no stability yet. To test the web target, you need to use the `master` (which can be a bit ahead), or the `gecko` branch (which can be a bit behind, we update the pointer from time to time).

Ah, I see. I had assumed that the current published crate reflected `master`, I didn't realize it was different. 
Thanks for the help!
