### ISSUE TITLE
0.6.2 panics with PendingTransition error

### ISSUE THREAD

**Issue by jeancf** [gfx-rs/wgpu-rs#747]
I am confronted to a panic in wgpu-rs 0.6.2 that I cannot interpret.

I am adding shadow mapping to my render loop. I have one render pass per light to compute shadows followed by a forward render pass for the scene.
When building the command buffer of the first shadow pass, the program panics at `encoder.finish()` with the error:

    PendingTransition { id: Valid((5, 1, Vulkan)), selector: TextureSelector { levels: 0..1, layers: 1..2 }, usage: SAMPLED..ATTACHMENT_WRITE }

In my setup, the buffer that has SAMPLED and ATTACHMENT_WRITE usages is the depth buffer of the shadow pass.

Drilling down in the call stack, I found that the panic is issued in the `track` module of wgpu-core where `change_extend()` calls `RessourceState::change()`. The doc of the method says:

    If output is None, the old usage is extended with the new usage. The error is returned if it's not possible, specifying the conflicting transition. Extension can only be done for read-only usages.

Interestingly, when I replace the TextureViews of the shadow buffer by the TextureView of the depth buffer used in the forward pass the app compiles and run (but without shadows of course).

Here is the line where it panics: https://gitlab.com/jeancf/wgpu-and-me/-/blob/shading2/src/shading/graphics.rs#L1142

I do not understand what I am doing wrong and I could use some clues to resolve the problem. Thanks!

**Comment by kvark** [comment]
You are trying to use the same texture subresource as both `SAMPLED` and `ATTACHMENT_WRITE` within the same synchronization scope. In this case, you are rendering to something that you are also trying to bind in a group in the same render pass.

**Comment by jeancf** [comment]
Yesssss! Thanks a lot! It is so easy once you know the answer :-)

**Comment by kvark** [comment]
What we want most here is that instead of `id: Valid((5, 1, Vulkan))` you see the name of the texture (if it's named). We are heading there...

**Comment by dhardy** [comment]
I am now seeing this, which I think is the same error?
```
wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `render`
    In a pass parameter
      note: command buffer = `render`
    Attempted to use texture (2, 1, Vulkan) mips 0..1 layers 0..1 as a combination of ATTACHMENT_WRITE within a usage scope.
```

> ... within the same synchronization scope

In my case the texture is used for indirect rendering (to texture, then to screen). Each usage is in a separate render pass (but same command encoder) — this is what the `shadow` example does.

**Comment by kvark** [comment]
@dhardy this is an interesting one. It says you are using the mip0 layer 0 *multiple times* in your attachments. e.g. the same view is both attachment 0 and attachment 1. Is this what you are doing? If unsure, attach a zipped API trace, and we'll see ;)

**Comment by dhardy** [comment]
Probably that is what I'm doing: so it's necessary to use a different *view* of the texture for each usage? That didn't help.

From what I understand of the shadow example, only `base_array_layer` and `array_layer_count` differ from the default values for the target views, and that is only necessary because the texture layer count is greater than one. In my case it's equal to one, so `tex.create_view(&wgpu::TextureViewDescriptor::default());` should suffice for both target and "forward" pass views?

**Comment by kvark** [comment]
> so it's necessary to use a different view of the texture for each usage? 

More info here https://gpuweb.github.io/gpuweb/#programming-model-resource-usages
See the "Some internal usages are compatible with others" paragraph.
Could you hop on "#wgpu:matrix.org" to talk about this? Issues are not the best for discussing this.

**Comment by dhardy** [comment]
Aha, I was mistakenly re-using the `RenderPassColorAttachment` of the target for the forward render.
