### ISSUE TITLE
Async functions for map_{read|write}_async instead of callbacks?

### ISSUE THREAD

**Issue by lachlansneff** [gfx-rs/wgpu-rs#76]
I'm not entirely sure how it works underneath, but would it be possible for these to be async functions (or to return a Future)? I notice that the callback recieves a borrowed slice, is that just an artifact of the api or an internal necessity?

**Comment by kvark** [comment]
We are open to ideas on how to make those methods more available.
Also see https://github.com/gfx-rs/wgpu-rs/pull/13 (which got abandoned, unfortunately, :cry: @nical)

**Comment by lachlansneff** [comment]
Awesome! I'll do some research and propose a possible api or will go and update #13!

**Comment by nical** [comment]
>  We are open to ideas on how to make those methods more available. Also see #13 (which got abandoned, unfortunately,  @nical)

I think that the proposal in #13 should not be a lot of work to implement if anyone wants to take a look. I haven't had as much time for spare time coding as I hoped this summer unfortunately.

**Comment by swiftcoder** [comment]
I'm looking at this with #120 now as well - please don't hesitate to weigh in on that diff if you have suggestions.

**Comment by fintelia** [comment]
I believe this is now resolved?

**Comment by cwfitzgerald** [comment]
Yup!
