### ISSUE TITLE
device.create_render_pipeline fails to locate entry point in fragment stage

### ISSUE THREAD

**Issue by ElhamAryanpur** [gfx-rs/wgpu-rs#760]
Hello!

So I was following sotrh tutorial on the wgpu and implemented textures. Now I do know new updates have changed a lot of descriptors, but I did fix those changes.

However, I get error as:
`wgpu error: Validation Error`
`error in stage FRAGMENT`
`unable to find an entry point at "main" stage`

To test, I also tried just having a very simple fragment shader that have white color as output, still same error. I use shaderc for compiling glsl shaders to SPIR-V and no error there either. I tried even changing the main function name, still same error.

**Comment by ElhamAryanpur** [comment]
The core code for the main renderer is [here](https://github.com/BlueMazar/BlueEngineCore/tree/128dce3d15b8769457cc1101cce408a543412651) and the crate that uses it, which is where shaders exist too is [here](https://github.com/BlueMazar/BlueEngine/tree/27abff52121cb170828abeefe7575619a3473e88)

**Comment by ElhamAryanpur** [comment]
It was an error with the shaderc, sorry

**Comment by ElhamAryanpur** [comment]
Please close this issue

**Comment by grovesNL** [comment]
No problem, thanks for the update!
