### ISSUE TITLE
WGPU 0.7 validation error with WGSL texture_2d

### ISSUE THREAD

**Issue by jeancf** [gfx-rs/wgpu-rs#775]
Texture created from a .png file with:
```
dimension: wgpu::TextureDimension::D2,
format: wgpu::TextureFormat::Rgba8UnormSrgb,
usage: wgpu::TextureUsage::SAMPLED | wgpu::TextureUsage::COPY_DST,
```

In GLSL everything work when I sample it with:
```
layout (set = 0, binding = 1) uniform texture2D tex;
outColor = texture(sampler2D(tex, samp), frag_uv);
```

In WGSL I tried to use:
```
[[group(0), binding(1)]]
var tex: texture_2d<f32>;

[[location(0)]]
var<out> out_color: vec4<f32>;

out_color = textureSample(tex, samp, frag_uv);
```

and I get:
```
wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
    error in stage FRAGMENT
    error matching global binding at index 1 in group 0 against the pipeline layout: texture class Sampled { kind: Uint, multi: false } doesn't match the shader Sampled { kind: Float, multi: false }
```

I think this is saying that my texture_2d declared as f32 does not match the texture that is a Uint

But the documentation of WGSL says:

* type must be f32, i32 or u32
* The parameterized type for the images is the type after conversion from sampling. E.g. you can have an image with texels with 8bit unorm components, but when you sample them you get a 32-bit float result (or vec-of-f32).

What am I doing wrong?

**Comment by kvark** [comment]
What is says is that your `BindGroupLayoutEntry` has the `Uint` kind for the binding, while this needs to be `Float`.
The error is correct in this case.
Also, please check out the examples, which use textures quite a bit.

**Comment by jeancf** [comment]
I am sorry I did not think of looking at the examples first, the answer was there indeed.

Thanks for your response.
