### ISSUE TITLE
[0.7] hello-triangle example crash on win10

### ISSUE THREAD

**Issue by Nalleyer** [gfx-rs/wgpu-rs#787]
# Reproduction:
```
> git clone https://github.com/gfx-rs/wgpu-rs wgpu-rs-7
> cd wgpu-rs-7
# i wrote a bat to run with debug log and traceback
> cat debug.bat
# set RUST_BACKTRACE=1
# set RUST_BACKTRACE=1
# cargo run --example hello-triangle
> debug.bat
```
The window appeared and the program crashed. 
![图片](https://user-images.githubusercontent.com/11672704/110895557-f496e580-8334-11eb-8ca7-04530b5025c8.png)

# Full log:

[log.txt](https://github.com/gfx-rs/wgpu-rs/files/6127755/log.txt)

# Environment:

windows 10 pro 64bit x64
Intel(R) Core(TM) i7-7700 CPU @3.60GHz
GPU0: GeForce GTX 1060 6GB
GPU1: Intel(R) HD Graphics 630

# Other

when using BackendBit::DX12, it's works fine

Thanks in advance!

**Comment by kvark** [comment]
Thank you for filing!
Could you please grab a stack trace from this crash?
Also, could you try running `Ash` and/or `gfx-rs` examples on Vulkan?

**Comment by Nalleyer** [comment]
Thank you for answering, @kvark , I tried to run the example quad in gfx-rs project with
```
 cargo run --bin quad --features vulkan
```

It works, the window shows up with a gfx-rs logo. also with a alot of validation error.

the compute and bench example works well.

[log.txt](https://github.com/gfx-rs/wgpu-rs/files/6138487/log.txt)

The triangle example in ash works pretty well.

```
cargo run --bin triangle
```
[log_ash.txt](https://github.com/gfx-rs/wgpu-rs/files/6138513/log_ash.txt)

**Comment by kvark** [comment]
If you could open Visual Studio and do "Open Project", point it to the executable, and Run Debug, this would give us a stack trace.

**Comment by Nalleyer** [comment]
Hi, I ran the example with visual studio 2019, and found there is a problem with ig9icd64.dll.
Then I updated the driver for my Intel graphics card. the example works well for now.
Thank you for your patience
:tada:

**Comment by kvark** [comment]
If you happen to have the stack trace somewhere, we'd still want that to avoid a crash.
It might be handled by https://github.com/gfx-rs/gfx/pull/3674 though already

**Comment by Nalleyer** [comment]
Sorry I forgot to save a screenshot for that.
I remember it seems to be that the visual studio said it cannot load the symbol for ig9icd64.dll because of ig9icd64.pdb.
ths stack starts from ntdll.dll to kernel32??.dll to ... to ig9icd64.dll.

At that time I didn't know if this is a "Valid" stack trace.
