### ISSUE TITLE
map_read/write_async can capture pointers to the stack

### ISSUE THREAD

**Issue by nical** [gfx-rs/wgpu-rs#8]
This code should compile but it does:

```rust
    pub fn do_the_thing(buffer: &wgpu::Buffer) {
        let mut stack_thing: u32 = 1;
        // the FnOnce closure is about to capture `reference_to_the_stack.
        let reference_to_the_stack = &mut stack_thing;
        buffer.map_write_async(0, 0, move |mapping: wgpu::BufferMapAsyncResult<&mut [u8]>| {
            if let wgpu::BufferMapAsyncResult::Success(..) = mapping {
                *reference_to_the_stack = 42;
            }
        });
        println!("stack_thing hasn't been moved into the closure, it's value is {:?}", stack_thing);
    } // stack_thing is gone but the callback still exists with a pointer to it.
```

Normally, rust would prevent you from moving the `FnOnce` callback out of the stack in `map_write_aync`, for example if you tried to push the callback into a vector that outplives that stack you would get:

```
error[E0310]: the parameter type `F` may not live long enough
7 |         self.callbacks.push(Box::new(callback));
  |                             ^^^^^^^^^^^^^^^^^^
  |
note: ...so that the type `C` will meet its required lifetime bounds
```

However the implementation of `map_read/write_async` dodges this borrow check by casting the boxed `BufferMapWriteAsyncUserData` into raw parts.

As a result the callbacks can capture any pointer on the stack and read or write into these memory locations later after the caller's stack is gone.

I believe the correct fix for this is to add the `'static` bound to the `F` parameter.

**Comment by nical** [comment]
I was about to send a pull request with the proposed fix and found out this has already been fixed but the fix hasn't made it to crates.io yet.

**Comment by kvark** [comment]
Ok, closing then. Thanks for the issue!
