### ISSUE TITLE
Clone for ShaderModule and other resources

### ISSUE THREAD

**Issue by gzp-crey** [gfx-rs/wgpu-rs#801]
Is it intentional that ShaderModule is not Clone ?

Both Id and context are clone and as I remember from some really old pr/comments/etc. the resources are ref counted inside the device.
My issue is that I have a background async task that loads/creates all type of resources (shaders, pipeline, etc.) It uses channels to pass resources b/n the loader and render. Render has a store for resources and when required it passes the required elements to the async task. The channel requires an "owned" (handle to) resource the ShaderModule cannot be passed. I could wrap it into an Arc, but all of its member already implements clone and if there is no other reason it'd make sense to make them clone.

Thanks.

**Comment by kvark** [comment]
The ID are not `Arc`-ed internally, so if we implement `Clone` on the shader module, we'd no longer know when it goes out of scope.
