### ISSUE TITLE
Will SPIR-V shader support continue?

### ISSUE THREAD

**Issue by MarioSieg** [gfx-rs/wgpu-rs#804]
Hey I'm planning on creating a new 3D rendering system.
I've seen that all the examples use WGLSL, but I see that WGPU-RS still supports SPIR-V binaries:
https://docs.rs/wgpu/0.7.0/wgpu/enum.ShaderSource.html
I have many shaders written in GLSL from my old engine and I just would like to know if SPIR-V support will continue,
even if the main focus is on WGLSL. I'm not interested in rewriting my shaders because I do not like WGLSL.
So will SPIR-V support continue in the future or will it be dropped?

Best Regards,
Mario

**Comment by kvark** [comment]
We don't have any plans to deprecate SPIR-V shaders when building for native. When targeting the web, however, we can work with SPIR-V today. it would need to be transformed into WGSL, and Naga doesn't have a WGSL backend yet.
So if you are only targeting native, you'll get SPIR-V working for the foreseeable future.

**Comment by MarioSieg** [comment]
Alright, good to know, thank you!
