### ISSUE TITLE
Is the shadow example supposed to look like this?

### ISSUE THREAD

**Issue by lachlansneff** [gfx-rs/wgpu-rs#81]
After the newest update to fix running wgpu on macos, I was able to run the shadow example.

However, it's extremely glitchy looking, I'm worried there are still issues with rendering on macos.

Does this look right?
<img width="797" alt="Screen Shot 2019-09-09 at 10 12 01 PM" src="https://user-images.githubusercontent.com/31360811/64579032-5eed5500-d34f-11e9-8b76-1616cb8fd51c.png">

**Comment by kvark** [comment]
See https://github.com/gfx-rs/wgpu/issues/103
So far all the evidence supports the idea of this being a macOS runtime/driver bug. They don't like something about 2D array textures being used with depth comparison sampling :/ All the upstream bugs are submitted, and we are still waiting for any response from Apple.

**Comment by lachlansneff** [comment]
Ah, interesting. Would it be possible to rewrite the example to use different rendering techniques?

**Comment by kvark** [comment]
It's not entirely clear to me what kind of changes are needed. Involves a bit of experimentation... But should certainly be possible in some way.

**Comment by Grishy** [comment]
Do you have any news?

**Comment by kvark** [comment]
I believe this was fixed in macOS drivers
