### ISSUE TITLE
Application showing blank window, but rending fine when played back from trace.

### ISSUE THREAD

**Issue by 5nefarious** [gfx-rs/wgpu-rs#816]
Discussed here: #812. I'm writing a [test program](https://github.com/5nefarious/render-test) using [Bevy](https://github.com/bevyengine/bevy) and `wgpu-rs` directly. Most of the time, running the application produces a blank window. Not black, but the default window color. However, everything renders fine when I [play back](https://github.com/gfx-rs/wgpu/tree/master/player) the trace.

Saving the `ShaderModule` (to prevent it from being deallocated) seemed to fix the issue, but I was informed by @kvark that this shouldn't be necessary. Also, the problem only returned when I tried to render a texture.

I'm using the Metal backend on macOS, with `wgpu-rs` at version 0.7. A dependency conflict is preventing me from updating to `master`.

**Comment by kvark** [comment]
Thank you for filing! I tried running your code on macOS, and wasn't able to reproduce the issue (even if I remove the lines that save the `ShaderModule`).

**Comment by 5nefarious** [comment]
> Thank you for filing! I tried running your code on macOS, and wasn't able to reproduce the issue (even if I remove the lines that save the `ShaderModule`).

Weird... So everything rendered just fine for you? It consistently doesn't work on my machine for some reason. Thanks for running the code to check!

**Comment by kvark** [comment]
What am I supposed to see? The window was plain red in both cases (with/without the shader module patch).

**Comment by 5nefarious** [comment]
> What am I supposed to see? The window was plain red in both cases (with/without the shader module patch).

Plain red is correct. I get a window that's dark gray (I'm using the dark system theme).

**Comment by 5nefarious** [comment]
For reproducibility: I'm testing commit [f352915](https://github.com/5nefarious/render-test/commit/f3529152f68bc759a83f58c4f1f1b3f72f90ed30) on my repo

**Comment by kvark** [comment]
Indeed, sometimes it's not red! I'll look some more. Thank you for help!

**Comment by kvark** [comment]
Trying to debug from XCode, it's not easy to load the app:
>dyld: Library not loaded: @rpath/libstd-349f286494d73b18.dylib
Referenced from: /Users/dmalyshau/Code/render-test/target/debug/render-test

Is bevy using some complicated scheme to dynamically link to rust's libstd?.. I launch things from XCode regularly, and never seen this error.

**Comment by 5nefarious** [comment]
I had been getting the same exact error whenever I tried to debug the program in `lldb`. I think Bevy is [doing something strange with dynamic linking](https://github.com/bevyengine/bevy/blob/main/crates/bevy_dylib/Cargo.toml), but I don't know if that is what's causing this error.

**Comment by 5nefarious** [comment]
Alright, I think I might have cracked the case. I got debugging with Xcode setup by plugging `$(rustc --print sysroot)/lib` in for `DYLD_LIBRARY_PATH`. When the application didn't render properly, I saw this:

<img width="270" alt="Screen Shot 2021-03-29 at 5 35 48 PM" src="https://user-images.githubusercontent.com/10836441/112903473-8c2a6100-90b5-11eb-9c73-138fc9e6f0f8.png">

Bevy automatically tries to run systems in parallel, and apparently I shouldn't be grabbing window surfaces off of the main thread. Adding my "dispatcher" system to the Bevy plugin with `.excluse_system()` instead of `.system()` appears to have fixed the issue.

@kvark, if you can reproduce this, then I think it's safe to mark this issue as closed, as it doesn't appear to be a problem with `wgpu`.


I noticed something else interesting while using the Metal system trace. There appear to be two Samplers bound as resources, even though I'm only using one.

<img width="571" alt="Screen Shot 2021-03-29 at 5 30 09 PM" src="https://user-images.githubusercontent.com/10836441/112903781-f8a56000-90b5-11eb-9f19-5684a8011c60.png">

**Comment by kvark** [comment]
Thank you for investigating this!
I filed https://github.com/gfx-rs/gfx/issues/3704 to make this experience better in the future.
