### ISSUE TITLE
How do I use gecko branch as a dependency?

### ISSUE THREAD

**Issue by Zageron** [gfx-rs/wgpu-rs#836]
Been digging for a while.

Building the examples on gecko branch works just fine.
Many different combinations of dependencies I have tried have not worked.

I assume I am missing some feature declaration in my Cargo.toml.

```toml
[dependencies]
wgpu = { branch = "gecko", git = "https://github.com/gfx-rs/wgpu-rs" }
```

Results in an exceptional number of errors around js-sys.

```sh
PS L:\git\zageron\silver-palm-tree> env RUSTFLAGS=--cfg=web_sys_unstable_apis cargo build --no-default-features --target wasm32-unknown-unknown
    Blocking waiting for file lock on build directory
   Compiling js-sys v0.3.49
error: expected `,`
   --> C:\Users\Zageron\.cargo\registry\src\github.com-1ecc6299db9ec823\js-sys-0.3.49\src\lib.rs:639:39
    |
639 |         #[wasm_bindgen(js_namespace = Atomics, catch)]
    |                                       ^^^^^^^
```

**Comment by grovesNL** [comment]
Hi! :wave: There was a breaking change in `syn` so we've had to update wasm-bindgen/web-sys/js-sys to newer versions on `master`. It might be easier to use `master` for now. Otherwise you could update the `gecko` branch locally to use new versions, or pin `syn` to an older version (more context in #822 and #821)

**Comment by Zageron** [comment]
> 
> 
> Hi! 👋 There was a breaking change in `syn` so we've had to update wasm-bindgen/web-sys/js-sys to newer versions on `master`. It might be easier to use `master` for now. Otherwise you could update the `gecko` branch locally to use new versions, or pin `syn` to an older version (more context in #822 and #821)

Thanks so much for the details!

**Comment by grovesNL** [comment]
@Zageron were you able to get this working with `master` instead?

**Comment by Zageron** [comment]
> @Zageron were you able to get this working with `master` instead?

Apologies for delay, yes I was able to get it working right away.
