### ISSUE TITLE
vulkan-portability on MacOS panics

### ISSUE THREAD

**Issue by rybertm** [gfx-rs/wgpu-rs#840]
https://github.com/gfx-rs/wgpu-rs/blob/55cafa398868998d1c14620111208d92f5cda9d5/Cargo.toml#L23 sets the `gfx-backend-vulkan` feature inside `wgpu/wgpu-core` but in this crate only `vulkan-portability` gets set, so when `gfx_select!` is expanded it checks for `gfx-backend-vulkan`, which is not present in `wgpu-rs`: https://github.com/gfx-rs/wgpu-rs/blob/55cafa398868998d1c14620111208d92f5cda9d5/src/backend/direct.rs#L593-L595

As for fixing, I could add a `gfx-backend-vulkan` dependency to the `vulkan-portability` feature as well as add it to macos targets, but I don't know if it could break in other unix systems @kvark.

_Originally posted by @rybertm in https://github.com/gfx-rs/wgpu-rs/issues/575#issuecomment-696066934_

**Comment by rybertm** [comment]
Looks like https://github.com/gfx-rs/wgpu-rs/blob/78234dd12030c2c4e7247d8ae1a6df08e299e44d/Cargo.toml#L23
broke the "vulkan-portability" feature for the same reason stated above, quoted from the original issue.

The same fix could be applied unless there's other plans.

**Comment by kvark** [comment]
I'm thinking that, since `gfx_select!` isn't ever used internally by `wgpu-core`, the feature it should be checking should be "vulkan-portability" (instead of "gfx-backend-vulkan"), even though `wgpu-core` doesn't have this feature.

**Comment by rybertm** [comment]
Not sure if i should submit a PR with that change or if you want some discussion around it or ideas

**Comment by kvark** [comment]
A PR would be appreciated!

**Comment by kvark** [comment]
I decided to remove support for Vulkan Portability, at least for the 0.8 release.
The reason for it being - our validation is very good now, and Naga's Metal output is great. So we have very little value to extract from running with Vulkan Validation Layers at this point.
