### ISSUE TITLE
Inverted Y issue

### ISSUE THREAD

**Issue by simast** [gfx-rs/wgpu-rs#842]
After the recent master update (naga was updated in #839) all my shader output is inverted on Y axis. I use .spv shaders.
Just curious if this was intended change and if it is - then what is the recommended way to handle this?

**Comment by kvark** [comment]
This is a bug on our side, sorry about it!
Since our examples now use WGSL exclusively, SPIRV bugs are easier to miss.

**Comment by kvark** [comment]
Should be good once #843 lands

**Comment by simast** [comment]
Thanks for the quick response, I can confirm the issue is fixed.
