### ISSUE TITLE
Version 0.7.1 on crates.io does not correspond to any commit in the repository

### ISSUE THREAD

**Issue by wleslie** [gfx-rs/wgpu-rs#854]
The most recent release on crates.io is [0.7.1](https://crates.io/crates/wgpu/0.7.1), but the master branch still shows 0.7.0 in Cargo.toml. As far as I can tell, there is no other branch in the repo where Cargo.toml has version 0.7.1. Was this release cut from uncommitted code, and if so, can it be checked in?

**Comment by kvark** [comment]
We use branches for breaking revisions, see https://github.com/gfx-rs/wgpu-rs/tree/v0.7
