### ISSUE TITLE
Allow passing non-array struct to Buffer

### ISSUE THREAD

**Issue by JessubKim** [gfx-rs/wgpu-rs#88]
Currently, if you want to pass in any variables to host-side buffer, it must be an array. 
The following extract from lib.rs shows the struct in wgpu-rs that stores host-side buffer's data.
```
pub struct CreateBufferMapped<'a, T> {
    id: wgn::BufferId,
    pub data: &'a mut [T],
}
```

The following shows the implementation of the struct:

```
impl<'a, T> CreateBufferMapped<'a, T>
where
    T: Copy,
{
    pub fn fill_from_slice(self, slice: &[T]) -> Buffer {
        self.data.copy_from_slice(slice);
        self.finish()
    }

    pub fn finish(self) -> Buffer {
        wgn::wgpu_buffer_unmap(self.id);
        Buffer { id: self.id }
    }
}
```

Since the input data type has to be an array, this forces a number of limitations such as not being able to include array count together with the array in the buffer.

**Proposal:**
* Add a new variant of create_buffer_mapped method that allow being passed non-array struct as input data. 
For example, the following shows the input struct that could be allowed to the host-side buffer.

```
struct input_data{
count: usize,
array: Vec[i32]
}
```

Exact details of the new method based off create_buffer_mapped will be added later.

I will create a PR for this if someone can confirm that this feature could be merged in.

**Comment by kvark** [comment]
There would be nothing wrong with having `fill_from_struct` method :+1:

**Comment by kvark** [comment]
fwiw, you can always pass a single struct as a slice, e.g. `&[my_struct]`

**Comment by JessubKim** [comment]
@kvark passing single struct like that works if all members within the struct are constant size. But in my case, because it contains a vector which can vary in size, `create_buffer_mapped` method won't correctly calculate the byte size.

I was able to pass custom struct as u8 array using `fill_from_slice` and it works. (except for some reason, the first byte for an array element is wrong when read using `map_read_async`

**Comment by swiftcoder** [comment]
> But in my case, because it contains a vector which can vary in size, create_buffer_mapped method won't correctly calculate the byte size.

I don't think that is going to work regardless - you can only pass flat types to the GPU. You'll need to serialise your struct into a buffer at some point in this process.

**Comment by JessubKim** [comment]
I tested the `fill_from_slice` and `map_read_async` functions more. I found that simply passing in array of bytes as u8 allow me to write and read custom struct in a buffer with no issue.

Closing this ticket
