### ISSUE TITLE
Incorrect shader arg interpolation lint in v0.8?

### ISSUE THREAD

**Issue by dhardy** [gfx-rs/wgpu-rs#883]
I'm updating KAS to v0.8, and get this error:
```
wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `SR render_pipeline`
    error matching FRAGMENT shader requirements against the pipeline
    location[2] Float32x2 interpolated as Some(Flat) with sampling None is not provided by the previous stage outputs
    input interpolation doesn't match provided Some(Perspective)
```
This appears to be caused by use of `flat` interpolation in my fragment shader:
```
layout(location = 0) flat in vec4 fragColor;
```
This has nothing to do with `Perspective` projections; interpolating or not interpolating shader inputs is valid either way. Or maybe `Perspective` refers to something else than the view projection? Anyway, I don't "need" `flat` here but also see no reason not to use it (since I don't need interpolation of the colour input), so I think this validation error is simply wrong?

**Comment by kvark** [comment]
What it says is that your output color from VS must be interpolated in the same way. I.e. it has to be declared as `layout(location = 0) flat out vec4 fragColor` in VS.

**Comment by kvark** [comment]
cc @jimblandy just in case :)

**Comment by dhardy** [comment]
That solution works. Curious, because I thought I had already tried that only to hit shader compiler error.

Anyway, is this actually an error? On [this page](https://www.khronos.org/opengl/wiki/Type_Qualifier_(GLSL)) I find this quote:

> While interpolation qualifiers can be put on any of these variables, the only ones that actually have an effect are those on the fragment shader. The pre-GL 4.3 rules on matching interfaces mean you have to provide them on other stages, but interpolation is controlled entirely by the qualifiers on the fragment shader input variables.

The specification (section 4.5) covers the interpolation modes but doesn't appear clear on where they may (or should) be used. Maybe that's elsewhere; I haven't read the whole thing.

**Comment by dhardy** [comment]
I guess we can just close this then.
